"""Seven runtime ports defined here and implemented by qma-daemon (AD-1; DEC-0300).

Exactly: MemoryProvider, ModelDeployment, ExecutionEnvironment, KnowledgeSource,
ToolAdapter, ComputeProvider, ContextCompiler. Each declares cardinality; every
singleton declares an explicit scope key.
"""

from __future__ import annotations

from qma.core.ports.cardinality import (
    CONTEXT_COMPILER_SCOPE_KEY,
    MULTI_CONTRIBUTION_POINTS,
    PORT_CONTRACT_BY_NAME,
    PORT_CONTRACTS,
    RETIRED_CONTRIBUTION_POINTS,
    Cardinality,
    PortContract,
    PortError,
    has_qma_wire_schema,
    qualified_contribution_id,
    require_singleton_scope_key,
    validate_contribution_point,
    validate_multi_contribution_key,
)
from qma.core.ports.compute import ComputeProvider
from qma.core.ports.context import ContextCompiler
from qma.core.ports.execution import ExecutionEnvironment
from qma.core.ports.knowledge import KnowledgeSource
from qma.core.ports.memory import MemoryProvider
from qma.core.ports.model import (
    AUTH_MODE_NONE,
    LOCAL_PROXY_ADAPTERS,
    MODEL_FAMILY_ASSIGN_COMMAND,
    OPENCODEX_ADAPTER,
    PROXY_ALLOW_UNAUTHENTICATED_LOOPBACK_KEY,
    DeploymentRecord,
    ModelCapabilities,
    ModelClassRequest,
    ModelDeployment,
    NeedsFlags,
    ReviewPolicy,
    RoutingDecision,
    assign_model_family,
    capabilities_for,
    eligible_pool,
    is_local_proxy_deployment,
    resolve_model_request,
    select_from_eligible,
    select_reviewer,
    unmet_constraint_for,
)
from qma.core.ports.tools import (
    LEAF_BLOCKED_TOOL_TAGS,
    TOOL_ADAPTER_WRITE_COMMAND,
    TOOL_KIND_DEFAULT_RUNG,
    TOOL_KINDS,
    ToolAdapter,
    ToolAdapterBinding,
    ToolAdapterRecord,
    ToolKind,
    ToolRecord,
    ToolsetRecord,
    default_rung_for_kind,
    narrow_toolset_ids,
    select_lowest_capable,
    skill_grants_tool_or_capability,
    subagent_inherited_tool_ids,
    write_tool_adapter_binding,
)

RUNTIME_PORT_TYPES: tuple[type, ...] = (
    MemoryProvider,
    ModelDeployment,
    ExecutionEnvironment,
    KnowledgeSource,
    ToolAdapter,
    ComputeProvider,
    ContextCompiler,
)

__all__ = [
    "AUTH_MODE_NONE",
    "CONTEXT_COMPILER_SCOPE_KEY",
    "LEAF_BLOCKED_TOOL_TAGS",
    "LOCAL_PROXY_ADAPTERS",
    "MODEL_FAMILY_ASSIGN_COMMAND",
    "MULTI_CONTRIBUTION_POINTS",
    "OPENCODEX_ADAPTER",
    "PORT_CONTRACTS",
    "PORT_CONTRACT_BY_NAME",
    "PROXY_ALLOW_UNAUTHENTICATED_LOOPBACK_KEY",
    "RETIRED_CONTRIBUTION_POINTS",
    "RUNTIME_PORT_TYPES",
    "TOOL_ADAPTER_WRITE_COMMAND",
    "TOOL_KINDS",
    "TOOL_KIND_DEFAULT_RUNG",
    "Cardinality",
    "ComputeProvider",
    "ContextCompiler",
    "DeploymentRecord",
    "ExecutionEnvironment",
    "KnowledgeSource",
    "MemoryProvider",
    "ModelCapabilities",
    "ModelClassRequest",
    "ModelDeployment",
    "NeedsFlags",
    "PortContract",
    "PortError",
    "ReviewPolicy",
    "RoutingDecision",
    "ToolAdapter",
    "ToolAdapterBinding",
    "ToolAdapterRecord",
    "ToolKind",
    "ToolRecord",
    "ToolsetRecord",
    "assign_model_family",
    "capabilities_for",
    "default_rung_for_kind",
    "eligible_pool",
    "has_qma_wire_schema",
    "is_local_proxy_deployment",
    "narrow_toolset_ids",
    "qualified_contribution_id",
    "require_singleton_scope_key",
    "resolve_model_request",
    "select_from_eligible",
    "select_lowest_capable",
    "select_reviewer",
    "skill_grants_tool_or_capability",
    "subagent_inherited_tool_ids",
    "unmet_constraint_for",
    "validate_contribution_point",
    "validate_multi_contribution_key",
    "write_tool_adapter_binding",
]
