"""Product-session journal projection (Workflows AD-8; Stories 55.1–55.4).

``product_session`` is not a QMA Session fold and not a tab/window/view.
Occupancy stays none until a live-adjacent story. Public calls are compared
to ``product_session.context``. ``granted_ops`` are grant_ids resolved to
host GrantRecords; mismatch and revoke refuse before execution.
Restart/reconnect restores bound context from the journal; tabs share it
and never mint or close it. ``view:*`` remains an AD-17 wire DTO only
(GAP-0081; SCN-0018 Branch B).
"""

from __future__ import annotations

from qma.daemon.sessions.chrome import ProductSessionChrome
from qma.daemon.sessions.grant_binding import (
    GRANT_ACCEPTED_TABLE,
    GRANT_RECORD_TABLE,
    GRANT_REVOCATION_TABLE,
    GRANT_SIXTH_STORE_MINTED,
    TOOL_REGISTRY_REWRITTEN,
    BoundSessionGrant,
    compare_envelope_to_grant,
)
from qma.daemon.sessions.product_session import (
    ADR_0024_DECISION_REWRITTEN,
    APP_INSTANCE_ID_OPTIONAL_AT_INSPECT_SHA,
    APP_USE_APP_INSTANCE_REQUIRED,
    AUTHORING_APP_INSTANCE_OPTIONAL,
    AUTHORING_INSTANCE_OPTIONAL_INSPECT_SHA,
    CHROME_KINDS,
    CHROME_OWNS_GRANTS,
    CHROME_OWNS_OCCUPANCY,
    DEC_0421_SUPERSEDED_BY,
    DEC_0463_FOLLOWS_DEC_0421,
    ENVELOPE_INSTANCE_ID_REMAINS_REQUIRED,
    GAP_0081_CHROME_FILLED,
    HOME_IS_AUTHORING_WITHOUT_INSTANCE,
    INSTANCE_ID_KIND,
    INSTANCE_ID_KIND_EXISTED_AT_INSPECT_SHA,
    PARENT_AD8_SELECTED_REF_KINDS,
    PRODUCT_SESSION_CONTEXT_FIELDS,
    PRODUCT_SESSION_EXISTED_AT_INSPECT_SHA,
    PRODUCT_SESSION_FOLD_ID,
    PRODUCT_SESSION_ID_PREFIX,
    PRODUCT_SESSION_INSPECT_SHAS,
    PRODUCT_SESSION_LIVE_ADJACENT,
    PRODUCT_SESSION_NEW_CT_MINTED,
    PRODUCT_SESSION_OCCUPANCY,
    PRODUCT_SESSION_OWNER,
    PRODUCT_SESSION_SIXTH_COMP_MINTED,
    PRODUCT_SESSION_SIXTH_STORE_MINTED,
    PRODUCT_SESSION_STORE,
    PRODUCT_SESSION_STORE_CLASS,
    PRODUCT_SESSION_TAB_WRITES,
    PRODUCT_SESSION_TABLE,
    PRODUCT_SESSION_TYPES_EXISTED_AT_INSPECT_SHA_34C148B,
    PRODUCT_SESSION_WIRED_AT_INSPECT_SHA,
    QMA_SESSION_ID_PREFIX,
    RECONNECT_KIND_QUERY,
    RECONNECT_KIND_RESYNC,
    SELECTED_REF_INSPECT_SHA,
    SELECTED_REF_KINDS,
    THIRD_PRODUCT_SESSION_PROFILE_MINTED,
    BoundProductSessionCall,
    ProductSession,
    ProductSessionContext,
    ProductSessionProfile,
    ProductSessionService,
    ReconnectSnapshot,
    SelectedRef,
    bind_public_call_to_context,
    claim_instance_id_selected_ref_kind_at_inspect_sha,
    claim_optional_authoring_instance_at_inspect_sha,
    claim_product_session_at_inspect_sha,
    invoke_instance_id_from_selected_refs,
    looks_like_chrome_id,
    parse_product_session_profile,
    parse_selected_ref,
    parse_selected_refs,
    refuse_ambiguous_instance,
    refuse_chrome_owns_grants,
    refuse_chrome_owns_occupancy,
    refuse_reconnect_replays_intent,
    refuse_tab_as_product_session,
    refuse_tab_mints_session,
    resolve_authoring_invoke_instance,
)

__all__ = [
    "ADR_0024_DECISION_REWRITTEN",
    "APP_INSTANCE_ID_OPTIONAL_AT_INSPECT_SHA",
    "APP_USE_APP_INSTANCE_REQUIRED",
    "AUTHORING_APP_INSTANCE_OPTIONAL",
    "AUTHORING_INSTANCE_OPTIONAL_INSPECT_SHA",
    "CHROME_KINDS",
    "CHROME_OWNS_GRANTS",
    "CHROME_OWNS_OCCUPANCY",
    "DEC_0421_SUPERSEDED_BY",
    "DEC_0463_FOLLOWS_DEC_0421",
    "ENVELOPE_INSTANCE_ID_REMAINS_REQUIRED",
    "GAP_0081_CHROME_FILLED",
    "GRANT_ACCEPTED_TABLE",
    "GRANT_RECORD_TABLE",
    "GRANT_REVOCATION_TABLE",
    "GRANT_SIXTH_STORE_MINTED",
    "HOME_IS_AUTHORING_WITHOUT_INSTANCE",
    "INSTANCE_ID_KIND",
    "INSTANCE_ID_KIND_EXISTED_AT_INSPECT_SHA",
    "PARENT_AD8_SELECTED_REF_KINDS",
    "PRODUCT_SESSION_CONTEXT_FIELDS",
    "PRODUCT_SESSION_EXISTED_AT_INSPECT_SHA",
    "PRODUCT_SESSION_FOLD_ID",
    "PRODUCT_SESSION_ID_PREFIX",
    "PRODUCT_SESSION_INSPECT_SHAS",
    "PRODUCT_SESSION_LIVE_ADJACENT",
    "PRODUCT_SESSION_NEW_CT_MINTED",
    "PRODUCT_SESSION_OCCUPANCY",
    "PRODUCT_SESSION_OWNER",
    "PRODUCT_SESSION_SIXTH_COMP_MINTED",
    "PRODUCT_SESSION_SIXTH_STORE_MINTED",
    "PRODUCT_SESSION_STORE",
    "PRODUCT_SESSION_STORE_CLASS",
    "PRODUCT_SESSION_TABLE",
    "PRODUCT_SESSION_TAB_WRITES",
    "PRODUCT_SESSION_TYPES_EXISTED_AT_INSPECT_SHA_34C148B",
    "PRODUCT_SESSION_WIRED_AT_INSPECT_SHA",
    "QMA_SESSION_ID_PREFIX",
    "RECONNECT_KIND_QUERY",
    "RECONNECT_KIND_RESYNC",
    "SELECTED_REF_INSPECT_SHA",
    "SELECTED_REF_KINDS",
    "THIRD_PRODUCT_SESSION_PROFILE_MINTED",
    "TOOL_REGISTRY_REWRITTEN",
    "BoundProductSessionCall",
    "BoundSessionGrant",
    "ProductSession",
    "ProductSessionChrome",
    "ProductSessionContext",
    "ProductSessionProfile",
    "ProductSessionService",
    "ReconnectSnapshot",
    "SelectedRef",
    "bind_public_call_to_context",
    "claim_instance_id_selected_ref_kind_at_inspect_sha",
    "claim_optional_authoring_instance_at_inspect_sha",
    "claim_product_session_at_inspect_sha",
    "compare_envelope_to_grant",
    "invoke_instance_id_from_selected_refs",
    "looks_like_chrome_id",
    "parse_product_session_profile",
    "parse_selected_ref",
    "parse_selected_refs",
    "refuse_ambiguous_instance",
    "refuse_chrome_owns_grants",
    "refuse_chrome_owns_occupancy",
    "refuse_reconnect_replays_intent",
    "refuse_tab_as_product_session",
    "refuse_tab_mints_session",
    "resolve_authoring_invoke_instance",
]
