"""Closed-and-addable hook registry and HookResult (AD-10, AD-11; FR-Q30/FR-Q31/FR-Q32)."""

from __future__ import annotations

from qma.daemon.hooks.ledger_gate import (
    DAEMON_AUTHORED_ENTRY_KINDS,
    LEDGER_ENTRY_REQUIRED_FIELDS,
    LedgerAppendGateResult,
    LedgerQuarantineRecord,
    LedgerQuarantineStream,
    annotate_ledger_entry,
    evaluate_before_ledger_append,
    is_dispatch_lease_holder,
    is_exempt_ledger_author,
    is_well_formed_ledger_entry,
)
from qma.daemon.hooks.registry import (
    AGENT_REACHABLE_WRITE_VERBS,
    BYPASS_WRITE_PATHS,
    DAEMON_OWNED_HOOK_VERBS,
    PHASE_LESS_CONTROLS,
    HookRegistry,
    HookRegistryEntry,
    PrimitiveInvocation,
    assert_no_bypass_write_path,
    default_empty_hook_result,
    event_names_for_verb,
    resolve_parallel_hook_results,
)
from qma.daemon.hooks.timeouts import (
    HOOK_TIMEOUT_AFTER_KEY,
    HOOK_TIMEOUT_BEFORE_KEY,
    HOOK_TIMEOUT_CONTROL_KEY,
    HOOK_TIMEOUT_KEYS,
    HookTimeoutResolution,
    HookTimeoutTelemetry,
    HookTimeoutTelemetrySink,
    resolve_hook_timeout,
    timeout_registry_key_for_event,
)

__all__ = [
    "AGENT_REACHABLE_WRITE_VERBS",
    "BYPASS_WRITE_PATHS",
    "DAEMON_AUTHORED_ENTRY_KINDS",
    "DAEMON_OWNED_HOOK_VERBS",
    "HOOK_TIMEOUT_AFTER_KEY",
    "HOOK_TIMEOUT_BEFORE_KEY",
    "HOOK_TIMEOUT_CONTROL_KEY",
    "HOOK_TIMEOUT_KEYS",
    "LEDGER_ENTRY_REQUIRED_FIELDS",
    "PHASE_LESS_CONTROLS",
    "HookRegistry",
    "HookRegistryEntry",
    "HookTimeoutResolution",
    "HookTimeoutTelemetry",
    "HookTimeoutTelemetrySink",
    "LedgerAppendGateResult",
    "LedgerQuarantineRecord",
    "LedgerQuarantineStream",
    "PrimitiveInvocation",
    "annotate_ledger_entry",
    "assert_no_bypass_write_path",
    "default_empty_hook_result",
    "evaluate_before_ledger_append",
    "event_names_for_verb",
    "is_dispatch_lease_holder",
    "is_exempt_ledger_author",
    "is_well_formed_ledger_entry",
    "resolve_hook_timeout",
    "resolve_parallel_hook_results",
    "timeout_registry_key_for_event",
]
