"""Emit microstructure.jsonl from curated full-read notes. No production code."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(
    r"C:\Users\Mubarak\Desktop\QMX\workroom\research\2026-09-15_unbounded-market-intelligence"
    r"\extractions\microstructure.jsonl"
)
MD = ".worktrees/mql5-library/data/mql5-library/md"


def R(**kwargs):
    aid = kwargs["article_id"]
    kwargs.setdefault("path", f"{MD}/{aid}.md")
    kwargs.setdefault("family", "microstructure")
    kwargs.setdefault("prior_overlap", False)
    return kwargs


RECORDS = [
    R(
        article_id=22263,
        title="Market Microstructure in MQL5 (Part 1): Robust Foundation",
        author="Max Brown",
        published="2026-05-08",
        subfamily="foundation",
        venue={"class": "futures", "symbol_examples": ["NQ M1"], "notes": "Series aimed at NQ NY-open M1; GMT_OFFSET_HOURS=2 broker constant"},
        method_1liner="Defensive math/data layer (SafeLog/SafeDivide, min sample, trimmed mean/var, FFT, shared structs) for later microstructure metrics.",
        methods=["numerical_guards", "ValidateSymbol/SafeCopyClose", "trimmed_mean_var", "shared_structs OrderFlowSignal/TimeAwareSignal/RobustFractalAnalysis"],
        metrics_proposed=["computation_status", "validation_message", "shared_struct_fields"],
        inputs=["CopyClose", "SymbolInfoDouble"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Foundation only; no predictive labels. Session offset constant is broker-local."},
        evidence_level="L1",
        evidence_notes="Engineering preamble. No empirical edge claim. Declares planned 12-part series including noise/flow/regime.",
        qmx_placement={"MIS": "pattern for not_ready/status on fitted or heavy labelers", "SQS": "none", "Book": "none", "Bot": "none", "not": "do not invent DOM from foundation structs"},
        transfer_caveats=["NQ futures ≠ FX retail ≠ crypto-spot", "GMT+2 hardcode is broker-specific"],
        quotes=["You trade NQ around the New York open and therefore rely on minute-level microstructure to stay ahead of fast price moves."],
    ),
    R(
        article_id=22553,
        title="Market Microstructure in MQL5 (Part 2): Measuring long memory in MQL5 with Hurst estimators",
        author="Max Brown",
        published="2026-05-25",
        subfamily="long_memory",
        venue={"class": "futures", "symbol_examples": ["NQ M1 Globex"], "notes": "133 Globex sessions Nov 2025–May 2026; NY session reset 09:30 ET"},
        method_1liner="Three Hurst estimators (R/S, aggregated variance, absolute moments) blended by confidence; session-boundary reset required.",
        methods=["HurstExponentRS", "aggregated_variance", "absolute_moments", "confidence_weighted_blend", "session_reset"],
        metrics_proposed=["hurst_exponent", "hurst_confidence", "H*_t rolling"],
        inputs=["log returns from closes"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Rolling backward window after 40 post-open bars. Must NOT mix pre/post-open. Empirical thresholds from same 133-session sample (in-sample)."},
        evidence_level="L3",
        evidence_notes="Pooled H≈0.511; rolling mean≈0.48. Author null: blended H does not significantly predict intraday trending across 133 sessions.",
        qmx_placement={"MIS": "slow persistence coordinate with not_ready until warm; drop direction", "SQS": "none — not spread", "Book": "may refuse trend class when H in [0.4,0.6] filter zone", "Bot": "trend vs MR playbook switch is bot/Book, not MIS", "not": "do not treat H>0.5 as entry"},
        transfer_caveats=["NQ M1 near RW boundary; FX/crypto H distributions differ", "tick-volume not used here", "in-sample thresholds"],
        quotes=["Because NQ M1 operates near the random walk boundary... the variation in H across sessions is largely noise around that boundary rather than a structured regime signal."],
    ),
    R(
        article_id=22598,
        title="Market Microstructure in MQL5 (Part 3): Estimating ARFIMA d with GPH",
        author="Max Brown",
        published="2026-05-27",
        subfamily="long_memory",
        venue={"class": "futures", "symbol_examples": ["US100 M1 Globex"], "notes": "72 NY sessions Jan–May 2026; later parts switch to NQ futures proper"},
        method_1liner="GPH log-periodogram estimator of fractional d; cross-check vs Hurst via d≈H−0.5.",
        methods=["GPHEstimator", "PopulateARFIMAAnalysis", "consistency_vs_Hurst"],
        metrics_proposed=["arfima_d", "arfima_confidence (R²)"],
        inputs=["log returns"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Uses past returns in window. R² confidence typically ~0 on RW-like series — flags unreliable."},
        evidence_level="L3",
        evidence_notes="Pooled d=−0.006; agrees with Part 2 near-zero memory. Half of sessions need no fractional differencing beyond log returns.",
        qmx_placement={"MIS": "optional consistency check with Hurst; low R² → not_ready", "SQS": "none", "Book": "none", "Bot": "none", "not": "fractional-diff features for ML without venue recalibration"},
        transfer_caveats=["US100 CFD vs NQ futures distinction later admitted in Part 4", "GPH bandwidth g=0.65 is researcher knob"],
        quotes=["Applying fractional differencing with a non-integer d to this series would be fitting noise."],
    ),
    R(
        article_id=22638,
        title="Market Microstructure in MQL5 (Part 4): Volatility That Remembers",
        author="Max Brown",
        published="2026-06-05",
        subfamily="vol_memory",
        venue={"class": "futures", "symbol_examples": ["NQ E-mini Nasdaq-100 CME Globex"], "notes": "514 NY sessions May 2024–May 2026; explicitly prefers NQ over US100 CFD"},
        method_1liner="MFDFA width Δα, realized/duration-adj vol, fractional vol, FIGARCH-inspired proxy, clustering index, GJR leverage, bipower jump intensity.",
        methods=["MFDFA", "realized_vol", "FIGARCH_proxy", "clustering_index", "GJR_leverage_proxy", "bipower_jump_intensity"],
        metrics_proposed=["multifractal_width", "clustering_index", "leverage_proxy", "jump_intensity", "realized_vol"],
        inputs=["OHLC / log returns"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "session_in_sample", "detail": "Session aggregates and percentiles (e.g. jump P90=2.1%) fitted on 514-session corpus; mid-session use of full-session stats would leak."},
        evidence_level="L3",
        evidence_notes="Mean jump intensity 1.4%, P90 2.1%. Stress regimes show LOWER clustering. NQ Δα median 0.875 vs US100 CFD 0.498 — venue matters.",
        qmx_placement={"MIS": "vol-memory / jump / clustering coordinates with venue=NQ_M1 provenance", "SQS": "none — vol ≠ spread quality", "Book": "stress/jump may shut door", "Bot": "none", "not": "dump ATR into SQS"},
        transfer_caveats=["NQ futures DOM/order-flow richness ≠ CFD ≠ spot FX/crypto", "winsorized skewness artifacts", "FIGARCH is proxy not full MLE"],
        quotes=["NQ is the exchange-traded underlying contract; US100 is a retail CFD product whose price is derived from the index, not from actual futures order flow."],
    ),
    R(
        article_id=23372,
        title="Market Microstructure in MQL5 (Part 8): Micro-Trend Strength",
        author="Max Brown",
        published="2026-07-20",
        subfamily="micro_trend",
        venue={"class": "futures", "symbol_examples": ["NQ M1"], "notes": "514 NY sessions; merges Part 7 regime labels"},
        method_1liner="Signed micro-trend composite: EMA alignment + ATR-normalized price position + slope consistency + tick-volume multiplier − contradiction penalty.",
        methods=["GetMicroTrendStrength", "adaptive_threshold_by_regime_confidence"],
        metrics_proposed=["micro_trend_strength", "micro_trend_class", "persistence_rate"],
        inputs=["OHLC", "tick volume", "ATR", "EMA"],
        volume_semantics="tick_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Bar-by-bar causal. Adaptive thresholds use session-level Part 7 confidence (session aggregate) — mild session-level leakage if applied before session end."},
        evidence_level="L3",
        evidence_notes="Trending sessions highest persistence; Stressed 61.3% flat. Author: tick volume is activity proxy not contracts.",
        qmx_placement={"MIS": "optional strength magnitude without sign; or shadow", "SQS": "none", "Book": "may gate on flat/stressed", "Bot": "signed direction is confluence", "not": "treat tick volume as traded volume"},
        transfer_caveats=["tick volume ≠ traded volume", "NQ-specific adaptive thresholds", "Part 7 regime dependency"],
        quotes=["The volume component uses tick volume rather than traded contract volume."],
    ),
    R(
        article_id=8818,
        title="Prices in DoEasy library (part 59): Object to store data of one tick",
        author="Artyom Trishkin",
        published="2021-02-02",
        subfamily="tick_infra",
        venue={"class": "multi", "symbol_examples": ["EURUSD"], "notes": "Library object over MqlTick; FX demo prints show Last=0 volume=0"},
        method_1liner="CTick object wrapping MqlTick plus computed Ask−Bid spread and change flags.",
        methods=["MqlTick_wrapper", "spread_property", "tick_flags"],
        metrics_proposed=["tick_spread", "bid", "ask", "last", "volume", "flags"],
        inputs=["MqlTick"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Storage object only."},
        evidence_level="L1",
        evidence_notes="Plumbing. Demonstrates FX ticks often have zero Last/volume — venue semantics baked into fields.",
        qmx_placement={"MIS": "none as method", "SQS": "tick bid/ask is raw input to SQS ratio", "Book": "none", "Bot": "none", "not": "assume Last/volume always populated on FX"},
        transfer_caveats=["FX Last/volume often empty", "TICK_FLAG_BUY/SELL only where exchange tape exists"],
        quotes=["An object to store such values will possess additional properties: spread - the difference of Ask and Bid prices"],
    ),
    R(
        article_id=8912,
        title="Prices in DoEasy library (part 60): Series list of symbol tick data",
        author="Artyom Trishkin",
        published="2021-03-17",
        subfamily="tick_infra",
        venue={"class": "fx_retail", "symbol_examples": ["EURUSD"], "notes": "Series list retrieval by index/time"},
        method_1liner="Tick series list with indexed Bid/Ask/Last/Spread accessors for one symbol.",
        methods=["tick_series_list", "indexed_access"],
        metrics_proposed=["spread_by_index"],
        inputs=["CopyTicks / tick objects"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Historical tick store."},
        evidence_level="L1",
        evidence_notes="Infrastructure toward live tick buffers and later DOM.",
        qmx_placement={"MIS": "none", "SQS": "enables per-tick spread sampling", "Book": "none", "Bot": "none", "not": "method claim"},
        transfer_caveats=["broker tick archive quality varies"],
    ),
    R(
        article_id=8952,
        title="Prices in DoEasy library (part 61): Collection of symbol tick series",
        author="Artyom Trishkin",
        published="2021-03-22",
        subfamily="tick_infra",
        venue={"class": "fx_retail", "symbol_examples": ["EURUSD", "AUDUSD"], "notes": "Multi-symbol collection; sample prints Last=0"},
        method_1liner="Collection of per-symbol tick series with day-count configuration.",
        methods=["tick_series_collection"],
        metrics_proposed=[],
        inputs=["ticks"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Store/update only."},
        evidence_level="L1",
        evidence_notes="Multi-symbol plumbing; no analytics.",
        qmx_placement={"MIS": "none", "SQS": "multi-symbol spread surfaces need this shape of store", "Book": "none", "Bot": "none", "not": "analytics"},
        transfer_caveats=["AUDUSD/EURUSD demos are FX retail quotes"],
    ),
    R(
        article_id=8988,
        title="Prices in DoEasy library (part 62): Updating tick series in real time, preparation for working with Depth of Market",
        author="Artyom Trishkin",
        published="2021-03-24",
        subfamily="dom_library",
        venue={"class": "multi", "symbol_examples": [], "notes": "Symbol object gains DOM subscribe flag; MarketBookAdd/Release pairing"},
        method_1liner="Realtime tick series update + symbol-level subscribe/unsubscribe to DOM broadcast.",
        methods=["realtime_tick_update", "MarketBookAdd_Release_lifecycle"],
        metrics_proposed=["dom_subscribed_flag"],
        inputs=["ticks", "BookEvent subscription"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Event plumbing."},
        evidence_level="L1",
        evidence_notes="Critical ops lesson: every DOM subscribe needs matching unsubscribe (ctor/dtor).",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "none", "not": "emit DOM labels without BOOKDEPTH>0"},
        transfer_caveats=["many FX/crypto-spot symbols have BOOKDEPTH=0"],
    ),
    R(
        article_id=9010,
        title="Prices in DoEasy library (part 63): Depth of Market and its abstract request class",
        author="Artyom Trishkin",
        published="2021-03-30",
        subfamily="dom_library",
        venue={"class": "multi", "symbol_examples": [], "notes": "Abstract MqlBookInfo order object; ENUM_BOOK_TYPE four types"},
        method_1liner="Abstract DOM order object from MarketBookGet/OnBookEvent; buy/sell limit/market types.",
        methods=["CMarketBookOrd", "MqlBookInfo_mapping"],
        metrics_proposed=["dom_order_type", "dom_order_volume", "dom_order_price"],
        inputs=["MarketBookGet", "OnBookEvent"],
        volume_semantics="traded_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Live book snapshot object; tester lacks native BookEvent (known MT5 limitation; see also 15748 prior)."},
        evidence_level="L1",
        evidence_notes="Library object model only; no edge study. Resting sizes are cancellable.",
        qmx_placement={"MIS": "only if venue streams depth — depth imbalance with venue tag", "SQS": "resting clusters as locations if promoted later", "Book": "none", "Bot": "none", "not": "fake DOM on BOOKDEPTH=0"},
        transfer_caveats=["NQ futures DOM ≠ spot FX book ≠ crypto-spot L2", "cancelled size ≠ true liquidity"],
    ),
    R(
        article_id=9044,
        title="Prices in DoEasy library (Part 64): Depth of Market, classes of DOM snapshot and snapshot series objects",
        author="Artyom Trishkin",
        published="2021-04-13",
        subfamily="dom_library",
        venue={"class": "multi", "symbol_examples": [], "notes": "Snapshot + series with ms timestamp property"},
        method_1liner="DOM snapshot object (one BookEvent) and snapshot series (time-ordered molds) with max snapshot cap.",
        methods=["CMarketBookSnapshot", "CMBookSeries", "ms_timestamp_sort_key"],
        metrics_proposed=["dom_snapshot_time_msc", "series_length"],
        inputs=["BookEvent sequence"],
        volume_semantics="traded_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Historical series of past snapshots during runtime; not future."},
        evidence_level="L1",
        evidence_notes="Enables runtime DOM history for stats; still no trading method.",
        qmx_placement={"MIS": "depth_imbalance_series if real book", "SQS": "possible block from resting clusters", "Book": "none", "Bot": "none", "not": "strategy solely on book (Santos 15748 prior)"},
        transfer_caveats=["snapshot history only while program runs unless persisted"],
    ),
    R(
        article_id=9095,
        title="Prices and Signals in DoEasy library (Part 65): Depth of Market collection and the class for working with MQL5.com Signals",
        author="Artyom Trishkin",
        published="2021-04-20",
        subfamily="dom_library",
        venue={"class": "multi", "symbol_examples": [], "notes": "Multi-symbol DOM series collection + unrelated Signals service class"},
        method_1liner="Collection of DOM snapshot series across symbols with auto update/prune; plus MQL5.com Signals object (off-family).",
        methods=["CMBookSeriesCollection", "search_sort_stats_hooks"],
        metrics_proposed=["per_symbol_dom_history"],
        inputs=["BookEvent multi-symbol"],
        volume_semantics="traded_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Collection maintenance."},
        evidence_level="L1",
        evidence_notes="Completes DoEasy DOM stack. Signals half is irrelevant to microstructure family.",
        qmx_placement={"MIS": "multi-symbol depth availability flag", "SQS": "none unless blocks", "Book": "none", "Bot": "none", "not": "MQL5.com signals as MIS"},
        transfer_caveats=["collection empty when depth absent"],
    ),
    R(
        article_id=1179,
        title="MQL5 Cookbook: Handling BookEvent",
        author="Denis Kirichenko",
        published="2014-10-22",
        subfamily="dom_ui",
        venue={"class": "futures", "symbol_examples": ["SBRF-12.14 MOEX"], "notes": "Also notes ECN FX aggregator DOM is not exchange book"},
        method_1liner="BookEvent handler template + relative-volume DOM panel; depth count is broker-specific.",
        methods=["OnBookEvent", "MarketBookGet", "relative_volume_bars"],
        metrics_proposed=["dom_depth_levels", "relative_volume_pct"],
        inputs=["BookEvent"],
        volume_semantics="traded_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Live display."},
        evidence_level="L2",
        evidence_notes="MOEX futures demo. States simplest idea: large contiguous volumes as S/R zones — qualitative.",
        qmx_placement={"MIS": "book_available + depth_n if streamed", "SQS": "volume clusters as optional blocks", "Book": "none", "Bot": "none", "not": "ECN FX aggregator as true exchange DOM"},
        transfer_caveats=["DOM depth differs by broker", "ECN FX ≠ exchange L2", "MOEX ≠ crypto-spot"],
        quotes=["In ECN accounts, liquidity providers supply data on the orders, though only within their aggregator model."],
    ),
    R(
        article_id=1793,
        title="MQL5 Cookbook: Implementing Your Own Depth of Market",
        author="Vasiliy Sokolov",
        published="2015-10-09",
        subfamily="dom_ui",
        venue={"class": "multi", "symbol_examples": [], "notes": "CMarketBook class; references MOEX pricing article for matching"},
        method_1liner="CMarketBook convenience class + custom DOM panel with spread, tick chart, bid/ask totals.",
        methods=["CMarketBook", "custom_DOM_panel", "tick_chart_sync"],
        metrics_proposed=["bid_total", "ask_total", "spread_level", "last_at_bid_or_ask"],
        inputs=["BookEvent", "ticks"],
        volume_semantics="traded_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "UI/access layer."},
        evidence_level="L1",
        evidence_notes="Standard library extension pattern. No quantitative edge.",
        qmx_placement={"MIS": "access pattern only", "SQS": "none", "Book": "none", "Bot": "none", "not": "panel as signal"},
        transfer_caveats=["requires real MarketBook stream"],
    ),
    R(
        article_id=3336,
        title="Implementing a Scalping Market Depth Using the CGraphic Library",
        author="Vasiliy Sokolov",
        published="2017-10-26",
        subfamily="dom_ui",
        venue={"class": "multi", "symbol_examples": [], "notes": "Syncs Last to Ask/Bid; tick volume circles"},
        method_1liner="Scalping DOM UI: synchronize tick stream with book; Last forced to Ask/Bid; volume circles proportional to recent max.",
        methods=["tick_book_sync", "CGraphic_DOM", "volume_circle_scaling"],
        metrics_proposed=["synced_last", "relative_deal_volume"],
        inputs=["BookEvent", "ticks"],
        volume_semantics="traded_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Display. Circle diameter uses recent-N max — rolling causal."},
        evidence_level="L1",
        evidence_notes="UI refinement of 1793. Explicitly notes book can change dozens of times/sec.",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "scalping UI is bot-facing", "not": "MIS from graphics"},
        transfer_caveats=["exchange microstructure UI does not transfer to thin FX books"],
    ),
    R(
        article_id=18821,
        title="Analyzing the Hourly Movement of Trading Symbols and Their Spreads in MetaTrader 5",
        author="",
        published="2026-07-14",
        subfamily="spread_cost",
        venue={"class": "fx_retail", "symbol_examples": ["EURUSD", "GBPUSD"], "notes": "Intraday hour-of-day stats; 'Spread' also means inter-symbol pair spread"},
        method_1liner="ISI ProSpread SMA: hour-bucket probabilities for price and (pair) spread modes across sessions.",
        methods=["hour_of_day_histogram", "session_character_table", "four_formula_modes"],
        metrics_proposed=["hour_bull_prob", "sma_spread_or_price", "volatility_index"],
        inputs=["OHLC history", "optional pair spread"],
        volume_semantics="none",
        spread_vs_range_conflation="partial — title mixes bid/ask cost with inter-instrument spread and range/volatility formulas",
        lookahead={"status": "full_sample_thresholds", "detail": "Hourly probabilities estimated on historical window then used as 'edge' — classic in-sample seasonality; not PIT unless frozen."},
        evidence_level="L2",
        evidence_notes="Shows e.g. EURUSD 09:00 up 64%. Promotional conclusion overclaims. Useful as TOD coordinate idea only.",
        qmx_placement={"MIS": "tod_bucket / hour_stats as coordinates", "SQS": "SQS may key baseline off session_id — not off hour-probability", "Book": "may admit/deny hours", "Bot": "directional hour bias is bot", "not": "treat 64% cell as certified edge"},
        transfer_caveats=["FX session mythology; crypto 24/7", "broker TZ/DST", "word 'spread' overloaded"],
        quotes=["ISI ProSpread SMA is more than just an indicator; it is your personal 24/7 statistical analyst."],
    ),
    R(
        article_id=20371,
        title="Formulating Dynamic Multi-Pair EA (Part 6): Adaptive Spread Sensitivity for High-Frequency Symbol Switching",
        author="",
        published="2026-01-30",
        subfamily="spread_cost",
        venue={"class": "fx_retail", "symbol_examples": ["multi-pair"], "notes": "~2-month backtest window Nov 2025–Jan 2026"},
        method_1liner="Multi-symbol router: absolute spread cap + spread/ATR ratio + ranking; disable symbols with bad spreads; strategy behind gate is EMA+RSI.",
        methods=["spread_atr_ratio", "symbol_ranking", "temporary_disable", "absolute_spread_cap"],
        metrics_proposed=["spreadInPips", "spreadATRRatio", "spreadScore", "isTradeable"],
        inputs=["SymbolInfo spread", "ATR"],
        volume_semantics="none",
        spread_vs_range_conflation="warn — MaxSpreadATRRatio mixes cost (spread) with range/vol (ATR); QMX SQS must stay spread-vs-spread-baseline, not ATR",
        lookahead={"status": "causal", "detail": "Live spread vs thresholds. ATR on closed bars if coded correctly; verify no current-bar ATR leak in any port."},
        evidence_level="L2",
        evidence_notes="Architecture useful (execution layer ≠ entry). Backtest short; strategy confound. Defaults MaxAbsoluteSpread=10, MaxSpreadATRRatio=0.25.",
        qmx_placement={"MIS": "spread_pips, spread_vs_session_baseline (not ATR), tradeable_flag", "SQS": "block-only spread RATIO vs session baseline — do NOT import ATR into SQS", "Book": "symbol router / door on tradeable_flag", "Bot": "EMA/RSI entries", "not": "ATR as SQS"},
        transfer_caveats=["spread/ATR conflates cost with volatility", "multi-pair FX retail", "short IS window"],
        quotes=["Instead of trading all pairs blindly, the EA intelligently concentrates activity on the most efficient markets at any given moment"],
    ),
    R(
        article_id=22998,
        title="Measuring broker execution quality in MQL5: Why your live account doesn't match the backtest",
        author="",
        published="2026-08-11",
        subfamily="exec_quality",
        venue={"class": "fx_retail", "symbol_examples": ["XAUUSD"], "notes": "Client-side diagnostics; Instant vs Market vs Exchange execution modes"},
        method_1liner="Execution Quality Monitor: probe (request-to-fill) vs passive OnTradeTransaction approx; slip mean/median/p95; entry/exit asymmetry; observed quoted spread.",
        methods=["probe_trades", "passive_OnTradeTransaction", "slippage_asymmetry", "p95_tail", "CSV_logging"],
        metrics_proposed=["entry_slip_pts", "exit_slip_pts", "slip_asymmetry", "observed_spread_pts", "requote_count_probe", "latency_ms"],
        inputs=["live fills", "ticks at measurement"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Diagnostic of past fills. Passive mode uses quote AFTER fill event — not causal for gating future entries, only for measurement bias."},
        evidence_level="L3",
        evidence_notes="Strong method paper for cost truth. Explicitly distinguishes quoted spread from academic effective spread. Lists 6 limitations.",
        qmx_placement={"MIS": "exec_slip_stats, spread_obs, asymmetry as sensors", "SQS": "not SQS — SQS is live spread vs baseline, not fill slip", "Book": "door/invalidation on bad exec regime", "Bot": "none", "not": "confuse passive approx with true slip"},
        transfer_caveats=["measures whole path not broker alone", "probe costs real spread", "tester ≠ live"],
        quotes=["in market-microstructure literature \"effective spread\" has a precise meaning... I am not using it in that strict sense. Here it is simply the quoted spread observed at measurement time"],
    ),
    R(
        article_id=23299,
        title="Execution Cost and Slippage Sensitivity Analyzer",
        author="",
        published="2026-07-23",
        subfamily="exec_quality",
        venue={"class": "unspecified", "symbol_examples": [], "notes": "Offline deal-ledger reprice; sample strategy cushion 2.49×"},
        method_1liner="Reprice closed-deal ledger under linear cost model; breakeven cost, cushion, PF-at-cost, win erosion, graded score.",
        methods=["deal_ledger_reprice", "breakeven_cost", "cushion_vs_assumed_cost"],
        metrics_proposed=["breakeven_cost_per_deal", "cushion", "pf_at_cost", "win_erosion", "composite_grade"],
        inputs=["deal history CSV"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Offline robustness of past trades; constant cost assumption."},
        evidence_level="L2",
        evidence_notes="Planning tool. Author: real slip not constant; complements WFO/MC. Needs ≥100 deals preferred.",
        qmx_placement={"MIS": "none live", "SQS": "none", "Book": "candidate admission may require cushion gate later", "Bot": "none", "not": "constant slip as live label"},
        transfer_caveats=["linear cost ≠ news/spike slip", "partial exits billed per row"],
    ),
    R(
        article_id=23755,
        title="A Reusable Breakeven Manager in MQL5 with Spread Compensation",
        author="",
        published="2026-09-01",
        subfamily="exec_quality",
        venue={"class": "multi", "symbol_examples": [], "notes": "Execution helper"},
        method_1liner="Breakeven stop manager that adds current spread (and optional buffer) so BE is not instantly stopped out by bid/ask.",
        methods=["spread_compensated_BE"],
        metrics_proposed=["be_price_with_spread"],
        inputs=["position", "current spread"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Trade management utility."},
        evidence_level="L1",
        evidence_notes="Useful reminder that stops hit by spread widening (overlaps prior 21235). Not a sensor model.",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "BE manager is bot/execution", "not": "MIS"},
        transfer_caveats=["broker spread at modify time"],
    ),
    R(
        article_id=2739,
        title="An Example of Developing a Spread Strategy for Moscow Exchange Futures",
        author="",
        published="2017-02-07",
        subfamily="spread_cost",
        venue={"class": "moex_futures", "symbol_examples": ["Si", "RTS"], "notes": "Inter-contract statistical spread, not bid/ask"},
        method_1liner="Linear-regression synthetic of RTS vs Si; trade residual spread slope on M5 with dual-leg orders; real-tick multi-symbol tester.",
        methods=["two_symbol_regression_spread", "LR_slope_signal", "multi_symbol_tester"],
        metrics_proposed=["residual_spread", "LR_slope"],
        inputs=["two futures closes"],
        volume_semantics="none",
        spread_vs_range_conflation="title uses 'spread' as residual between legs — NOT bid/ask quoted spread",
        lookahead={"status": "unclear", "detail": "LR on last 100 bars of residual — causal if on closed bars; A,B fit window must be frozen carefully."},
        evidence_level="L2",
        evidence_notes="Venue-true MOEX futures pairs. Word collision with SQS 'spread'.",
        qmx_placement={"MIS": "none for SQS", "SQS": "NOT this — SQS is bid/ask quality", "Book": "none", "Bot": "pairs trade is bot", "not": "confuse residual spread with quoted spread"},
        transfer_caveats=["MOEX Si/RTS ≠ FX majors ≠ crypto", "correlation regime breaks"],
    ),
    R(
        article_id=14035,
        title="Forex spread trading using seasonality",
        author="",
        published="2025-01-08",
        subfamily="spread_cost",
        venue={"class": "fx_retail", "symbol_examples": [], "notes": "Seasonal inter-symbol spreads"},
        method_1liner="Seasonality approach to forex inter-instrument spread trading (calendar month cycles).",
        methods=["seasonal_spread_cycle"],
        metrics_proposed=["seasonal_phase"],
        inputs=["daily OHLC pairs"],
        volume_semantics="none",
        spread_vs_range_conflation="inter-symbol spread ≠ bid/ask",
        lookahead={"status": "full_sample_thresholds", "detail": "Seasonal patterns typically fit on history then applied — PIT freeze required."},
        evidence_level="L2",
        evidence_notes="Pairs/seasonality research; not microstructure quoted-spread.",
        qmx_placement={"MIS": "calendar month coordinate only", "SQS": "none", "Book": "none", "Bot": "pairs entries", "not": "SQS"},
        transfer_caveats=["naming collision with bid/ask spread"],
    ),
    R(
        article_id=15622,
        title="Evaluating the Quality of Forex Spread Trading Based on Seasonal Factors in MetaTrader 5",
        author="",
        published="2026-05-25",
        subfamily="spread_cost",
        venue={"class": "fx_retail", "symbol_examples": [], "notes": "Quality evaluation of seasonal spread approach D1"},
        method_1liner="Evaluate seasonal spread-trading quality on daily TF for symbols and inter-symbol spreads.",
        methods=["seasonal_quality_eval"],
        metrics_proposed=["seasonal_quality"],
        inputs=["D1 OHLC"],
        volume_semantics="none",
        spread_vs_range_conflation="inter-symbol spread ≠ bid/ask",
        lookahead={"status": "full_sample_thresholds", "detail": "Evaluation on historical seasons; watch train/test leakage."},
        evidence_level="L2",
        evidence_notes="Companion to 14035/18821 cluster. Still not SQS.",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "research only", "not": "SQS"},
        transfer_caveats=["D1 FX seasonality ≠ M1 crypto microstructure"],
    ),
    R(
        article_id=17934,
        title="Advanced Order Execution Algorithms in MQL5: TWAP, VWAP, and Iceberg Orders",
        author="N Soumik",
        published="2025-05-15",
        subfamily="vwap",
        venue={"class": "unspecified", "symbol_examples": [], "notes": "Retail EA wrapping institutional-style slicers; backtest PF claims promotional"},
        method_1liner="Modular ExecutionManager: TWAP time slices, VWAP volume-tracking slices, Iceberg display size; PerformanceAnalyzer for slip/shortfall.",
        methods=["TWAP", "VWAP_execution", "Iceberg", "ExecutionManager_facade"],
        metrics_proposed=["slippage", "implementation_shortfall", "market_impact_proxy"],
        inputs=["orders", "volume profile / time"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "unclear", "detail": "VWAP execution that targets future session volume profile can leak if using realized full-day volume; TWAP is causal on clock."},
        evidence_level="L2",
        evidence_notes="Useful taxonomy of execution algos. Attached backtest metrics (PF 2.34, Sharpe 5.47) are not transferable certificates.",
        qmx_placement={"MIS": "none — execution policy", "SQS": "none", "Book": "may own slice/iceberg policy later", "Bot": "ExecutionManager is bot/broker path", "not": "MIS sizing from VWAP algo"},
        transfer_caveats=["retail MT5 liquidity ≠ dark pools", "tick volume VWAP ≠ institutional VWAP", "promo backtest"],
    ),
    R(
        article_id=22963,
        title="Implementing Anchored VWAP Indicator in MQL5: A Step-by-Step Guide",
        author="",
        published="2026-08-11",
        subfamily="vwap",
        venue={"class": "multi", "symbol_examples": [], "notes": "Explicit tick-volume proxy when real volume absent"},
        method_1liner="Anchored VWAP with fixed or session (D/W/M) reset, optional σ bands, draggable anchor, multi-instance.",
        methods=["anchored_VWAP", "session_reset_VWAP", "stdev_bands", "applied_price_options"],
        metrics_proposed=["avwap", "avwap_band_upper", "avwap_band_lower"],
        inputs=["OHLC", "tick or real volume"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Accumulates from anchor forward on closed bars. Anchor placement by user can be discretionary (not algorithmic leak)."},
        evidence_level="L2",
        evidence_notes="Clean indicator engineering. States tick volume as proxy by asset class.",
        qmx_placement={"MIS": "session_vwap / anchored_vwap as fair-value coordinate", "SQS": "VWAP is not SQS unless later promoted as level block", "Book": "none", "Bot": "pullback vs VWAP is confluence", "not": "call VWAP a DOM"},
        transfer_caveats=["tick volume VWAP on FX is participation proxy", "crypto real volume exchange-specific"],
        quotes=["use tick volume as a practical proxy for trading activity in asset classes where real volume is inaccessible"],
    ),
    R(
        article_id=22990,
        title="Building an Object-Oriented Session VWAP Engine in MQL5",
        author="",
        published="2026-06-29",
        subfamily="vwap",
        venue={"class": "fx_retail", "symbol_examples": ["liquid currency pairs"], "notes": "Daily reset VWAP engine + pullback EA"},
        method_1liner="OOP daily-reset VWAP with deviation bands; argues MA ignores tick-volume so mis-anchors after news.",
        methods=["session_VWAP_engine", "volume_weighted_bands", "pullback_EA"],
        metrics_proposed=["session_vwap", "vwap_deviation"],
        inputs=["price", "tick volume"],
        volume_semantics="tick_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Daily cumulative on closed bars; EA claims closed-bar filters."},
        evidence_level="L2",
        evidence_notes="Good rationale vs SMA. Pullback EA is bot layer.",
        qmx_placement={"MIS": "session_vwap coordinate", "SQS": "not SQS", "Book": "none", "Bot": "pullback EA", "not": "institutional volume claim from tick volume"},
        transfer_caveats=["FX tick volume ≠ institutional traded volume"],
    ),
    R(
        article_id=16984,
        title="Price Action Analysis Toolkit Development (Part 10): External Flow (II) VWAP",
        author="",
        published="2025-01-30",
        subfamily="vwap",
        venue={"class": "fx_retail", "symbol_examples": [], "notes": "MQL5↔Python VWAP signals"},
        method_1liner="EA ships bars to Python; Pandas/NumPy compute VWAP; signals logged back — treats VWAP as S/R.",
        methods=["python_VWAP_service", "socket_or_file_bridge"],
        metrics_proposed=["vwap", "vwap_side"],
        inputs=["OHLCV"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "unclear", "detail": "Depends on whether Python uses only past bars; rolling VWAP must exclude forming bar."},
        evidence_level="L1",
        evidence_notes="Integration demo more than microstructure science. Overlaps later 19290 prior tick VWAP.",
        qmx_placement={"MIS": "weak — prefer in-process VWAP", "SQS": "none", "Book": "none", "Bot": "signal consumer", "not": "external Python as live authority without PIT"},
        transfer_caveats=["IPC latency", "volume field semantics"],
    ),
    R(
        article_id=22063,
        title="Beyond the Clock (Part 1): Building Activity and Imbalance Bars in Python and MQL5",
        author="",
        published="2026-05-08",
        subfamily="imbalance_bars",
        venue={"class": "fx_retail", "symbol_examples": ["currency pair ticks"], "notes": "AFML-style; multi-year tick Parquet"},
        method_1liner="Replace clock bars with tick/volume/dollar/imbalance bars; auto E0[T] calibration; EWM state persistence; zero-tick filter; Python↔MQL5 parity.",
        methods=["tick_bars", "volume_bars", "dollar_bars", "imbalance_bars", "EWM_threshold", "parity_test"],
        metrics_proposed=["bar_imbalance", "activity_threshold", "mean_spread_in_bar"],
        inputs=["ticks", "spread per tick"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Imbalance threshold from EWM of past bars; must persist state and staleness-check across weekends. Time bars need zero-tick drop."},
        evidence_level="L3",
        evidence_notes="Strong sampling-theory method paper. Explicit production failure modes documented.",
        qmx_placement={"MIS": "activity/imbalance sampling as feature clock; mean_spread_in_bar", "SQS": "spread inside bar still not SQS ratio", "Book": "none", "Bot": "none", "not": "train ML on clock bars then claim imbalance-bar edge"},
        transfer_caveats=["FX tick volume ≠ futures volume buckets", "crypto exchange volume fragmentation"],
        quotes=["Time bars are the default because they are easy to construct, not because they are correct."],
    ),
    R(
        article_id=21825,
        title="Creating Custom Indicators in MQL5 (Part 9): Order Flow Footprint Chart with Price Level Volume Tracking",
        author="",
        published="2026-03-26",
        subfamily="footprint",
        venue={"class": "multi", "symbol_examples": [], "notes": "Tick-reconstructed footprint; bid/ask inference from ticks"},
        method_1liner="Footprint: quantize ticks to price levels; delta or bid-vs-ask modes; diagonal imbalance coloring (1.5–4× thresholds).",
        methods=["price_level_volume", "delta_mode", "bid_vs_ask_mode", "diagonal_imbalance"],
        metrics_proposed=["level_delta", "level_bid_vol", "level_ask_vol", "bar_POC"],
        inputs=["ticks"],
        volume_semantics="tick_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Updates on new ticks/closed geometry; color thresholds fixed researcher knobs."},
        evidence_level="L2",
        evidence_notes="Useful OF proxy when DOM missing. Not true aggressor tape; diagonal imbalance heuristics.",
        qmx_placement={"MIS": "footprint_delta / imbalance_proxy labelled proxy", "SQS": "POC levels may become blocks later", "Book": "none", "Bot": "entry confirmation", "not": "call it exchange footprint without last/aggressor"},
        transfer_caveats=["tick up/down ≠ Lee-Ready aggressor", "FX Last often absent"],
    ),
    R(
        article_id=21829,
        title="Creating Custom Indicators in MQL5 (Part 10): Enhancing the Footprint Chart with Per-Bar Volume Sentiment Information Box",
        author="",
        published="2026-03-27",
        subfamily="footprint",
        venue={"class": "multi", "symbol_examples": [], "notes": "UI enhancement of 21825"},
        method_1liner="Per-bar sentiment box: net delta, total volume, buy/sell % on footprint.",
        methods=["per_bar_sentiment_box"],
        metrics_proposed=["net_delta", "buy_pct", "sell_pct"],
        inputs=["footprint arrays"],
        volume_semantics="tick_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Summary of same causal footprint."},
        evidence_level="L1",
        evidence_notes="Presentation layer on Part 9.",
        qmx_placement={"MIS": "net_delta summary", "SQS": "none", "Book": "none", "Bot": "UI", "not": "new science"},
        transfer_caveats=["inherits Part 9 proxy limits"],
    ),
    R(
        article_id=21984,
        title="Creating Custom Indicators in MQL5 (Part 11): Enhancing the Footprint Chart with Market Structure and Order Flow Layers",
        author="",
        published="2026-04-09",
        subfamily="footprint",
        venue={"class": "multi", "symbol_examples": [], "notes": "Adds structure layers on footprint"},
        method_1liner="Footprint + market-structure / order-flow overlay layers (BOS-style confluence on tape proxy).",
        methods=["footprint_plus_structure"],
        metrics_proposed=["structure_flags_on_footprint"],
        inputs=["ticks", "swing structure"],
        volume_semantics="tick_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "unclear", "detail": "Swing structure often uses future confirmation; must verify pivot confirmation lag."},
        evidence_level="L1",
        evidence_notes="Mixes SMC structure with OF proxy — higher leak risk if pivots unconfirmed.",
        qmx_placement={"MIS": "keep OF metrics only", "SQS": "structure levels as blocks if any", "Book": "none", "Bot": "structure+OF confluence", "not": "unconfirmed pivots in MIS"},
        transfer_caveats=["structure lookahead common in SMC ports"],
    ),
    R(
        article_id=2612,
        title="Testing trading strategies on real ticks",
        author="",
        published="2016-08-04",
        subfamily="tick_infra",
        venue={"class": "fx_retail", "symbol_examples": [], "notes": "MT5 tester modes comparison"},
        method_1liner="Compare OHLC / Every-tick / Every-tick-real: trade counts and PnL diverge; real ticks slowest but most accurate.",
        methods=["tester_mode_comparison"],
        metrics_proposed=["tick_count", "mode_dependent_pnl"],
        inputs=["tester"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Tester methodology."},
        evidence_level="L3",
        evidence_notes="Concrete table: OHLC +169 vs Every-tick −466 vs Real −97 on same EA — mode is not a footnote.",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "none", "not": "trust OHLC backtests for scalp/microstructure"},
        transfer_caveats=["broker real-tick archive gaps fall back to synthetic"],
        quotes=["testing on real ticks is most accurate but time-consuming"],
    ),
    R(
        article_id=11106,
        title="Developing a Replay System — Market simulation (Part 17): Ticks and more ticks (I)",
        author="",
        published="2023-11-30",
        subfamily="tick_infra",
        venue={"class": "multi", "symbol_examples": [], "notes": "Custom replay/simulator"},
        method_1liner="Replay system tick handling part I — feeding/simulating ticks for custom symbols.",
        methods=["replay_ticks"],
        metrics_proposed=[],
        inputs=["stored ticks"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Simulator infra."},
        evidence_level="L1",
        evidence_notes="Needed for DOM/tick research without live book; simulated ≠ evidence.",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "none", "not": "treat sim BookEvent as live proof"},
        transfer_caveats=["custom-symbol ticks are not broker truth"],
    ),
    R(
        article_id=11113,
        title="Developing a Replay System — Market simulation (Part 18): Ticks and more ticks (II)",
        author="",
        published="2023-12-08",
        subfamily="tick_infra",
        venue={"class": "multi", "symbol_examples": [], "notes": "Continuation"},
        method_1liner="Replay ticks part II — further tick simulation/control in market replay.",
        methods=["replay_ticks_ii"],
        metrics_proposed=[],
        inputs=["stored ticks"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Simulator."},
        evidence_level="L1",
        evidence_notes="Pairs with 11106.",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "none", "not": "sim as venue"},
        transfer_caveats=["same as 11106"],
    ),
    R(
        article_id=23465,
        title="Exporting Symbol Tick Data to Binary Files in MQL5 for Offline Analysis",
        author="",
        published="2026-08-06",
        subfamily="tick_infra",
        venue={"class": "multi", "symbol_examples": [], "notes": "Offline research path"},
        method_1liner="Export ticks to compact binary for offline Python/research — prerequisite for imbalance bars / slip studies.",
        methods=["tick_binary_export"],
        metrics_proposed=[],
        inputs=["CopyTicks"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Export."},
        evidence_level="L1",
        evidence_notes="Enables AFML-style offline work (22063).",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "none", "not": "analytics"},
        transfer_caveats=["export completeness = broker history"],
    ),
    R(
        article_id=22460,
        title="Creating a Custom Tick Chart in MQL5",
        author="",
        published="2026-05-11",
        subfamily="tick_infra",
        venue={"class": "multi", "symbol_examples": [], "notes": "Visualization"},
        method_1liner="Custom tick chart rendering from tick stream.",
        methods=["tick_chart"],
        metrics_proposed=[],
        inputs=["ticks"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "UI."},
        evidence_level="L1",
        evidence_notes="Display only.",
        qmx_placement={"MIS": "none", "SQS": "none", "Book": "none", "Bot": "UI", "not": "signal"},
        transfer_caveats=[],
    ),
    R(
        article_id=18680,
        title="MetaTrader tick info access from MQL5 services to Python application using sockets",
        author="",
        published="2025-07-28",
        subfamily="tick_infra",
        venue={"class": "multi", "symbol_examples": [], "notes": "IPC"},
        method_1liner="Socket bridge of tick info from MQL5 service to Python.",
        methods=["tick_socket_bridge"],
        metrics_proposed=[],
        inputs=["ticks"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Transport."},
        evidence_level="L1",
        evidence_notes="Transport for external analytics.",
        qmx_placement={"MIS": "none live authority", "SQS": "none", "Book": "none", "Bot": "none", "not": "Python process as MIS"},
        transfer_caveats=["IPC failure modes"],
    ),
    R(
        article_id=20327,
        title="Analytical Volume Profile Trading (AVPT): Liquidity Architecture, Market Memory, and Algorithmic Execution",
        author="",
        published="2025-11-24",
        subfamily="liquidity_proxy",
        venue={"class": "unspecified", "symbol_examples": [], "notes": "Volume profile as 'liquidity architecture'"},
        method_1liner="Volume-profile / market-memory framing for algorithmic execution around HVN/LVN.",
        methods=["volume_profile", "HVN_LVN"],
        metrics_proposed=["POC", "VAH", "VAL"],
        inputs=["OHLCV"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "unclear", "detail": "Session VP built with future bars of the session leaks if used mid-session without expanding-window discipline."},
        evidence_level="L1",
        evidence_notes="Conceptual. 'Liquidity' here is volume-at-price, not book depth.",
        qmx_placement={"MIS": "poc/vah/val as coordinates if causal", "SQS": "VP nodes as optional blocks", "Book": "none", "Bot": "execution around profile", "not": "equate VP to DOM liquidity"},
        transfer_caveats=["tick volume profile ≠ exchange volume profile"],
    ),
    R(
        article_id=23550,
        title="Building a Volume-Based Liquidity Heatmap Indicator in MQL5",
        author="",
        published="2026-08-10",
        subfamily="liquidity_proxy",
        venue={"class": "multi", "symbol_examples": [], "notes": "Author admits no OI/liquidation feed"},
        method_1liner="High-volume candle filter → estimated liquidation levels via leverage assumption → heatmap bubbles until swept.",
        methods=["volume_SMA_filter", "synthetic_liquidation_price", "heatmap_tiers"],
        metrics_proposed=["liq_level_estimate", "signal_strength_rank"],
        inputs=["OHLC", "tick or real volume"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "New-bar gated. Extending levels forward is display, not label leak."},
        evidence_level="L2",
        evidence_notes="Honest caveat: probabilistic estimate, not real liquidations/OI.",
        qmx_placement={"MIS": "weak proxy only with explicit synthetic tag", "SQS": "sweep levels as blocks if ever", "Book": "none", "Bot": "discretionary", "not": "treat as true crypto liquidation heatmap"},
        transfer_caveats=["no OI on MT5", "leverage assumption arbitrary", "crypto exchange liq maps differ"],
        quotes=["the displayed levels are probabilistic estimates derived from price and volume data only, not actual liquidation or open interest data"],
    ),
    R(
        article_id=22342,
        title="Building a Liquidity Spectrum Volume Profile Indicator in MQL5",
        author="",
        published="2026-05-01",
        subfamily="liquidity_proxy",
        venue={"class": "multi", "symbol_examples": [], "notes": "VP spectrum visualization"},
        method_1liner="Volume-profile 'liquidity spectrum' indicator — volume-at-price distribution styling.",
        methods=["liquidity_spectrum_VP"],
        metrics_proposed=["spectrum_bins"],
        inputs=["OHLCV"],
        volume_semantics="mixed",
        spread_vs_range_conflation=False,
        lookahead={"status": "unclear", "detail": "Depends on lookback closed vs forming bar."},
        evidence_level="L1",
        evidence_notes="Naming: liquidity = volume profile again.",
        qmx_placement={"MIS": "optional VP features", "SQS": "possible blocks", "Book": "none", "Bot": "none", "not": "DOM"},
        transfer_caveats=["volume semantics"],
    ),
    R(
        article_id=18661,
        title="Analyzing Price Time Gaps in MQL5 (Part II): Creating a Heat Map of Liquidity Distribution Over Time",
        author="",
        published="2026-06-05",
        subfamily="liquidity_proxy",
        venue={"class": "multi", "symbol_examples": [], "notes": "Gap/time heatmap"},
        method_1liner="Heatmap of 'liquidity distribution over time' from price time-gap analysis — activity timing, not book.",
        methods=["time_gap_heatmap"],
        metrics_proposed=["liquidity_time_heat"],
        inputs=["OHLC times"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "causal", "detail": "Historical heatmap of activity."},
        evidence_level="L1",
        evidence_notes="Session/activity coordinate cousin; word liquidity overloaded.",
        qmx_placement={"MIS": "activity TOD heatmap", "SQS": "none", "Book": "none", "Bot": "none", "not": "book liquidity"},
        transfer_caveats=["gaps on 24/7 crypto differ from FX weekends"],
    ),
    R(
        article_id=21876,
        title="How to Detect Round-Number Liquidity in MQL5",
        author="Mostafa Ghanbari",
        published="2026-04-23",
        subfamily="liquidity_proxy",
        venue={"class": "multi", "symbol_examples": ["FX", "BTCUSD", "GOLD"], "notes": "Psychological round numbers as 'liquidity'"},
        method_1liner="ZeroSize strength via tick-size normalize + trailing-zero string count; draw major/minor round levels.",
        methods=["GetZeroCount", "round_number_levels"],
        metrics_proposed=["zero_size", "round_level_price"],
        inputs=["price", "SYMBOL_TRADE_TICK_SIZE"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Deterministic level generator from price grid — not predictive."},
        evidence_level="L2",
        evidence_notes="Engineering fix for modulo FP bugs. Anecdotal pin-bar chart — not a study.",
        qmx_placement={"MIS": "none", "SQS": "round levels as optional SQS blocks (locations)", "Book": "none", "Bot": "reaction trades", "not": "call round numbers DOM liquidity"},
        transfer_caveats=["psychological levels ≠ resting liquidity", "Digits differ by symbol"],
    ),
    R(
        article_id=15895,
        title="Scalping Orderflow for MQL5",
        author="",
        published="2024-09-19",
        subfamily="negative_example",
        venue={"class": "fx_retail", "symbol_examples": ["EURUSD M5/M15"], "notes": "Prior miner B already flagged as mashup"},
        method_1liner="Mashup 'orderflow' EA: indicators + dynamic sizing; not tape/DOM; weak PF / DD risk admitted.",
        methods=["indicator_mashup_labelled_orderflow"],
        metrics_proposed=[],
        inputs=["OHLC indicators"],
        volume_semantics="tick_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "unclear", "detail": "Typical indicator EA; not audited."},
        evidence_level="L1",
        evidence_notes="Negative example: title says orderflow, body is TA mashup. Low PF, frequent small wins vs large losses.",
        qmx_placement={"MIS": "reject as OF source", "SQS": "none", "Book": "none", "Bot": "out of scope", "not": "import as VPIN/DOM"},
        transfer_caveats=["naming fraud relative to true OF"],
        quotes=["Despite the strategy's high win rates and modest profitability, it may not be able to produce large returns due to its low profit factor"],
    ),
    R(
        article_id=8136,
        title="Price series discretization, random component and noise",
        author="",
        published="2020-11-23",
        subfamily="noise_theory",
        venue={"class": "multi", "symbol_examples": ["MOEX-informed theory", "FX tick counts"], "notes": "Links to exchange pricing article"},
        method_1liner="Argues clock bars inject noise; prefers tick/block-of-ticks discretization; price formation is discrete book matching.",
        methods=["anti_clock_bar_argument", "tick_block_sampling"],
        metrics_proposed=["theoretical_bar_size_from_tick_stats"],
        inputs=["ticks", "tick volume"],
        volume_semantics="tick_volume",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Theory / measurement of discretization bias."},
        evidence_level="L2",
        evidence_notes="Conceptual backbone for 22063. Reminds DOM matching creates discrete prices/volumes.",
        qmx_placement={"MIS": "motivates activity bars / noise metrics", "SQS": "none", "Book": "none", "Bot": "none", "not": "assume M1 OHLC is faithful tape"},
        transfer_caveats=["ticks themselves still discretize"],
        quotes=["Discretization of a price series into time intervals introduces a significant random component"],
    ),
    R(
        article_id=20287,
        title="Automating Black-Scholes Greeks: Advanced Scalping and Microstructure Trading",
        author="",
        published="2025-11-21",
        subfamily="negative_example",
        venue={"class": "unspecified", "symbol_examples": [], "notes": "Title bait"},
        method_1liner="BS Greeks automation labelled as microstructure scalping — options greeks, not book/spread science.",
        methods=["black_scholes_greeks"],
        metrics_proposed=["delta", "gamma", "theta", "vega"],
        inputs=["option model inputs"],
        volume_semantics="none",
        spread_vs_range_conflation=False,
        lookahead={"status": "n/a", "detail": "Options model."},
        evidence_level="L1",
        evidence_notes="Title false friend for this family. Skip for SQS/DOM work.",
        qmx_placement={"MIS": "reject for this family", "SQS": "none", "Book": "none", "Bot": "options bot elsewhere", "not": "microstructure"},
        transfer_caveats=["options ≠ spot microstructure"],
    ),
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        for rec in RECORDS:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print(f"wrote {len(RECORDS)} records -> {OUT}")
    # uniqueness check
    ids = [r["article_id"] for r in RECORDS]
    assert len(ids) == len(set(ids)), "duplicate ids"
    prior = {9804, 23355, 22938, 22939, 15748, 19290, 22772, 18867, 1575, 21235, 16752, 9231,
             17737, 23286, 22940, 16830, 15223, 23482, 23016, 10715, 23454, 21003, 14203, 19944}
    overlap = set(ids) & prior
    print("overlap with prior24", overlap)
    print("new_count", len(ids))


if __name__ == "__main__":
    main()
