"""Closed-and-addable vocabularies declared in qma-core (FR-Q08, FR-Q10).

Every member identifies the architecture decision that owns any extension.
Locally invented values fail executable validation. Serialization is
``lower_snake_case`` except ``ModelClass`` (SCREAMING_SNAKE) and handle kinds
(CamelCase type names) (AR-Q14).
"""

from __future__ import annotations

from qma.core.vocabulary.acts import (
    ACT_TARGET,
    GovernedAct,
    GovernedActTarget,
    validate_governed_act,
)
from qma.core.vocabulary.enums import (
    JOB_HANDLE_NONTERMINAL_STATES,
    JOB_HANDLE_TERMINAL_STATES,
    JOB_HANDLE_TO_TASK_STATE,
    TASK_EMITTING_NODE_KINDS,
    TASK_MISSION_NONTERMINAL_STATES,
    TASK_MISSION_TERMINAL_STATES,
    AskOnTimeout,
    DeliveryState,
    EnvironmentLifecycle,
    ExecutionEnvironmentKind,
    GraphArtifactKind,
    HandleKind,
    HookControl,
    HookResultDecision,
    HookVerb,
    JobHandleState,
    MemoryValidationState,
    MessageKind,
    ModelClass,
    NetworkPolicy,
    NodeKind,
    PrincipalClass,
    RefinementEditKind,
    RoutingPolicy,
    SessionAutonomy,
    TaskMissionState,
    VariableEditability,
    VariableScope,
    is_job_handle_terminal,
    is_task_mission_terminal,
    map_job_handle_to_task_state,
)
from qma.core.vocabulary.handles import (
    MONEY_PATH_LIVE_WRITABLE_HANDLE_KINDS,
    READ_ONLY_EVIDENCE_HANDLE_KINDS,
    assert_handle_kind_not_money_path,
)
from qma.core.vocabulary.hooks import (
    BEFORE_LEDGER_APPEND_EVENT,
    HOOK_CONTROLS,
    HOOK_EVENT_NAMES,
    HOOK_RESULT_FIELDS,
    HOOK_RESULT_PRECEDENCE,
    HOOK_TIMEOUT_REASON,
    HOOK_VERBS,
    assert_decision_legal_for_event,
    assert_fields_legal_for_event,
    build_hook_event_names,
    empty_result_decision_for_event,
    hook_result_rank,
    legal_decisions_for_event,
    legal_fields_for_event,
    most_restrictive_hook_result,
    parse_hook_event_name,
    timeout_decision_for_event,
    validate_registration_phase_law,
)
from qma.core.vocabulary.principals import (
    assert_no_principal_conversion,
    may_convert_principal,
)
from qma.core.vocabulary.registry import (
    CLOSED_VOCABULARIES,
    HOST_REQUEST_OWNING_AD,
    HOST_REQUEST_VOCABULARY_OWNER,
    ClosedVocabulary,
    VocabularyError,
    parse_closed,
)

__all__ = [
    "ACT_TARGET",
    "BEFORE_LEDGER_APPEND_EVENT",
    "CLOSED_VOCABULARIES",
    "HOOK_CONTROLS",
    "HOOK_EVENT_NAMES",
    "HOOK_RESULT_FIELDS",
    "HOOK_RESULT_PRECEDENCE",
    "HOOK_TIMEOUT_REASON",
    "HOOK_VERBS",
    "HOST_REQUEST_OWNING_AD",
    "HOST_REQUEST_VOCABULARY_OWNER",
    "JOB_HANDLE_NONTERMINAL_STATES",
    "JOB_HANDLE_TERMINAL_STATES",
    "JOB_HANDLE_TO_TASK_STATE",
    "MONEY_PATH_LIVE_WRITABLE_HANDLE_KINDS",
    "READ_ONLY_EVIDENCE_HANDLE_KINDS",
    "TASK_EMITTING_NODE_KINDS",
    "TASK_MISSION_NONTERMINAL_STATES",
    "TASK_MISSION_TERMINAL_STATES",
    "AskOnTimeout",
    "ClosedVocabulary",
    "DeliveryState",
    "EnvironmentLifecycle",
    "ExecutionEnvironmentKind",
    "GovernedAct",
    "GovernedActTarget",
    "GraphArtifactKind",
    "HandleKind",
    "HookControl",
    "HookResultDecision",
    "HookVerb",
    "JobHandleState",
    "MemoryValidationState",
    "MessageKind",
    "ModelClass",
    "NetworkPolicy",
    "NodeKind",
    "PrincipalClass",
    "RefinementEditKind",
    "RoutingPolicy",
    "SessionAutonomy",
    "TaskMissionState",
    "VariableEditability",
    "VariableScope",
    "VocabularyError",
    "assert_decision_legal_for_event",
    "assert_fields_legal_for_event",
    "assert_handle_kind_not_money_path",
    "assert_no_principal_conversion",
    "build_hook_event_names",
    "empty_result_decision_for_event",
    "hook_result_rank",
    "is_job_handle_terminal",
    "is_task_mission_terminal",
    "legal_decisions_for_event",
    "legal_fields_for_event",
    "map_job_handle_to_task_state",
    "may_convert_principal",
    "most_restrictive_hook_result",
    "parse_closed",
    "parse_hook_event_name",
    "timeout_decision_for_event",
    "validate_governed_act",
    "validate_registration_phase_law",
]
