"""Mission Compiler, Task Graph state, and dispatcher (AD-12, AD-13; FR-Q27–FR-Q29)."""

from __future__ import annotations

from qma.daemon.taskgraph.compiler import (
    CompileRequest,
    CompileResult,
    GraphTemplateCatalog,
    MissionCompiler,
    validate_approval_route,
)
from qma.daemon.taskgraph.dispatcher import (
    DispatchDecision,
    TaskGraphDispatcher,
    TaskGraphStore,
    TaskTransitionResult,
    validate_proposed_transition,
)
from qma.daemon.taskgraph.execution import (
    DAEMON_CONTRIBUTED_GRAPH_TEMPLATES,
    DEFERRED_GRAPH_EXCLUSIONS,
    MISSION_TEMPLATE_REGISTRY,
    REDUCING_EDGE_MAPPINGS,
    TOPOLOGY_REFUSAL_CODES,
    TOPOLOGY_REFUSAL_FAMILY,
    ControlPrimitive,
    LoopNodeState,
    Skill,
    assert_template_not_interchanged,
    deterministic_task_id,
    emits_task,
    holds_dispatch_lease,
    loop_state_from_node_config,
    mint_loop_iteration_task,
    node_carries_ledger,
    validate_graph_template_topology,
    validate_no_daemon_graph_template,
)
from qma.daemon.taskgraph.procedures import (
    execute_procedure_door_step,
    instantiate_procedure,
)
from qma.daemon.taskgraph.records import (
    MISSION_DIRECTOR_ROLE,
    RESERVED_APPROVAL_ROUTE_OPERATOR,
    DispatchLease,
    GraphTemplate,
    MissionRecord,
    ProposedTransition,
    TaskGraph,
    TaskGraphNode,
    TaskLedger,
    TaskRecord,
    derive_mission_desk,
)
from qma.daemon.taskgraph.state import (
    JobHandleEvidence,
    compute_mission_state,
    task_state_from_job_handle,
    validate_never_dispatched_cancel,
    validate_terminal_evidence,
    validate_unique_terminal,
)

__all__ = [
    "DAEMON_CONTRIBUTED_GRAPH_TEMPLATES",
    "DEFERRED_GRAPH_EXCLUSIONS",
    "MISSION_DIRECTOR_ROLE",
    "MISSION_TEMPLATE_REGISTRY",
    "REDUCING_EDGE_MAPPINGS",
    "RESERVED_APPROVAL_ROUTE_OPERATOR",
    "TOPOLOGY_REFUSAL_CODES",
    "TOPOLOGY_REFUSAL_FAMILY",
    "CompileRequest",
    "CompileResult",
    "ControlPrimitive",
    "DispatchDecision",
    "DispatchLease",
    "GraphTemplate",
    "GraphTemplateCatalog",
    "JobHandleEvidence",
    "LoopNodeState",
    "MissionCompiler",
    "MissionRecord",
    "ProposedTransition",
    "Skill",
    "TaskGraph",
    "TaskGraphDispatcher",
    "TaskGraphNode",
    "TaskGraphStore",
    "TaskLedger",
    "TaskRecord",
    "TaskTransitionResult",
    "assert_template_not_interchanged",
    "compute_mission_state",
    "derive_mission_desk",
    "deterministic_task_id",
    "emits_task",
    "execute_procedure_door_step",
    "holds_dispatch_lease",
    "instantiate_procedure",
    "loop_state_from_node_config",
    "mint_loop_iteration_task",
    "node_carries_ledger",
    "task_state_from_job_handle",
    "validate_approval_route",
    "validate_graph_template_topology",
    "validate_never_dispatched_cancel",
    "validate_no_daemon_graph_template",
    "validate_proposed_transition",
    "validate_terminal_evidence",
    "validate_unique_terminal",
]
