"""qml — the QMX bot-authoring library.

One uv-installable pure distribution (``import qml``), an application-layer
product built on QMF, never a roster package, never a framework, never an
engine, and never a CLI (DEC-0171, DEC-0185). Imports ``qmf-core``,
``qmf-registry``, and ``qmf-risk`` only; never ``qmf-venue``.

``__version__`` is display-only SemVer provenance and never enters ``fp1``
(DEC-0180). Identity lives on CT-33 content and the logic source-manifest.
"""

from __future__ import annotations

from qml.conformance import (
    CONFORMANCE_FORMAT_VERSION,
    DENIAL_SET,
    ConformanceTicket,
    evaluate_ticket,
)
from qml.declaration import (
    BOT_DEFINITION_KIND_FORMAT_VERSION,
    CONFLUENCE_KIND_FORMAT_VERSION,
    CONSTRAINT_OPS,
    FORBIDDEN_BOT_FIELDS,
    FORBIDDEN_CONDITION_FIELDS,
    KIND_BOT_DEFINITION,
    KIND_CONFLUENCE,
    LEG_ROLES,
    PARAMETER_TYPES,
    PERMITTED_EXIT_INTENT_VOCABULARY,
    REGISTRY_ENVELOPE_FORMAT_VERSION,
    AuthoredArtifact,
    AuthoredKind,
    BotDefinition,
    BotVersionGraph,
    Confluence,
    ConfluenceCite,
    ConfluenceLeg,
    ConfluenceOrdering,
    CurrentPointer,
    HardConstraintFilter,
    LegRole,
    ParameterSpec,
    ParameterType,
    UiFlag,
    bot_definition_kind_contract,
    branches_from_edge,
    confluence_kind_contract,
    continues_performance_edge,
    install_bot_definition_kind,
    install_confluence_kind,
    mint_bot_definition,
    mint_confluence,
    parse_leg_role,
    parse_ordering,
    parse_parameter_type,
    parse_ui_flag,
    promote_tuned_assignment,
    register_bot_definition,
    register_confluence,
    resolve_confluence_at_layer1,
)
from qml.families import (
    FAMILY_KEYED_SURFACES,
    FORBIDDEN_AUTHORITY_FIELDS,
    KIND_STRATEGY_FAMILY,
    STRATEGY_FAMILY_KIND_FORMAT_VERSION,
    FamilyKeyedSurface,
    StrategyFamilyId,
    StrategyFamilyRecord,
    mint_strategy_family,
    resolve_family_at_layer1,
)
from qml.footprint import (
    AD22_IDENTITY_FIELDS,
    CompletenessReport,
    Footprint,
    Horizon,
    ProducerBinding,
    ProducerBindingForm,
    ProducerKind,
    ProducerTemplate,
    ResolvedProducer,
    StreamMember,
    StreamRole,
    derive_horizon,
    mint_footprint,
    mint_producer_template,
    parse_binding_form,
    report_completeness,
    resolve_template,
)
from qml.logic import (
    LOGIC_REFERENCE_CLASS,
    LogicIdentity,
    fingerprint_source_manifest,
    mint_logic_identity,
    normalize_source_manifest,
    resolve_logic_at_layer1,
)
from qml.protocol import (
    PROTOCOL_CONTRACT_CLASS,
    PROTOCOL_DENIAL_SET,
    PROTOCOL_FORMAT_VERSION,
    PROTOCOL_LADDER,
    BotCallback,
    BotFactory,
    BotIntent,
    FootprintEvidence,
    FunctionFactory,
    HostedBot,
    MappingReadSurface,
    PresenceState,
    ReadSurface,
    accept_intents,
    construct_bot,
    permitted_exit_kinds,
    protocol_contract_identity,
)

__all__ = [
    "AD22_IDENTITY_FIELDS",
    "BOT_DEFINITION_KIND_FORMAT_VERSION",
    "CONFLUENCE_KIND_FORMAT_VERSION",
    "CONFORMANCE_FORMAT_VERSION",
    "CONSTRAINT_OPS",
    "DENIAL_SET",
    "FAMILY_KEYED_SURFACES",
    "FORBIDDEN_AUTHORITY_FIELDS",
    "FORBIDDEN_BOT_FIELDS",
    "FORBIDDEN_CONDITION_FIELDS",
    "KIND_BOT_DEFINITION",
    "KIND_CONFLUENCE",
    "KIND_STRATEGY_FAMILY",
    "LEG_ROLES",
    "LOGIC_REFERENCE_CLASS",
    "PARAMETER_TYPES",
    "PERMITTED_EXIT_INTENT_VOCABULARY",
    "PROTOCOL_CONTRACT_CLASS",
    "PROTOCOL_DENIAL_SET",
    "PROTOCOL_FORMAT_VERSION",
    "PROTOCOL_LADDER",
    "REGISTRY_ENVELOPE_FORMAT_VERSION",
    "STRATEGY_FAMILY_KIND_FORMAT_VERSION",
    "AuthoredArtifact",
    "AuthoredKind",
    "BotCallback",
    "BotDefinition",
    "BotFactory",
    "BotIntent",
    "BotVersionGraph",
    "CompletenessReport",
    "Confluence",
    "ConfluenceCite",
    "ConfluenceLeg",
    "ConfluenceOrdering",
    "ConformanceTicket",
    "CurrentPointer",
    "FamilyKeyedSurface",
    "Footprint",
    "FootprintEvidence",
    "FunctionFactory",
    "HardConstraintFilter",
    "Horizon",
    "HostedBot",
    "LegRole",
    "LogicIdentity",
    "MappingReadSurface",
    "ParameterSpec",
    "ParameterType",
    "PresenceState",
    "ProducerBinding",
    "ProducerBindingForm",
    "ProducerKind",
    "ProducerTemplate",
    "ReadSurface",
    "ResolvedProducer",
    "StrategyFamilyId",
    "StrategyFamilyRecord",
    "StreamMember",
    "StreamRole",
    "UiFlag",
    "__version__",
    "accept_intents",
    "bot_definition_kind_contract",
    "branches_from_edge",
    "confluence_kind_contract",
    "construct_bot",
    "continues_performance_edge",
    "derive_horizon",
    "evaluate_ticket",
    "fingerprint_source_manifest",
    "install_bot_definition_kind",
    "install_confluence_kind",
    "mint_bot_definition",
    "mint_confluence",
    "mint_footprint",
    "mint_logic_identity",
    "mint_producer_template",
    "mint_strategy_family",
    "normalize_source_manifest",
    "parse_binding_form",
    "parse_leg_role",
    "parse_ordering",
    "parse_parameter_type",
    "parse_ui_flag",
    "permitted_exit_kinds",
    "promote_tuned_assignment",
    "protocol_contract_identity",
    "register_bot_definition",
    "register_confluence",
    "report_completeness",
    "resolve_confluence_at_layer1",
    "resolve_family_at_layer1",
    "resolve_logic_at_layer1",
    "resolve_template",
]

# Display-only provenance — never part of fp1 identity (DEC-0180).
__version__ = "0.1.0"
