"""Fill, slippage, cost, and financing ports plus adapters (B-6).

Inbound execution is a CT-23 Book-resolved intent (or a typed refusal). Ports
execute an authorized intent, never a bot-sized order, and never a venue
command (DEC-0164). Fill/slippage/cost ``typing.Protocol`` seams are pinned
here; Epic 17 implements adapters.
"""

from __future__ import annotations

from qmb.execution.ports import (
    CLAIMS_EDGE,
    COMPOSITION_ORDER,
    COMPOSITION_VERSION,
    FILL_DECISIONS,
    FINANCING_IS_ORDER_FILL,
    GAP_0048_OPEN,
    PORT_ROLES,
    SPENDS_SPLIT_BUDGET,
    TAINT_IS_IDENTITY,
    TAINT_OPTIMISTIC,
    AuthorizedIntent,
    CostedFill,
    CostPort,
    ExecutionPorts,
    Fill,
    FillDecision,
    Filled,
    FillKind,
    FillPort,
    FinancingPort,
    NoFill,
    PartialFill,
    SlicePath,
    SlippagePort,
    apply_execution_ports,
    classify_fill_quantity,
    derive_world_from_provenance,
    execute_authorized,
    fingerprint_ports,
    ports_identity,
    record_virtual_close,
    refuse_optimistic_edge_claim,
    refuse_store_synthetic_governed_evidence,
    require_authorized_intent,
)
from qmb.execution.risk import (
    admit_open,
    evaluate_exit,
    mint_replay_exit,
    require_full_loss_before_open,
)

__all__ = [
    "CLAIMS_EDGE",
    "COMPOSITION_ORDER",
    "COMPOSITION_VERSION",
    "FILL_DECISIONS",
    "FINANCING_IS_ORDER_FILL",
    "GAP_0048_OPEN",
    "PORT_ROLES",
    "SPENDS_SPLIT_BUDGET",
    "TAINT_IS_IDENTITY",
    "TAINT_OPTIMISTIC",
    "AuthorizedIntent",
    "CostPort",
    "CostedFill",
    "ExecutionPorts",
    "Fill",
    "FillDecision",
    "FillKind",
    "FillPort",
    "Filled",
    "FinancingPort",
    "NoFill",
    "PartialFill",
    "SlicePath",
    "SlippagePort",
    "admit_open",
    "apply_execution_ports",
    "classify_fill_quantity",
    "derive_world_from_provenance",
    "evaluate_exit",
    "execute_authorized",
    "fingerprint_ports",
    "mint_replay_exit",
    "ports_identity",
    "record_virtual_close",
    "refuse_optimistic_edge_claim",
    "refuse_store_synthetic_governed_evidence",
    "require_authorized_intent",
    "require_full_loss_before_open",
]
