"""Frozen schema catalog for the 71 value_status_required registry rows.

Generated from docs/registry/variables.yaml. Schema only — never resolved
values (DEC-0203, DEC-0254, DEC-0256). Tests assert this catalog matches the
registry file. Liveness heartbeat names are the DEC-0261 forms.
"""

from __future__ import annotations

from typing import Final, TypedDict

__all__ = [
    "BLANK_EFFECT_BOOT",
    "BLANK_EFFECT_LIVE",
    "BLANK_EFFECT_SOAK",
    "COMPONENT_COUNTS",
    "EXPECTED_BLANK_EFFECT_COUNTS",
    "EXPECTED_ROW_COUNT",
    "LIVENESS_HEARTBEAT_NAMES",
    "RETIRED_DEAD_MANS_SWITCH_NAMES",
    "VALUE_STATUS_REQUIRED_ROWS",
    "RegistryRowSchema",
    "rows_by_name",
]


class RegistryRowSchema(TypedDict):
    name: str
    component: str
    owner_scope: str
    units: str | None
    type: str
    blank_effect: tuple[str, ...]
    configurable: bool


BLANK_EFFECT_BOOT: Final[str] = "blocks-boot"
BLANK_EFFECT_LIVE: Final[str] = "blocks-role-live"
BLANK_EFFECT_SOAK: Final[str] = "blocks-soak"

EXPECTED_ROW_COUNT: Final[int] = 71
COMPONENT_COUNTS: Final[dict[str, int]] = {
    "COMP-QMN": 48,
    "COMP-QMF-RISK": 20,
    "COMP-QMF-DATA": 3,
}
EXPECTED_BLANK_EFFECT_COUNTS: Final[dict[str, int]] = {
    BLANK_EFFECT_BOOT: 12,
    BLANK_EFFECT_LIVE: 41,
    BLANK_EFFECT_SOAK: 60,
}

LIVENESS_HEARTBEAT_NAMES: Final[frozenset[str]] = frozenset(
    {
        "liveness_heartbeat_endpoint",
        "liveness_heartbeat_cadence",
        "liveness_heartbeat_token_reference",
    }
)

RETIRED_DEAD_MANS_SWITCH_NAMES: Final[frozenset[str]] = frozenset(
    {
        "dead_mans_switch_endpoint",
        "dead_mans_switch_cadence",
        "dead_mans_switch_token_reference",
    }
)

VALUE_STATUS_REQUIRED_ROWS: Final[tuple[RegistryRowSchema, ...]] = (
    {
        "name": 'backup_recovery_point_objective',
        "component": 'COMP-QMF-DATA',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'backup_retention_period',
        "component": 'COMP-QMF-DATA',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'restore_verification_cadence',
        "component": 'COMP-QMF-DATA',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'news_blackout_before',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node',
        "units": 'minutes',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'news_blackout_after',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node',
        "units": 'minutes',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'bench_consecutive_loss_threshold',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'bot',
        "units": 'consecutive-qualifying-loss-exits',
        "type": 'count',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'qualifying_loss_threshold',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'book',
        "units": 'r-multiple',
        "type": 'ratio',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'kill_line_capital_floor',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'book',
        "units": 'money(numeraire)',
        "type": 'money',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'sqs_hard_block_threshold_per_class',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node-and-book',
        "units": 'score-ratio',
        "type": 'ratio',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'sqs_hysteresis_band',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node-and-book',
        "units": 'score-ratio',
        "type": 'ratio',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'sqs_outlier_guard_multiple',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node-and-book',
        "units": 'dispersion-multiple',
        "type": 'ratio',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'sqs_sample_cadence',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node-and-book',
        "units": None,
        "type": 'enum',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'sqs_baseline_conditioning',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node-and-book',
        "units": None,
        "type": 'enum',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'sqs_baseline_refit_schedule',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node-and-book',
        "units": None,
        "type": 'enum',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'sqs_staleness_horizon',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node-and-book',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'decision_freshness_bound',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'book',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'daily_dead_zone_width',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'session_handover_buffer_width',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'session_handover_buffer_anchor',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'node',
        "units": None,
        "type": 'enum',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'breakeven_ratchet_trigger',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'book',
        "units": None,
        "type": 'ratio',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'breakeven_ratchet_offset',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'book',
        "units": None,
        "type": 'ratio',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'ksa_effect_matrix',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'enum',
        "type": 'declaration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'ksa_detector_posture',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'enum',
        "type": 'enum',
        "blank_effect": ('blocks-role-live',),
        "configurable": True,
    },
    {
        "name": 'news_calendar_max_staleness',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'amend_min_improvement',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'book',
        "units": 'dimensionless-ratio',
        "type": 'ratio',
        "blank_effect": ('blocks-role-live',),
        "configurable": True,
    },
    {
        "name": 'submission_deadline',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'local_queue_bound',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'max_slice_latency',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'accumulator_bound',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'count',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'reconciliation_lookback',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'reconciliation_cadence',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'pacing_cadence',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'backoff_cadence',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'protective_reserve_capacity',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'count',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'pool_constants',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'declaration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'health_constants',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'declaration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'node_crash_loop_max_boots',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'count',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'node_crash_loop_window',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'drain_window',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'slice_watch_trip_multiple',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'dimensionless-ratio',
        "type": 'ratio',
        "blank_effect": ('blocks-boot',),
        "configurable": True,
    },
    {
        "name": 'shadow_lane_publish_bound',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot',),
        "configurable": True,
    },
    {
        "name": 'news_recorder_max_attempts',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'count',
        "blank_effect": ('blocks-boot',),
        "configurable": True,
    },
    {
        "name": 'news_recorder_backoff',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot',),
        "configurable": True,
    },
    {
        "name": 'watchdog_interval',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-boot', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'clock_drift_warn',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'clock_drift_no_new_entry',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'clock_drift_halt',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'clock_unsynchronized_after',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'venue_d1_reverification_cadence',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live',),
        "configurable": True,
    },
    {
        "name": 'backup_recovery_time_objective_integrity',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'backup_recovery_time_objective_full_dr',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'backup_object_storage_provider',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'string',
        "type": 'string',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'backup_payload_key_custody',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'string',
        "type": 'string',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'hot_room_retention_window',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'disk_headroom_min',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'bytes',
        "type": 'quantity',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'vps_disk_budget',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'bytes',
        "type": 'declaration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'news_calendar_provider_primary',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'enum',
        "type": 'enum',
        "blank_effect": ('blocks-role-live',),
        "configurable": True,
    },
    {
        "name": 'news_calendar_refresh_cadence',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'operator_log_retention_window',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'journald_size_cap',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'bytes',
        "type": 'quantity',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'liveness_heartbeat_endpoint',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'string',
        "type": 'string',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'liveness_heartbeat_cadence',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'liveness_heartbeat_token_reference',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-ops',
        "units": 'string',
        "type": 'string',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'evidence_channel_budget',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'count',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'governor_cpu_budget',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'count',
        "type": 'count',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'governor_memory_budget',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'bytes',
        "type": 'quantity',
        "blank_effect": ('blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'seat_callback_deadline',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'duration',
        "type": 'duration',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'seat_memory_ceiling',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'bytes',
        "type": 'quantity',
        "blank_effect": ('blocks-role-live', 'blocks-soak',),
        "configurable": True,
    },
    {
        "name": 'bot_state_snapshot_cadence',
        "component": 'COMP-QMN',
        "owner_scope": 'node',
        "units": 'enum',
        "type": 'enum',
        "blank_effect": ('blocks-role-live',),
        "configurable": True,
    },
    {
        "name": 'r_unit_price_recompute_cadence',
        "component": 'COMP-QMF-RISK',
        "owner_scope": 'book',
        "units": 'enum',
        "type": 'enum',
        "blank_effect": ('blocks-role-live',),
        "configurable": True,
    },
    {
        "name": 'accounting_period_calendar_identity',
        "component": 'COMP-QMN',
        "owner_scope": 'node-and-bms',
        "units": 'string',
        "type": 'string',
        "blank_effect": ('blocks-role-live',),
        "configurable": True,
    },
)


def rows_by_name() -> dict[str, RegistryRowSchema]:
    """Index the catalog by variable name."""
    return {row["name"]: row for row in VALUE_STATUS_REQUIRED_ROWS}

