"""Event-slice run loop, frontier clock port, and in-loop warm-up (B-2).

Time advances only through an injected frontier clock that IS qmf-core's AD-8
``Clock`` protocol. The loop is never forked: backtest, replay, and live differ
only by which clock and adapters the run-config binds (DEC-0169). Per slice the
six sub-phases in :data:`SUBPHASES` run in pinned identity-bearing order.
"""

from __future__ import annotations

from qmb.runloop.bars import (
    BARSPEC_KINDS,
    COMPLETED_BOUNDARY_ONLY,
    COMPLETENESS_COMPLETED,
    COMPLETENESS_FORMING,
    FORMING_BAR_ACTIONABLE,
    FORMING_BAR_VISIBLE,
    LOOKAHEAD_PREVENTION_INDEPENDENT_OF_GAP_0048,
    DeclaredBarSpec,
    DerivedBar,
    FormingBarState,
    ReadableBarSet,
    SameSliceConsumption,
    SeriesSample,
    StreamBarPlan,
    UnderlyingSeries,
    act_on_bar,
    consume_same_slice,
    consume_stream_plans,
    finest_base,
    readable_bars,
    require_same_series,
)
from qmb.runloop.frontier import (
    CLOCK_DOES_NOT_CHOOSE_WORLD,
    FrontierClock,
    NextEmitStream,
    StreamNextEmit,
    advance_frontier,
    as_wall_replay_instant,
    min_next_emit,
    read_frontier,
    script_replay_clock,
)
from qmb.runloop.loop import (
    LOOP_KIND,
    SAME_SLICE_NEW_INTENT_FILL,
    STREAM_ROLE_DATA_ONLY,
    STREAM_ROLE_TRADING,
    STREAM_SET_KEY,
    SUBPHASES,
    DeclaredStream,
    EventSlice,
    LoopOutcome,
    RestingIntent,
    SilentSliceHandler,
    SliceHandler,
    SliceObservation,
    SliceOutcome,
    StreamSet,
    SubphaseTrace,
    fingerprint_loop,
    frontier_clock_name,
    loop_identity,
    run,
    run_slice,
    stream_set_from_config,
)
from qmb.runloop.warmup import (
    EMBARGO_KEY,
    PRESEED_IS_WARMUP,
    WARMUP_ADDS_SECOND_WINDOW,
    WARMUP_MECHANISM,
    WARMUP_UNIT,
    SplitEmbargo,
    WarmupProgress,
    embargo_from_config,
    guard_trading,
    preseed_indicator_buffers,
    refuse_act_during_warmup,
    trading_evidence_range,
)

__all__ = [
    "BARSPEC_KINDS",
    "CLOCK_DOES_NOT_CHOOSE_WORLD",
    "COMPLETED_BOUNDARY_ONLY",
    "COMPLETENESS_COMPLETED",
    "COMPLETENESS_FORMING",
    "EMBARGO_KEY",
    "FORMING_BAR_ACTIONABLE",
    "FORMING_BAR_VISIBLE",
    "LOOKAHEAD_PREVENTION_INDEPENDENT_OF_GAP_0048",
    "LOOP_KIND",
    "PRESEED_IS_WARMUP",
    "SAME_SLICE_NEW_INTENT_FILL",
    "STREAM_ROLE_DATA_ONLY",
    "STREAM_ROLE_TRADING",
    "STREAM_SET_KEY",
    "SUBPHASES",
    "WARMUP_ADDS_SECOND_WINDOW",
    "WARMUP_MECHANISM",
    "WARMUP_UNIT",
    "DeclaredBarSpec",
    "DeclaredStream",
    "DerivedBar",
    "EventSlice",
    "FormingBarState",
    "FrontierClock",
    "LoopOutcome",
    "NextEmitStream",
    "ReadableBarSet",
    "RestingIntent",
    "SameSliceConsumption",
    "SeriesSample",
    "SilentSliceHandler",
    "SliceHandler",
    "SliceObservation",
    "SliceOutcome",
    "SplitEmbargo",
    "StreamBarPlan",
    "StreamNextEmit",
    "StreamSet",
    "SubphaseTrace",
    "UnderlyingSeries",
    "WarmupProgress",
    "act_on_bar",
    "advance_frontier",
    "as_wall_replay_instant",
    "consume_same_slice",
    "consume_stream_plans",
    "embargo_from_config",
    "finest_base",
    "fingerprint_loop",
    "frontier_clock_name",
    "guard_trading",
    "loop_identity",
    "min_next_emit",
    "preseed_indicator_buffers",
    "read_frontier",
    "readable_bars",
    "refuse_act_during_warmup",
    "require_same_series",
    "run",
    "run_slice",
    "script_replay_clock",
    "stream_set_from_config",
    "trading_evidence_range",
]
