"""Public operation descriptors and door matrix (Workflows AD-3 / AD-21).

Definitions only: complete versioned descriptors, closed vocabularies, and
``op_id``+version door admission. QMB remains the only operator CLI.
"""

from __future__ import annotations

from qma.core.operations.catalog import (
    PUBLIC_OPERATION_PAYLOADS,
    load_public_operation_descriptors,
    public_door_matrix,
    public_operation_descriptors,
)
from qma.core.operations.descriptor import (
    APPLICATION_LAYER_OP_OWNERS,
    BROKER_VENUE_OP_OWNER,
    ERROR_REFUSAL_FAMILY,
    FORBIDDEN_DESCRIPTOR_FIELDS,
    OPERATION_DESCRIPTOR_CONTRACT,
    OPERATION_DESCRIPTOR_FIELDS,
    OPERATION_DESCRIPTOR_INSPECT_SHAS,
    OPERATION_DESCRIPTOR_NEW_CT_MINTED,
    OPERATION_DESCRIPTOR_OWNER,
    OPERATION_DESCRIPTOR_WIRED_AT_INSPECT_SHA,
    OPERATOR_CLI_ADAPTER,
    QMA_IS_HOST_RUNTIME,
    QMF_IS_APPLICATION_LAYER_OP_OWNER,
    REQUIRED_REFUSAL_CODES,
    ErrorRefusalShape,
    OperationConfiguration,
    OperationDescriptor,
    ResourceNeeds,
    SupportedDoor,
    parse_operation_descriptor,
    publish_operation_descriptor,
)
from qma.core.operations.doors import (
    FORBIDDEN_OPERATOR_CLI_ADAPTERS,
    OPERATOR_CLI_ADAPTERS,
    QMA_OPERATOR_CLI,
    QMN_OPERATOR_CLI,
    admit_operation_door,
    descriptor_for,
    door_matrix,
    doors_for,
    is_operator_cli_adapter,
    owner_door_summary,
)
from qma.core.operations.effects import (
    CAS_CONFLICT_IS_RETRY,
    EFFECT_RETRY_BY_CLASS,
    HOST_RETRY_EFFECT_CLASSES,
    HOST_RETRY_POLICY_OVERRIDE,
    OUTBOX_REPLAY_IS_SECOND_DISPATCH,
    PER_PACK_RETRY_ENUM_MINTED,
    RECONCILE_POLICIES,
    UNKNOWN_BLOCKED_AUTO_RETRY,
    UNKNOWN_BLOCKED_FIELD,
    EffectOutcome,
    apply_effect_outcome,
    cas_config_revision,
    effect_retry_kind,
    host_may_dispatch,
    host_may_send_again,
    host_retry_applies,
    is_cas_conflict,
    is_unknown_blocked,
    may_retry_effect,
    parse_reconcile_policy,
    parse_retryability,
    place_run_identity,
    reconcile_external_egress,
    reconcile_policy_wins_over_host_retry,
)

__all__ = [
    "APPLICATION_LAYER_OP_OWNERS",
    "BROKER_VENUE_OP_OWNER",
    "CAS_CONFLICT_IS_RETRY",
    "EFFECT_RETRY_BY_CLASS",
    "ERROR_REFUSAL_FAMILY",
    "FORBIDDEN_DESCRIPTOR_FIELDS",
    "FORBIDDEN_OPERATOR_CLI_ADAPTERS",
    "HOST_RETRY_EFFECT_CLASSES",
    "HOST_RETRY_POLICY_OVERRIDE",
    "OPERATION_DESCRIPTOR_CONTRACT",
    "OPERATION_DESCRIPTOR_FIELDS",
    "OPERATION_DESCRIPTOR_INSPECT_SHAS",
    "OPERATION_DESCRIPTOR_NEW_CT_MINTED",
    "OPERATION_DESCRIPTOR_OWNER",
    "OPERATION_DESCRIPTOR_WIRED_AT_INSPECT_SHA",
    "OPERATOR_CLI_ADAPTER",
    "OPERATOR_CLI_ADAPTERS",
    "OUTBOX_REPLAY_IS_SECOND_DISPATCH",
    "PER_PACK_RETRY_ENUM_MINTED",
    "PUBLIC_OPERATION_PAYLOADS",
    "QMA_IS_HOST_RUNTIME",
    "QMA_OPERATOR_CLI",
    "QMF_IS_APPLICATION_LAYER_OP_OWNER",
    "QMN_OPERATOR_CLI",
    "RECONCILE_POLICIES",
    "REQUIRED_REFUSAL_CODES",
    "UNKNOWN_BLOCKED_AUTO_RETRY",
    "UNKNOWN_BLOCKED_FIELD",
    "EffectOutcome",
    "ErrorRefusalShape",
    "OperationConfiguration",
    "OperationDescriptor",
    "ResourceNeeds",
    "SupportedDoor",
    "admit_operation_door",
    "apply_effect_outcome",
    "cas_config_revision",
    "descriptor_for",
    "door_matrix",
    "doors_for",
    "effect_retry_kind",
    "host_may_dispatch",
    "host_may_send_again",
    "host_retry_applies",
    "is_cas_conflict",
    "is_operator_cli_adapter",
    "is_unknown_blocked",
    "load_public_operation_descriptors",
    "may_retry_effect",
    "owner_door_summary",
    "parse_operation_descriptor",
    "parse_reconcile_policy",
    "parse_retryability",
    "place_run_identity",
    "public_door_matrix",
    "public_operation_descriptors",
    "publish_operation_descriptor",
    "reconcile_external_egress",
    "reconcile_policy_wins_over_host_retry",
]
