"""``qmn.venue`` — the one sanctioned ``qmf-venue`` import and wirer boundary.

Every other ``qmn`` module receives :class:`VenueClientPort` and the CT-19/CT-20
shapes re-exported here; only this subpackage may import ``qmf.venue`` (DEC-0241,
DEC-0228). Story 24.1 lands the port, the FEAT-0023 conformance double, the
FTR-04 parent-disposition record, and the credential-free conformance suite.
Story 24.2 adds CT-18 verify-or-refuse at connection time (D008). Story 24.3
adds the live cTrader client: record-before-interpret, exact scale decode, and
FTR-01-blocked position/balance read-backs. Story 24.6 re-exports the UNKNOWN
stream-gate shapes so ``qmn.order`` can enforce the exact ``(VenueId, account)``
boundary without importing ``qmf.venue`` (QMX-F062). Story 24.8 adds reconnect
gap-recovery, the TN-21 replay adapter, and the shared three-implementation
port-contract suite. Story 24.9 re-exports subject-terminal resolution and
records TN-24i requote / deep-history edge dispositions. Story 28.3 adds named
money-path fault injection on the conformance double.
"""

from __future__ import annotations

# Re-export CT-19/CT-20 shapes so non-venue qmn modules never import qmf.venue.
from qmf.venue.blocking import (
    RISK_REDUCING_KINDS,
    AdmissionDisposition,
    AdmissionResult,
    ResolveObservation,
    ResolveResolution,
    StandingIntentDecision,
    StandingIntentDisposition,
    StandingIntentJournalEvent,
    StandingProtectionIntent,
    StreamBlockCause,
    UnknownBlock,
    UnknownGate,
    is_risk_reducing,
)
from qmf.venue.commands import (
    BindingOutcome,
    Command,
    CommandIdBinding,
    CommandIdBindingRegistry,
    CommandKind,
    CommandObservation,
    CompoundCommand,
    JournalEvent,
    OrderParameters,
    OrderType,
    ProtectionAmendment,
    ProtectionSide,
    SubmissionOutcome,
    SubmissionResult,
    TimeInForce,
    UnknownTrigger,
)
from qmf.venue.connection import (
    ASYNC_CONFORMANCE_EXEMPTION,
    CTRADER_OPEN_API_PORT,
    ConnectionManager,
    venue_command_stream,
    venue_writer_id,
)
from qmf.venue.events import (
    InboundVenueEvent,
    ObservationKind,
    Reconciliation,
    ReconciliationReadback,
    ReconciliationVerdict,
    SubjectResolution,
    SubjectTerminalOutcome,
    VenueNativeIdentity,
    resolve_subject_terminal,
)
from qmf.venue.observation import REQUIRED_CONNECTION_CHECKS

from qmn.venue.conformance import (
    CONFORMANCE_CASES,
    INJECTED_COMMAND_FAULTS,
    PORT_CONTRACT_CAPABILITY_KEYS,
    SHARED_FAULT_CONTRACT,
    ConformanceCase,
    ConformanceDouble,
    InjectedFault,
    PositionModel,
    agree_live_and_double_fault_contract,
    compare_port_contract_shapes,
    compound_command_acceptance_blocked,
    run_conformance_suite,
    run_port_contract_suite,
)
from qmn.venue.disposition import (
    ASYNC_EXEMPTION_MODULE,
    FTR04_DISPOSITION,
    TRANSPORT_LOCUS,
    ParentAsyncExemptionDisposition,
    resolve_transport_locus,
)
from qmn.venue.edge import (
    COMPANION_SOURCE_IMPLEMENTATION_FORBIDDEN,
    DEEP_HISTORY_NODE_SOURCE,
    REQUOTE_OUTCOME_TYPE_FORBIDDEN,
    DeepHistorySourceRole,
    RequoteMapping,
    companion_source_implementation_allowed,
    deep_history_source_inventory,
    map_requote,
    requote_error_map_row,
)
from qmn.venue.live import (
    CT13_SEVEN_EVENT_TYPES,
    FTR01_BLOCKED_KINDS,
    VOLUME_WIRE_SCALE_EXPONENT,
    JournalMapping,
    LiveCTraderClient,
    WireKind,
    ct13_journal_event_type,
    decode_volume,
    ftr01_position_balance_blocked,
)
from qmn.venue.port import (
    VenueClientKind,
    VenueClientPort,
    VenueClientSelection,
    select_venue_client,
)
from qmn.venue.reconnect import (
    ReceiveFrontier,
    ReconnectGapRecovery,
    ReconnectPhase,
    ReconnectReport,
    RecoveredObservation,
)
from qmn.venue.replay import (
    REPLAY_SUBMIT_REFUSAL_CATEGORY,
    ReplayAdapter,
    replay_command_attempt_refused,
)
from qmn.venue.verify import (
    DATA_QUALITY_EVENT_TYPE,
    BindingRevalidationState,
    DataQualityJournalEvent,
    FieldDefectKind,
    MeasuredFactBundle,
    VenueFactVerification,
    VenueFactVerifier,
    conformance_measured_facts,
    ctrader_static_declaration,
)

__all__ = [
    "ASYNC_CONFORMANCE_EXEMPTION",
    "ASYNC_EXEMPTION_MODULE",
    "COMPANION_SOURCE_IMPLEMENTATION_FORBIDDEN",
    "CONFORMANCE_CASES",
    "CT13_SEVEN_EVENT_TYPES",
    "CTRADER_OPEN_API_PORT",
    "DATA_QUALITY_EVENT_TYPE",
    "DEEP_HISTORY_NODE_SOURCE",
    "FTR01_BLOCKED_KINDS",
    "FTR04_DISPOSITION",
    "INJECTED_COMMAND_FAULTS",
    "PORT_CONTRACT_CAPABILITY_KEYS",
    "REPLAY_SUBMIT_REFUSAL_CATEGORY",
    "REQUIRED_CONNECTION_CHECKS",
    "REQUOTE_OUTCOME_TYPE_FORBIDDEN",
    "RISK_REDUCING_KINDS",
    "SHARED_FAULT_CONTRACT",
    "TRANSPORT_LOCUS",
    "VOLUME_WIRE_SCALE_EXPONENT",
    "AdmissionDisposition",
    "AdmissionResult",
    "BindingOutcome",
    "BindingRevalidationState",
    "Command",
    "CommandIdBinding",
    "CommandIdBindingRegistry",
    "CommandKind",
    "CommandObservation",
    "CompoundCommand",
    "ConformanceCase",
    "ConformanceDouble",
    "ConnectionManager",
    "DataQualityJournalEvent",
    "DeepHistorySourceRole",
    "FieldDefectKind",
    "InboundVenueEvent",
    "InjectedFault",
    "JournalEvent",
    "JournalMapping",
    "LiveCTraderClient",
    "MeasuredFactBundle",
    "ObservationKind",
    "OrderParameters",
    "OrderType",
    "ParentAsyncExemptionDisposition",
    "PositionModel",
    "ProtectionAmendment",
    "ProtectionSide",
    "ReceiveFrontier",
    "Reconciliation",
    "ReconciliationReadback",
    "ReconciliationVerdict",
    "ReconnectGapRecovery",
    "ReconnectPhase",
    "ReconnectReport",
    "RecoveredObservation",
    "ReplayAdapter",
    "RequoteMapping",
    "ResolveObservation",
    "ResolveResolution",
    "StandingIntentDecision",
    "StandingIntentDisposition",
    "StandingIntentJournalEvent",
    "StandingProtectionIntent",
    "StreamBlockCause",
    "SubjectResolution",
    "SubjectTerminalOutcome",
    "SubmissionOutcome",
    "SubmissionResult",
    "TimeInForce",
    "UnknownBlock",
    "UnknownGate",
    "UnknownTrigger",
    "VenueClientKind",
    "VenueClientPort",
    "VenueClientSelection",
    "VenueFactVerification",
    "VenueFactVerifier",
    "VenueNativeIdentity",
    "WireKind",
    "agree_live_and_double_fault_contract",
    "companion_source_implementation_allowed",
    "compare_port_contract_shapes",
    "compound_command_acceptance_blocked",
    "conformance_measured_facts",
    "ct13_journal_event_type",
    "ctrader_static_declaration",
    "decode_volume",
    "deep_history_source_inventory",
    "ftr01_position_balance_blocked",
    "is_risk_reducing",
    "map_requote",
    "replay_command_attempt_refused",
    "requote_error_map_row",
    "resolve_subject_terminal",
    "resolve_transport_locus",
    "run_conformance_suite",
    "run_port_contract_suite",
    "select_venue_client",
    "venue_command_stream",
    "venue_writer_id",
]
