"""Parameter schema, pure sampler port, and sensitivity-analysis home (B-8).

The default sampler adapter is TPE-class, pinned by ``registry:qmb_sampler_pin``.
Adapters run ``n_jobs=1``: process fan-out belongs to the orchestrator, never
the sampler (DEC-0168, DEC-0161). The pin value lives in the registry and
the distribution manifest, never restated here.

The typed parameter-space schema is ONE schema, authoritative in the CT-33
Bot definition — B-8 reads it; QMB never keeps a second local copy
(DEC-0173, DEC-0183).
"""

from __future__ import annotations

from qmf.core.refusal import Ok, Result, is_refusal
from qml.declaration.bot import BotDefinition
from qml.declaration.parameters import ParameterSpec

from qmb.optimize.objective import (
    DIRECTION_MAX,
    DIRECTION_MIN,
    INCOMPLETE_TRIAL_CONSTRAINT_MISSING,
    INCOMPLETE_TRIAL_CONSTRAINT_UNDEFINED,
    INCOMPLETE_TRIAL_OBJECTIVE_MISSING,
    INCOMPLETE_TRIAL_OBJECTIVE_UNDEFINED,
    INCOMPLETE_TRIAL_REASONS,
    INCOMPLETE_TRIAL_REFUSED,
    MIN_TRADES_FLOOR_KEY,
    MIN_TRADES_GATE_DEFAULT_ON,
    MIN_TRADES_HAS_SPINE_CONSTANT,
    MIN_TRADES_MEASURE,
    MIN_TRADES_OPERATOR,
    OBJECTIVE_DIRECTIONS,
    STUDY_CONSTRAINT_CLASS,
    STUDY_CONSTRAINT_OPERATORS,
    STUDY_CRITERIA_CLASS,
    STUDY_CRITERIA_FORMAT_VERSION,
    STUDY_CRITERIA_KEY,
    STUDY_OBJECTIVE_CLASS,
    WINNER_MAKES_BAR_VERDICT,
    WINNER_MAKES_EDGE_CLAIM,
    WINNER_ROLE,
    WINNER_SET_CLASS,
    WINNER_SET_FORMAT_VERSION,
    WINNER_VERDICT_DEFERRED_TO,
    IncompleteTrial,
    MinTradesGate,
    ScoredTrial,
    StudyConstraint,
    StudyCriteria,
    StudyObjective,
    StudyWinnerSet,
    coerce_study_criteria,
    compute_winner_set,
    study_criteria_identity,
)
from qmb.optimize.resume import (
    COST_ESTIMATE_CLASS,
    COST_ESTIMATE_FORMAT_VERSION,
    ESTIMATE_SPAWNS_TRIAL,
    ESTIMATE_STATUS_MEASURED,
    ESTIMATE_STATUS_NOT_YET_MEASURED,
    ESTIMATE_STATUS_OPEN_ENDED,
    RESUME_CONSULTS_OPTUNA_STORE,
    RESUME_SOURCE,
    STUDY_RESUME_PLAN_CLASS,
    STUDY_RESUME_PLAN_FORMAT_VERSION,
    TRIAL_BUDGET_CLASS,
    TRIAL_BUDGET_FIXED,
    TRIAL_BUDGET_KINDS,
    TRIAL_BUDGET_RUN_UNTIL,
    TRIAL_BUDGET_SCALE_WITH_PARAMS,
    CostEstimate,
    StudyResumePlan,
    TrialBudget,
    cost_estimate_identity,
    estimate_study_cost,
    plan_study_resume,
    resume_stepper,
    study_resume_identity,
)
from qmb.optimize.sampler import (
    DEFAULT_RATIONAL_SCALE,
    DEFAULT_ROUNDING,
    GENERATION_SEED_CLASS,
    PARAMETER_BATCH_CLASS,
    PARAMETER_BATCH_FORMAT_VERSION,
    PRIOR_TRIAL_CLASS,
    PROPOSED_TRIAL_CLASS,
    SAMPLED_VALUE_CLASS,
    SAMPLER_CONSULTS_OPTUNA_STORE,
    SAMPLER_FAMILY,
    SAMPLER_GENERATOR,
    SAMPLER_JOBS,
    SAMPLER_LIBRARY,
    SAMPLER_PARALLEL_ASK,
    SAMPLER_PIN_KEY,
    SAMPLER_STEPPING,
    SAMPLER_TRIAL_ROLE,
    STUDY_ARTIFACT_CLASS,
    STUDY_ARTIFACT_FORMAT_VERSION,
    STUDY_LABEL_CLASS,
    TRIAL_LABEL_CLASS,
    TRIAL_LABEL_FORMAT_VERSION,
    AdmittedStudy,
    ConvertedValue,
    ParameterBatch,
    PriorTrial,
    ProposedTrial,
    StudyArtifact,
    StudyLabel,
    StudyStepper,
    admit_study,
    coerce_prior_trials,
    convert_sampled_value,
    generator_provenance,
    propose_generation,
    refuse_parallel_ask,
    refuse_sampler_contract_bump,
    sampler_identity,
    trial_label,
)
from qmb.optimize.space import (
    STUDY_SPACE_CLASS,
    STUDY_SPACE_FORMAT_VERSION,
    STUDY_SPACE_KEY,
    StudyParameterSpace,
    coerce_study_space,
    study_space_from_bot,
    study_space_identity,
)
from qmb.optimize.splits import (
    ALIASES_ARE_DISPLAY_ONLY,
    DEFAULT_ACCESS_ROLES,
    OBJECTIVE_SPLIT_ALIAS,
    SEALED_HOLDOUT_ROLE,
    SPLIT_ALIASES,
    SPLIT_RUN_CLAIMS_EDGE,
    SPLIT_RUN_SPENDS_BUDGET,
    SPLIT_RUN_TAINT,
    STUDIES_RUN_REPLAY_ONLY,
    STUDY_SPLITS_CLASS,
    STUDY_SPLITS_FORMAT_VERSION,
    STUDY_SPLITS_KEY,
    TEST_ALIAS,
    TRAIN_ALIAS,
    TRIAL_SPLIT_PLAN_CLASS,
    TRIAL_SPLIT_RUN_CLASS,
    SplitEmbargo,
    StudySplits,
    TrialSplitPlan,
    TrialSplitRun,
    admit_default_split_access,
    admit_objective_run,
    admit_study_world,
    coerce_study_splits,
    plan_trial_runs,
    refuse_split_edge_or_budget,
    serve_split_read,
    study_splits_identity,
    study_warmup,
    study_warmup_from_config,
    trading_evidence_range,
)

__all__ = [
    "ALIASES_ARE_DISPLAY_ONLY",
    "COST_ESTIMATE_CLASS",
    "COST_ESTIMATE_FORMAT_VERSION",
    "DEFAULT_ACCESS_ROLES",
    "DEFAULT_RATIONAL_SCALE",
    "DEFAULT_ROUNDING",
    "DIRECTION_MAX",
    "DIRECTION_MIN",
    "ESTIMATE_SPAWNS_TRIAL",
    "ESTIMATE_STATUS_MEASURED",
    "ESTIMATE_STATUS_NOT_YET_MEASURED",
    "ESTIMATE_STATUS_OPEN_ENDED",
    "GENERATION_SEED_CLASS",
    "INCOMPLETE_TRIAL_CONSTRAINT_MISSING",
    "INCOMPLETE_TRIAL_CONSTRAINT_UNDEFINED",
    "INCOMPLETE_TRIAL_OBJECTIVE_MISSING",
    "INCOMPLETE_TRIAL_OBJECTIVE_UNDEFINED",
    "INCOMPLETE_TRIAL_REASONS",
    "INCOMPLETE_TRIAL_REFUSED",
    "MIN_TRADES_FLOOR_KEY",
    "MIN_TRADES_GATE_DEFAULT_ON",
    "MIN_TRADES_HAS_SPINE_CONSTANT",
    "MIN_TRADES_MEASURE",
    "MIN_TRADES_OPERATOR",
    "OBJECTIVE_DIRECTIONS",
    "OBJECTIVE_SPLIT_ALIAS",
    "PARAMETER_BATCH_CLASS",
    "PARAMETER_BATCH_FORMAT_VERSION",
    "PRIOR_TRIAL_CLASS",
    "PROPOSED_TRIAL_CLASS",
    "RESUME_CONSULTS_OPTUNA_STORE",
    "RESUME_SOURCE",
    "SAMPLED_VALUE_CLASS",
    "SAMPLER_CONSULTS_OPTUNA_STORE",
    "SAMPLER_FAMILY",
    "SAMPLER_GENERATOR",
    "SAMPLER_JOBS",
    "SAMPLER_LIBRARY",
    "SAMPLER_PARALLEL_ASK",
    "SAMPLER_PIN_KEY",
    "SAMPLER_STEPPING",
    "SAMPLER_TRIAL_ROLE",
    "SEALED_HOLDOUT_ROLE",
    "SPLIT_ALIASES",
    "SPLIT_RUN_CLAIMS_EDGE",
    "SPLIT_RUN_SPENDS_BUDGET",
    "SPLIT_RUN_TAINT",
    "STUDIES_RUN_REPLAY_ONLY",
    "STUDY_ARTIFACT_CLASS",
    "STUDY_ARTIFACT_FORMAT_VERSION",
    "STUDY_CONSTRAINT_CLASS",
    "STUDY_CONSTRAINT_OPERATORS",
    "STUDY_CRITERIA_CLASS",
    "STUDY_CRITERIA_FORMAT_VERSION",
    "STUDY_CRITERIA_KEY",
    "STUDY_LABEL_CLASS",
    "STUDY_OBJECTIVE_CLASS",
    "STUDY_RESUME_PLAN_CLASS",
    "STUDY_RESUME_PLAN_FORMAT_VERSION",
    "STUDY_SPACE_CLASS",
    "STUDY_SPACE_FORMAT_VERSION",
    "STUDY_SPACE_KEY",
    "STUDY_SPLITS_CLASS",
    "STUDY_SPLITS_FORMAT_VERSION",
    "STUDY_SPLITS_KEY",
    "TEST_ALIAS",
    "TRAIN_ALIAS",
    "TRIAL_BUDGET_CLASS",
    "TRIAL_BUDGET_FIXED",
    "TRIAL_BUDGET_KINDS",
    "TRIAL_BUDGET_RUN_UNTIL",
    "TRIAL_BUDGET_SCALE_WITH_PARAMS",
    "TRIAL_LABEL_CLASS",
    "TRIAL_LABEL_FORMAT_VERSION",
    "TRIAL_SPLIT_PLAN_CLASS",
    "TRIAL_SPLIT_RUN_CLASS",
    "WINNER_MAKES_BAR_VERDICT",
    "WINNER_MAKES_EDGE_CLAIM",
    "WINNER_ROLE",
    "WINNER_SET_CLASS",
    "WINNER_SET_FORMAT_VERSION",
    "WINNER_VERDICT_DEFERRED_TO",
    "AdmittedStudy",
    "ConvertedValue",
    "CostEstimate",
    "IncompleteTrial",
    "MinTradesGate",
    "ParameterBatch",
    "PriorTrial",
    "ProposedTrial",
    "ScoredTrial",
    "SplitEmbargo",
    "StudyArtifact",
    "StudyConstraint",
    "StudyCriteria",
    "StudyLabel",
    "StudyObjective",
    "StudyParameterSpace",
    "StudyResumePlan",
    "StudySplits",
    "StudyStepper",
    "StudyWinnerSet",
    "TrialBudget",
    "TrialSplitPlan",
    "TrialSplitRun",
    "admit_default_split_access",
    "admit_objective_run",
    "admit_study",
    "admit_study_world",
    "coerce_prior_trials",
    "coerce_study_criteria",
    "coerce_study_space",
    "coerce_study_splits",
    "compute_winner_set",
    "convert_sampled_value",
    "cost_estimate_identity",
    "estimate_study_cost",
    "generator_provenance",
    "parameter_space_from_bot",
    "plan_study_resume",
    "plan_trial_runs",
    "propose_generation",
    "refuse_parallel_ask",
    "refuse_sampler_contract_bump",
    "refuse_split_edge_or_budget",
    "resume_stepper",
    "sampler_identity",
    "serve_split_read",
    "study_criteria_identity",
    "study_resume_identity",
    "study_space_from_bot",
    "study_space_identity",
    "study_splits_identity",
    "study_warmup",
    "study_warmup_from_config",
    "trading_evidence_range",
    "trial_label",
]


def parameter_space_from_bot(declaration: object) -> Result[tuple[ParameterSpec, ...]]:
    """Read the CT-33-authoritative parameter-space schema (B-8, DEC-0183).

    Mandatory defaults are the Bot definition's canonical assignment. A swept
    non-default assignment is a B-3 run-spec override, never a silent new default.
    """
    if isinstance(declaration, BotDefinition):
        bot = declaration
    else:
        parsed = BotDefinition.try_from_mapping(declaration)
        if is_refusal(parsed):
            return parsed
        bot = parsed.value
    return Ok(tuple(bot.parameter_space))
