"""Run-config schema, layering, and compiler home (B-3).

Every run consumes exactly one fully-resolved, read-only, schema-validated
run-config. Layering is deterministic and pure: same inputs yield a
byte-identical resolved artifact. The artifact's fingerprint is the run-id
root and the ledger key, computed only by qmf-core ``fp1`` (DEC-0160).
"""

from __future__ import annotations

from qmb.config.compiler import (
    CITE_FIELDS,
    CLOCK_REPLAY,
    CLOCK_SIMULATED,
    DISPLAY_FIELDS,
    IDENTITY_FIELDS,
    LAYER_PRECEDENCE,
    OPTIONAL_IDENTITY_FIELDS,
    PROVENANCE_PROCEDURE_EPHEMERAL,
    PROVENANCE_RECORDED,
    PROVENANCE_SYNTHETIC_TAINTED,
    RUN_CONFIG_ARTIFACT_NAME,
    RUN_CONFIG_CLASS,
    RUN_CONFIG_FORMAT_VERSION,
    RUN_CONFIG_FORMAT_VERSION_1,
    RUN_CONFIG_KNOWN_FORMAT_VERSIONS,
    SANCTIONED_OVERLAP_KEYS,
    ResolvedRunConfig,
    artifact_relative_path,
    compile_run_config,
    fingerprint_layers,
    layers_identity,
    ledger_key,
    merge_book_bms_keys,
    run_config_identity,
    run_id_root,
)
from qmb.config.fragments import (
    BMS_NAMESPACES,
    BMS_RECORD_KIND,
    BOOK_NAMESPACES,
    BOOK_RECORD_KIND,
    CONFIG_FRAGMENT_CLASS,
    FRAGMENT_FORMAT_VERSION,
    FRAGMENT_FORMAT_VERSION_1,
    FRAGMENT_KNOWN_FORMAT_VERSIONS,
    FRAGMENT_LINEAGE_EDGE_TYPE,
    SOURCE_BMS,
    SOURCE_BOOK,
    SOURCE_PRESET,
    ConfigFragment,
    fragment_identity,
    materialize_bms_fragment,
    materialize_book_fragment,
    materialize_condition_preset,
)

__all__ = [
    "BMS_NAMESPACES",
    "BMS_RECORD_KIND",
    "BOOK_NAMESPACES",
    "BOOK_RECORD_KIND",
    "CITE_FIELDS",
    "CLOCK_REPLAY",
    "CLOCK_SIMULATED",
    "CONFIG_FRAGMENT_CLASS",
    "DISPLAY_FIELDS",
    "FRAGMENT_FORMAT_VERSION",
    "FRAGMENT_FORMAT_VERSION_1",
    "FRAGMENT_KNOWN_FORMAT_VERSIONS",
    "FRAGMENT_LINEAGE_EDGE_TYPE",
    "IDENTITY_FIELDS",
    "LAYER_PRECEDENCE",
    "OPTIONAL_IDENTITY_FIELDS",
    "PROVENANCE_PROCEDURE_EPHEMERAL",
    "PROVENANCE_RECORDED",
    "PROVENANCE_SYNTHETIC_TAINTED",
    "RUN_CONFIG_ARTIFACT_NAME",
    "RUN_CONFIG_CLASS",
    "RUN_CONFIG_FORMAT_VERSION",
    "RUN_CONFIG_FORMAT_VERSION_1",
    "RUN_CONFIG_KNOWN_FORMAT_VERSIONS",
    "SANCTIONED_OVERLAP_KEYS",
    "SOURCE_BMS",
    "SOURCE_BOOK",
    "SOURCE_PRESET",
    "ConfigFragment",
    "ResolvedRunConfig",
    "artifact_relative_path",
    "compile_run_config",
    "fingerprint_layers",
    "fragment_identity",
    "layers_identity",
    "ledger_key",
    "materialize_bms_fragment",
    "materialize_book_fragment",
    "materialize_condition_preset",
    "merge_book_bms_keys",
    "run_config_identity",
    "run_id_root",
]
