"""Promotion and next-day activation (TN-20; Stories 26.9 and 26.10).

Human-only promotion runs the silent battery and lands ADMITTED with no
intent, ledger, or exposure. Activation is a separate act that becomes
effective only at the next account-scoped day-boundary. The passive hub
inbox is write-only and WriterId-scoped; sandbox provenance is refused at
hub publish and at the promotion pull. Persistence uses the closed CT-13
``promotion`` type and the CT-24 → ``risk transition`` mapping.
"""

from __future__ import annotations

from typing import Final

from qmn.promotion.battery import (
    ADMISSION_IMPACT_NONE,
    ADMISSION_IMPACT_RELINT,
    ADMISSION_IMPACT_RESIGN,
    ADMISSION_IMPACTS,
    DEMO_BASELINE_ENVIRONMENT,
    LIVE_BASELINE_ENVIRONMENT,
    AdmissionLayerFreshState,
    BatteryCheck,
    BatteryCheckId,
    ConfigGateFreshState,
    Ct18CapabilityFreshState,
    IdentityFingerprints,
    LiveBaselineFreshState,
    PromotionFreshState,
    ProtectionFreshState,
    SilentBatteryReport,
    live_gating_from_config,
    revalidate_fresh_state,
    run_silent_battery,
)
from qmn.promotion.hub import (
    HUB_CROSSINGS,
    SANDBOX_PROVENANCE,
    HubArtifact,
    PublishedHub,
    publish_hub_fragment,
    pull_published_as_of,
    refuse_sandbox_provenance,
)
from qmn.promotion.journal import (
    ACTIVATION_CT13_EVENT_TYPE,
    ACTIVATION_PAYLOAD_KEYS,
    ACTIVATION_TRIGGER,
    CT13_SEVEN_EVENT_TYPES,
    LOG_LINE_SUBSTITUTES_FOR_JOURNAL,
    PROMOTION_EVENT_TYPE,
    PROMOTION_PAYLOAD_KEYS,
    ActivationBindingTransition,
    ActivationJournalRow,
    ActivationPhase,
    ActivationReconstruction,
    CommittedActivation,
    PromotionJournalRow,
    assert_closed_ct13_event_type,
    commit_activation,
    commit_promotion,
    map_activation_ct13_event_type,
    persist_activation,
    persist_promotion,
    promotion_journal_payload,
    reconstruct_activation,
)
from qmn.promotion.lifecycle import (
    AGENT_SIGNER_PREFIXES,
    FORBIDDEN_ACTIVATION_OVERRIDES,
    SAME_DAY_TRADE_PATH_EXISTS,
    ActivationAcceptance,
    ActivationReadiness,
    PromotionLanding,
    admit_first_intent,
    promote_to_admitted,
    refuse_invented_ksa_or_latency,
    request_activation,
    revalidate_before_first_intent,
)
from qmn.promotion.passive_hub import (
    HUB_INBOX_NAME,
    HUB_PUBLISHED_NAME,
    INBOUND_CROSSINGS,
    HubFragment,
    InboxReceipt,
    PassiveHubTree,
    PublishReceipt,
    accept_inbox_fragment,
    publish_inbox_fragment,
    pull_from_published,
    refuse_evidence_sync_into_inbox,
    refuse_inbound_crossing,
    refuse_inbox_promotion_read,
    refuse_published_direct_write,
)

__all__ = [
    "ACTIVATION_CT13_EVENT_TYPE",
    "ACTIVATION_PAYLOAD_KEYS",
    "ACTIVATION_TRIGGER",
    "ADMISSION_IMPACTS",
    "ADMISSION_IMPACT_NONE",
    "ADMISSION_IMPACT_RELINT",
    "ADMISSION_IMPACT_RESIGN",
    "AGENT_SIGNER_PREFIXES",
    "CT13_SEVEN_EVENT_TYPES",
    "DEMO_BASELINE_ENVIRONMENT",
    "FORBIDDEN_ACTIVATION_OVERRIDES",
    "HUB_CROSSINGS",
    "HUB_INBOX_NAME",
    "HUB_PUBLISHED_NAME",
    "INBOUND_CROSSINGS",
    "LIVE_BASELINE_ENVIRONMENT",
    "LOG_LINE_SUBSTITUTES_FOR_JOURNAL",
    "PROMOTION_EVENT_TYPE",
    "PROMOTION_PAYLOAD_KEYS",
    "PROMOTION_SURFACE",
    "SAME_DAY_TRADE_PATH_EXISTS",
    "SANDBOX_PROVENANCE",
    "ActivationAcceptance",
    "ActivationBindingTransition",
    "ActivationJournalRow",
    "ActivationPhase",
    "ActivationReadiness",
    "ActivationReconstruction",
    "AdmissionLayerFreshState",
    "BatteryCheck",
    "BatteryCheckId",
    "CommittedActivation",
    "ConfigGateFreshState",
    "Ct18CapabilityFreshState",
    "HubArtifact",
    "HubFragment",
    "IdentityFingerprints",
    "InboxReceipt",
    "LiveBaselineFreshState",
    "PassiveHubTree",
    "PromotionFreshState",
    "PromotionJournalRow",
    "PromotionLanding",
    "ProtectionFreshState",
    "PublishReceipt",
    "PublishedHub",
    "SilentBatteryReport",
    "accept_inbox_fragment",
    "admit_first_intent",
    "assert_closed_ct13_event_type",
    "commit_activation",
    "commit_promotion",
    "live_gating_from_config",
    "map_activation_ct13_event_type",
    "persist_activation",
    "persist_promotion",
    "promote_to_admitted",
    "promotion_journal_payload",
    "publish_hub_fragment",
    "publish_inbox_fragment",
    "pull_from_published",
    "pull_published_as_of",
    "reconstruct_activation",
    "refuse_evidence_sync_into_inbox",
    "refuse_inbound_crossing",
    "refuse_inbox_promotion_read",
    "refuse_invented_ksa_or_latency",
    "refuse_published_direct_write",
    "refuse_sandbox_provenance",
    "request_activation",
    "revalidate_before_first_intent",
    "revalidate_fresh_state",
    "run_silent_battery",
]

PROMOTION_SURFACE: Final[str] = "qmn.promotion"
