"""qma.wire — sole cross-boundary contract package.

Envelope, command/query/event families, protocol version, initialize handshake,
compatibility law, scoped attach/detach replay, command idempotency on
``producer_id``+``id``, correlation provenance, the RLM ``host_request`` bridge
(closed-and-addable verb→primitive map, JobHandle async return,
``registry:rlm.depth_cap``), listener bind posture, pre-protocol credential-ref
authentication, dial-out reachability, the durable remote outbox spool, and
principal classes with the closed human-gate command list (AD-24).
Owns no client implementation and no alternate cross-boundary contract
(DEC-0304; AR-Q04). SemVer is display-only provenance in lockstep with the QMF
workspace (AR-Q11).
"""

from __future__ import annotations

from qma.wire.attach import (
    ATTACH_METHOD,
    DETACH_METHOD,
    AttachError,
    AttachRequest,
    AttachSubscription,
    ClientAttachmentState,
    DetachRequest,
    ReplayCursor,
    format_scope_key,
    mint_replay_cursor,
    validate_attach,
)
from qma.wire.auth import (
    FORBIDDEN_SECRET_SURFACE_KEYS,
    AuthenticatedWireSession,
    assert_no_secret_on_wire_surface,
    authenticate_before_protocol,
)
from qma.wire.compatibility import (
    COMPATIBILITY_AUTHORITY,
    DEPRECATION_MINORS_DEFAULT,
    DEPRECATION_MINORS_REGISTRY_KEY,
    CompatibilityError,
    CompatibilityVerdict,
    FamilyFormatDeclaration,
    ProtocolVersion,
    SchemaEvolutionProposal,
    assert_sole_compatibility_authority,
    evaluate_deprecation_removal,
    evaluate_schema_evolution,
    ignore_unknown_fields,
    ignore_unknown_types,
    parse_protocol_version,
)
from qma.wire.correlation import (
    CORRELATION_MINT_ORIGINS,
    CorrelationAdmission,
    CorrelationMintOrigin,
    admit_correlation,
    assert_copied_verbatim,
    copy_correlation_id,
    mint_correlation_id,
    propagate_correlation,
)
from qma.wire.envelope import (
    CORRELATION_MISSING_ANNOTATION,
    JOURNAL_SEQ_FIELD,
    SCOPE_KIND_ORDER,
    ScopePathError,
    ScopeSegment,
    WireEnvelope,
    WireEnvelopeError,
    is_scope_prefix,
    parse_scope_path,
)
from qma.wire.families import (
    FAMILY_CONTRACTS,
    FamilyContract,
    assert_client_close_safe,
    contract_for,
    contract_for_type,
    progress_is_authoritative,
    snapshots_are_authoritative,
)
from qma.wire.host_request import (
    ALTERNATE_RLM_TRANSPORTS,
    HOST_REQUEST_BRIDGE_TRANSPORT,
    HOST_REQUEST_OWNING_AD,
    HOST_REQUEST_PRIMITIVE_MAP,
    HOST_REQUEST_VERBS,
    HOST_REQUEST_VOCABULARY_OWNER,
    JOB_HANDLE_NONTERMINAL_STATES,
    JOB_HANDLE_TERMINAL_STATES,
    RLM_DEPTH_CAP_DEFAULT,
    RLM_DEPTH_CAP_REGISTRY_KEY,
    AsyncHostResult,
    HostRequestEmission,
    HostRequestMapping,
    HostRequestVerbError,
    JobHandleContract,
    assert_no_alternate_rlm_transport,
    emit_host_request,
    enforce_spawn_depth,
    example_host_request_payloads,
    host_request_type_family,
    host_request_wire_family,
    parse_host_request_verb,
    resolve_host_request,
)
from qma.wire.idempotency import (
    DEDUP_WINDOW_REGISTRY_KEY,
    CommandDedupCursor,
    DedupVerdict,
    IdempotencyKey,
    idempotency_key_from_envelope,
)
from qma.wire.initialize import (
    JSONRPC_VERSION,
    SUPPORTED_PROTOCOL_VERSIONS,
    WIRE_PROTOCOL_VERSION,
    InitializeError,
    InitializeParams,
    InitializeResult,
    JsonRpcRequest,
    JsonRpcResponse,
    WireConnection,
    negotiate_initialize,
)
from qma.wire.listener import (
    DEFAULT_BIND_HOST,
    ListenerBindConfig,
    ListenerPosture,
    is_loopback_host,
    validate_listener_startup,
)
from qma.wire.outbox import (
    REMOTE_OUTBOX_DEPTH_REGISTRY_KEY,
    REMOTE_SPOOL_BYTES_REGISTRY_KEY,
    UNKNOWN_TAIL_KIND,
    OutboxBounds,
    OutboxEntry,
    RemoteOutbox,
    UnknownTailRecord,
)
from qma.wire.principals import (
    DAEMON_JOB_TRIM_STREAMS,
    HUMAN_GATE_COMMANDS,
    HUMAN_GATE_OWNING_AD,
    HUMAN_GATE_VOCABULARY_OWNER,
    AuthorizedWireCommand,
    JournalPrincipalShape,
    LedgerPrincipalShape,
    PrincipalBearingCommand,
    authorize_wire_command,
    command_carries_principal,
    is_daemon_job_trim,
    is_human_gate_command,
    journal_entry_principal_shape,
    ledger_entry_principal_shape,
    parse_principal_class,
    refuse_principal_impersonation,
)
from qma.wire.reachability import (
    DAEMON_DIAL_DIRECTION,
    REMOTE_DIAL_DIRECTION,
    DeployedSideConfig,
    ReachabilityPosture,
    validate_deployed_side,
    validate_remote_dial_out,
)
from qma.wire.schemas import (
    SCHEMA_DIR,
    SCHEMA_FILES,
    SchemaValidationError,
    family_schema_name,
    load_schema,
    validate_family_payload,
    validate_instance,
    validate_wire_envelope_dict,
)
from qma.wire.vocabulary import (
    SEED_COMMAND_COUNT,
    SEED_EVENT_COUNT,
    SEED_QUERY_COUNT,
    SEED_VOCABULARY_COUNT,
    WIRE_COMMANDS,
    WIRE_EVENTS,
    WIRE_QUERIES,
    WIRE_VOCABULARY_OWNER,
    MessageFamily,
    WireCommand,
    WireEvent,
    WireQuery,
    WireVocabularyError,
    family_of,
    parse_wire_type,
)

__all__ = [
    "ALTERNATE_RLM_TRANSPORTS",
    "ATTACH_METHOD",
    "COMPATIBILITY_AUTHORITY",
    "CORRELATION_MINT_ORIGINS",
    "CORRELATION_MISSING_ANNOTATION",
    "DAEMON_DIAL_DIRECTION",
    "DAEMON_JOB_TRIM_STREAMS",
    "DEDUP_WINDOW_REGISTRY_KEY",
    "DEFAULT_BIND_HOST",
    "DEPRECATION_MINORS_DEFAULT",
    "DEPRECATION_MINORS_REGISTRY_KEY",
    "DETACH_METHOD",
    "FAMILY_CONTRACTS",
    "FORBIDDEN_SECRET_SURFACE_KEYS",
    "HOST_REQUEST_BRIDGE_TRANSPORT",
    "HOST_REQUEST_OWNING_AD",
    "HOST_REQUEST_PRIMITIVE_MAP",
    "HOST_REQUEST_VERBS",
    "HOST_REQUEST_VOCABULARY_OWNER",
    "HUMAN_GATE_COMMANDS",
    "HUMAN_GATE_OWNING_AD",
    "HUMAN_GATE_VOCABULARY_OWNER",
    "JOB_HANDLE_NONTERMINAL_STATES",
    "JOB_HANDLE_TERMINAL_STATES",
    "JOURNAL_SEQ_FIELD",
    "JSONRPC_VERSION",
    "REMOTE_DIAL_DIRECTION",
    "REMOTE_OUTBOX_DEPTH_REGISTRY_KEY",
    "REMOTE_SPOOL_BYTES_REGISTRY_KEY",
    "RLM_DEPTH_CAP_DEFAULT",
    "RLM_DEPTH_CAP_REGISTRY_KEY",
    "SCHEMA_DIR",
    "SCHEMA_FILES",
    "SCOPE_KIND_ORDER",
    "SEED_COMMAND_COUNT",
    "SEED_EVENT_COUNT",
    "SEED_QUERY_COUNT",
    "SEED_VOCABULARY_COUNT",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "UNKNOWN_TAIL_KIND",
    "WIRE_COMMANDS",
    "WIRE_EVENTS",
    "WIRE_PROTOCOL_VERSION",
    "WIRE_QUERIES",
    "WIRE_VOCABULARY_OWNER",
    "AsyncHostResult",
    "AttachError",
    "AttachRequest",
    "AttachSubscription",
    "AuthenticatedWireSession",
    "AuthorizedWireCommand",
    "ClientAttachmentState",
    "CommandDedupCursor",
    "CompatibilityError",
    "CompatibilityVerdict",
    "CorrelationAdmission",
    "CorrelationMintOrigin",
    "DedupVerdict",
    "DeployedSideConfig",
    "DetachRequest",
    "FamilyContract",
    "FamilyFormatDeclaration",
    "HostRequestEmission",
    "HostRequestMapping",
    "HostRequestVerbError",
    "IdempotencyKey",
    "InitializeError",
    "InitializeParams",
    "InitializeResult",
    "JobHandleContract",
    "JournalPrincipalShape",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "LedgerPrincipalShape",
    "ListenerBindConfig",
    "ListenerPosture",
    "MessageFamily",
    "OutboxBounds",
    "OutboxEntry",
    "PrincipalBearingCommand",
    "ProtocolVersion",
    "ReachabilityPosture",
    "RemoteOutbox",
    "ReplayCursor",
    "SchemaEvolutionProposal",
    "SchemaValidationError",
    "ScopePathError",
    "ScopeSegment",
    "UnknownTailRecord",
    "WireCommand",
    "WireConnection",
    "WireEnvelope",
    "WireEnvelopeError",
    "WireEvent",
    "WireQuery",
    "WireVocabularyError",
    "__version__",
    "admit_correlation",
    "assert_client_close_safe",
    "assert_copied_verbatim",
    "assert_no_alternate_rlm_transport",
    "assert_no_secret_on_wire_surface",
    "assert_sole_compatibility_authority",
    "authenticate_before_protocol",
    "authorize_wire_command",
    "command_carries_principal",
    "contract_for",
    "contract_for_type",
    "copy_correlation_id",
    "emit_host_request",
    "enforce_spawn_depth",
    "evaluate_deprecation_removal",
    "evaluate_schema_evolution",
    "example_host_request_payloads",
    "family_of",
    "family_schema_name",
    "format_scope_key",
    "host_request_type_family",
    "host_request_wire_family",
    "idempotency_key_from_envelope",
    "ignore_unknown_fields",
    "ignore_unknown_types",
    "is_daemon_job_trim",
    "is_human_gate_command",
    "is_loopback_host",
    "is_scope_prefix",
    "journal_entry_principal_shape",
    "ledger_entry_principal_shape",
    "load_schema",
    "mint_correlation_id",
    "mint_replay_cursor",
    "negotiate_initialize",
    "parse_host_request_verb",
    "parse_principal_class",
    "parse_protocol_version",
    "parse_scope_path",
    "parse_wire_type",
    "progress_is_authoritative",
    "propagate_correlation",
    "refuse_principal_impersonation",
    "resolve_host_request",
    "snapshots_are_authoritative",
    "validate_attach",
    "validate_deployed_side",
    "validate_family_payload",
    "validate_instance",
    "validate_listener_startup",
    "validate_remote_dial_out",
    "validate_wire_envelope_dict",
]

# Display-only provenance — never identity content (AR-Q11; DEC-0335).
__version__ = "0.1.0"
