"""Impure composition root: process spawn, governor, sinks, WriterId (B-4/B-5).

The library's ``run()`` is a pure function: it writes no log and no ledger.
This module is the one impure owner of injected sinks, process-per-run
spawn, the ``min(cpu, memory)`` governor, and OS-process abort on cancel or
per-run limit breach. The library never holds module-global mutable state
(DEC-0161).
"""

from __future__ import annotations

from typing import Final

from qmb.orchestrator.governor import (
    CPU_BUDGET_KEY,
    DECISION_ADMITTED,
    DECISION_QUEUED,
    MEMORY_BUDGET_KEY,
    ON_FULL_ENQUEUE,
    ON_FULL_REFUSE,
    SANDBOX_CONCURRENT_MOTIVATING_REFERENCE,
    Admission,
    GovernedRequest,
    GovernorBudgets,
    ResourceGovernor,
    governor_identity,
)
from qmb.orchestrator.ledger import (
    FACTORY_SANDBOX_ENV,
    FRAGMENT_FILENAME,
    LedgerSink,
    finish_run,
    fragment_path,
    is_factory_sandbox,
    mint_writer_id,
    read_book_bar,
    read_merge_view,
    writer_slot_token,
)
from qmb.orchestrator.log import (
    CORRELATION_ID_EXCLUDED_FROM_FP1,
    EVENT_RUN_ABORTED,
    EVENT_RUN_COMPLETED,
    EVENT_RUN_CRASHED,
    EVENT_RUN_REFUSED,
    EVENT_RUN_STARTED,
    EVENT_SPAWNED,
    EVIDENCE_BEARING_FORMATS,
    LOG_FILENAME,
    LOG_IS_EVIDENCE,
    LOG_KIND,
    LOG_RECORD_CLASS,
    LOGGER_NAME,
    TIMESTAMP_ENCODING,
    TIMESTAMP_EXCLUDED_FROM_FP1,
    LogSink,
    LogSinkHealth,
    OperationalRecord,
    append_run_log,
    inject_run_log,
    mint_correlation_id,
    operational_log_identity,
    propagate_correlation,
    read_run_log,
    run_log_path,
    structured_log_fp1_identity,
)
from qmb.orchestrator.spawn import (
    DAEMON,
    DOCKER,
    ONE_WRITER_PER_STREAM,
    PAYLOAD_NAME,
    PROCESS_MANAGEMENT,
    RAY,
    RESULT_NAME,
    WRITER_NAME,
    IsolatedRun,
    LiveSpawn,
    ProcessLimitProbe,
    SpawnJob,
    abort_run,
    collect_run,
    next_ready_run,
    run_directory_name,
    spawn_concurrent,
    spawn_governed,
    spawn_run,
    start_run,
    worker_main,
)
from qmb.orchestrator.study import (
    STUDY_STATE_RUNNING,
    STUDY_STATE_STOPPED,
    STUDY_STOP_OUTCOME_CLASS,
    STUDY_STOP_OUTCOME_FORMAT_VERSION,
    StudyStopOutcome,
    stop_study,
)
from qmb.orchestrator.watch import (
    ABORT_KILLS_SIBLINGS,
    ENFORCEMENT,
)
from qmb.runloop.observe import (
    MEMORY_LIMIT_KEY,
    PARTIAL_GOVERNED_RESULT_ON_ABORT,
    TIME_LIMIT_KEY,
)

__all__ = [
    "ABORT_KILLS_SIBLINGS",
    "CORRELATION_ID_EXCLUDED_FROM_FP1",
    "CPU_BUDGET_KEY",
    "DAEMON",
    "DECISION_ADMITTED",
    "DECISION_QUEUED",
    "DOCKER",
    "ENFORCEMENT",
    "EVENT_RUN_ABORTED",
    "EVENT_RUN_COMPLETED",
    "EVENT_RUN_CRASHED",
    "EVENT_RUN_REFUSED",
    "EVENT_RUN_STARTED",
    "EVENT_SPAWNED",
    "EVIDENCE_BEARING_FORMATS",
    "FACTORY_SANDBOX_ENV",
    "FRAGMENT_FILENAME",
    "IMPURE_OWNER",
    "LOGGER_NAME",
    "LOG_FILENAME",
    "LOG_IS_EVIDENCE",
    "LOG_KIND",
    "LOG_RECORD_CLASS",
    "MEMORY_BUDGET_KEY",
    "ONE_WRITER_PER_STREAM",
    "ON_FULL_ENQUEUE",
    "ON_FULL_REFUSE",
    "PAYLOAD_NAME",
    "PROCESS_MANAGEMENT",
    "RAY",
    "RESULT_NAME",
    "SANDBOX_CONCURRENT_MOTIVATING_REFERENCE",
    "SPAWN_MODEL",
    "STUDY_STATE_RUNNING",
    "STUDY_STATE_STOPPED",
    "STUDY_STOP_OUTCOME_CLASS",
    "STUDY_STOP_OUTCOME_FORMAT_VERSION",
    "TIMESTAMP_ENCODING",
    "TIMESTAMP_EXCLUDED_FROM_FP1",
    "WRITER_NAME",
    "Admission",
    "GovernedRequest",
    "GovernorBudgets",
    "IsolatedRun",
    "LedgerSink",
    "LiveSpawn",
    "LogSink",
    "LogSinkHealth",
    "OperationalRecord",
    "ProcessLimitProbe",
    "ResourceGovernor",
    "SpawnJob",
    "StudyStopOutcome",
    "abort_run",
    "append_run_log",
    "collect_run",
    "finish_run",
    "fragment_path",
    "governor_identity",
    "inject_run_log",
    "is_factory_sandbox",
    "mint_correlation_id",
    "mint_writer_id",
    "next_ready_run",
    "operational_log_identity",
    "orchestrator_identity",
    "propagate_correlation",
    "read_book_bar",
    "read_merge_view",
    "read_run_log",
    "run_directory_name",
    "run_log_path",
    "spawn_concurrent",
    "spawn_governed",
    "spawn_run",
    "start_run",
    "stop_study",
    "structured_log_fp1_identity",
    "worker_main",
    "writer_slot_token",
]

IMPURE_OWNER: Final[str] = "orchestrator"
SPAWN_MODEL: Final[str] = "process-per-run"


def orchestrator_identity() -> dict[str, object]:
    """Identity-bearing orchestrator fields. Package SemVer is omitted."""
    identity: dict[str, object] = {
        "impure_owner": IMPURE_OWNER,
        "spawn_model": SPAWN_MODEL,
        "governor": "min-cpu-memory",
        "process_management": PROCESS_MANAGEMENT,
        "ray": RAY,
        "docker": DOCKER,
        "daemon": DAEMON,
        "one_writer_per_stream": ONE_WRITER_PER_STREAM,
        "abort_kills_siblings": ABORT_KILLS_SIBLINGS,
        "enforcement": ENFORCEMENT,
        "time_limit_key": TIME_LIMIT_KEY,
        "memory_limit_key": MEMORY_LIMIT_KEY,
        "partial_governed_result_on_abort": PARTIAL_GOVERNED_RESULT_ON_ABORT,
        "cancel_token": True,
        "ledger_writes": IMPURE_OWNER,
        "ledger_fragment": FRAGMENT_FILENAME,
        "factory_sandbox_env": FACTORY_SANDBOX_ENV,
        "log_writes": IMPURE_OWNER,
    }
    identity.update(governor_identity())
    identity.update(operational_log_identity())
    return identity
