"""qmb — the QMX experimentation/backtesting library plus the ``qmb`` CLI.

One uv-installable distribution (``import qmb``), an application-layer product
built on QMF, never a roster package. Imports the six backend QMF packages in
workspace lockstep; never ``qmf-venue``.

``__version__`` is display-only SemVer provenance and never enters ``fp1``
(DEC-0167). Identity lives on the resolved run-config fingerprint.
"""

from __future__ import annotations

from typing import Final

from qmb._backends import BACKEND_PACKAGES, backend_display_versions
from qmb._display import __version__, identity_payload
from qmb.config import (
    BMS_NAMESPACES,
    BMS_RECORD_KIND,
    BOOK_NAMESPACES,
    BOOK_RECORD_KIND,
    CITE_FIELDS,
    CLOCK_REPLAY,
    CLOCK_SIMULATED,
    CONFIG_FRAGMENT_CLASS,
    DISPLAY_FIELDS,
    FOLD_RATED,
    FOLD_UNRATED,
    FRAGMENT_FORMAT_VERSION,
    FRAGMENT_FORMAT_VERSION_1,
    FRAGMENT_KNOWN_FORMAT_VERSIONS,
    FRAGMENT_LINEAGE_EDGE_TYPE,
    IDENTITY_FIELDS,
    LAYER_PRECEDENCE,
    OPTIONAL_IDENTITY_FIELDS,
    PROVENANCE_PROCEDURE_EPHEMERAL,
    PROVENANCE_RECORDED,
    PROVENANCE_SYNTHETIC_TAINTED,
    REPLAY_BINDING_CLASS,
    RUN_CONFIG_ARTIFACT_NAME,
    RUN_CONFIG_CLASS,
    RUN_CONFIG_FORMAT_VERSION,
    RUN_CONFIG_FORMAT_VERSION_1,
    RUN_CONFIG_KNOWN_FORMAT_VERSIONS,
    SANCTIONED_OVERLAP_KEYS,
    SOURCE_BMS,
    SOURCE_BOOK,
    SOURCE_PRESET,
    STARTING_CAPITAL_KEY,
    VIRTUAL_LEDGER_CLASS,
    ConfigFragment,
    ReplayBinding,
    ResolvedRunConfig,
    VirtualLedger,
    artifact_relative_path,
    check_incomparable_to_live,
    coerce_starting_capital,
    compile_run_config,
    fingerprint_layers,
    fragment_identity,
    layers_identity,
    ledger_key,
    materialize_bms_fragment,
    materialize_book_fragment,
    materialize_condition_preset,
    merge_book_bms_keys,
    mint_replay_binding,
    resolve_starting_capital,
    run_config_identity,
    run_id_root,
)
from qmb.data import DATA_COMMANDS, data_front_identity
from qmb.doors import CLI_PIN_KEY, CLI_PROG, MCP_SHIPPED
from qmb.execution import (
    PORT_ROLES,
    admit_open,
    evaluate_exit,
    mint_replay_exit,
    ports_identity,
    require_full_loss_before_open,
)
from qmb.ledger import RUN_ROLES, ledger_identity
from qmb.optimize import SAMPLER_JOBS, SAMPLER_PIN_KEY, sampler_identity
from qmb.orchestrator import IMPURE_OWNER, SPAWN_MODEL, orchestrator_identity
from qmb.registryread import (
    AS_OF_FORMAT_VERSION,
    HUB_KIND,
    STALE_EVIDENCE_SEVERITY_KEY,
    STATE_KIND,
    AsOfSet,
    DatedPointer,
    PassiveHub,
    RegistryFragment,
    RegistryReadPort,
    ResolvedRef,
    SupersedesRef,
    port_home,
    read_port_identity,
)
from qmb.results import RESULT_CONTRACT, result_identity
from qmb.robustness import PROCEDURES, ladder_identity
from qmb.runloop import (
    CLOCK_DOES_NOT_CHOOSE_WORLD,
    LOOP_KIND,
    SUBPHASES,
    FrontierClock,
    NextEmitStream,
    StreamNextEmit,
    advance_frontier,
    as_wall_replay_instant,
    frontier_clock_name,
    loop_identity,
    min_next_emit,
    read_frontier,
    script_replay_clock,
)

STRUCTURAL_SEED: Final[tuple[str, ...]] = (
    "runloop",
    "config",
    "registryread",
    "execution",
    "data",
    "optimize",
    "robustness",
    "results",
    "ledger",
    "orchestrator",
    "doors/cli",
    "doors/api",
    "doors/mcp",
)

__all__ = [
    "AS_OF_FORMAT_VERSION",
    "BACKEND_PACKAGES",
    "BMS_NAMESPACES",
    "BMS_RECORD_KIND",
    "BOOK_NAMESPACES",
    "BOOK_RECORD_KIND",
    "CITE_FIELDS",
    "CLI_PIN_KEY",
    "CLI_PROG",
    "CLOCK_DOES_NOT_CHOOSE_WORLD",
    "CLOCK_REPLAY",
    "CLOCK_SIMULATED",
    "CONFIG_FRAGMENT_CLASS",
    "DATA_COMMANDS",
    "DISPLAY_FIELDS",
    "FOLD_RATED",
    "FOLD_UNRATED",
    "FRAGMENT_FORMAT_VERSION",
    "FRAGMENT_FORMAT_VERSION_1",
    "FRAGMENT_KNOWN_FORMAT_VERSIONS",
    "FRAGMENT_LINEAGE_EDGE_TYPE",
    "HUB_KIND",
    "IDENTITY_FIELDS",
    "IMPURE_OWNER",
    "LAYER_PRECEDENCE",
    "LOOP_KIND",
    "MCP_SHIPPED",
    "OPTIONAL_IDENTITY_FIELDS",
    "PORT_ROLES",
    "PROCEDURES",
    "PROVENANCE_PROCEDURE_EPHEMERAL",
    "PROVENANCE_RECORDED",
    "PROVENANCE_SYNTHETIC_TAINTED",
    "REPLAY_BINDING_CLASS",
    "RESULT_CONTRACT",
    "RUN_CONFIG_ARTIFACT_NAME",
    "RUN_CONFIG_CLASS",
    "RUN_CONFIG_FORMAT_VERSION",
    "RUN_CONFIG_FORMAT_VERSION_1",
    "RUN_CONFIG_KNOWN_FORMAT_VERSIONS",
    "RUN_ROLES",
    "SAMPLER_JOBS",
    "SAMPLER_PIN_KEY",
    "SANCTIONED_OVERLAP_KEYS",
    "SOURCE_BMS",
    "SOURCE_BOOK",
    "SOURCE_PRESET",
    "SPAWN_MODEL",
    "STALE_EVIDENCE_SEVERITY_KEY",
    "STARTING_CAPITAL_KEY",
    "STATE_KIND",
    "STRUCTURAL_SEED",
    "SUBPHASES",
    "VIRTUAL_LEDGER_CLASS",
    "AsOfSet",
    "ConfigFragment",
    "DatedPointer",
    "FrontierClock",
    "NextEmitStream",
    "PassiveHub",
    "RegistryFragment",
    "RegistryReadPort",
    "ReplayBinding",
    "ResolvedRef",
    "ResolvedRunConfig",
    "StreamNextEmit",
    "SupersedesRef",
    "VirtualLedger",
    "__version__",
    "admit_open",
    "advance_frontier",
    "artifact_relative_path",
    "as_wall_replay_instant",
    "backend_display_versions",
    "check_incomparable_to_live",
    "coerce_starting_capital",
    "compile_run_config",
    "data_front_identity",
    "evaluate_exit",
    "fingerprint_layers",
    "fragment_identity",
    "frontier_clock_name",
    "identity_payload",
    "ladder_identity",
    "layers_identity",
    "ledger_identity",
    "ledger_key",
    "loop_identity",
    "materialize_bms_fragment",
    "materialize_book_fragment",
    "materialize_condition_preset",
    "merge_book_bms_keys",
    "min_next_emit",
    "mint_replay_binding",
    "mint_replay_exit",
    "orchestrator_identity",
    "port_home",
    "ports_identity",
    "read_frontier",
    "read_port_identity",
    "require_full_loss_before_open",
    "resolve_starting_capital",
    "result_identity",
    "run_config_identity",
    "run_id_root",
    "sampler_identity",
    "script_replay_clock",
]
