# Build extractions/volatility.jsonl from curated full-read notes.
# Run from QMX root. Write-only under this research folder.

from __future__ import annotations

import json
from pathlib import Path

OUT = Path("workroom/research/2026-09-15_unbounded-market-intelligence/extractions/volatility.jsonl")
MD = ".worktrees/mql5-library/data/mql5-library/md"

SCHEMA = [
    "article_id",
    "path",
    "title",
    "source",
    "publication_date",
    "authors",
    "topics",
    "market_mechanisms",
    "asset_or_venue_dependencies",
    "time_horizons",
    "data_requirements",
    "central_claims",
    "formulas",
    "algorithms",
    "implementation_details",
    "execution_assumptions",
    "cost_assumptions",
    "risk_assumptions",
    "evidence_level",
    "reproducibility",
    "lookahead_or_leakage_risks",
    "transferable_mechanism",
    "qmx_overlap",
    "qmx_possible_gap",
    "testable_hypotheses",
    "confidence",
    "supporting_excerpts",
]


def R(**kw):
    row = {k: kw.get(k, [] if k in {
        "authors", "topics", "market_mechanisms", "asset_or_venue_dependencies",
        "time_horizons", "data_requirements", "central_claims", "formulas",
        "algorithms", "implementation_details", "execution_assumptions",
        "cost_assumptions", "risk_assumptions", "lookahead_or_leakage_risks",
        "testable_hypotheses", "supporting_excerpts",
    } else "") for k in SCHEMA}
    row.update(kw)
    row["source"] = "mql5-library-local"
    row["path"] = f"{MD}/{row['article_id']}.md"
    return row


recs = []

# --- Dube Volatility Models series ---
recs.append(R(
    article_id=20589,
    title="Building Volatility models in MQL5 (Part I): The Initial Implementation",
    publication_date="2026-01-14T11:13Z",
    authors=["Francis Dube"],
    topics=["ARCH", "GARCH", "conditional variance", "HAR/AR mean", "vol forecast library"],
    market_mechanisms=["volatility clustering", "conditional heteroskedasticity", "joint MLE mean+vol+dist"],
    asset_or_venue_dependencies=["MT5 OHLC any symbol; demos FX/metal closes (AUDUSD/XAUUSD-style); not exchange microstructure"],
    time_horizons=["bar returns; multi-step analytic/bootstrap forecast horizon"],
    data_requirements=["log-return vector", "optional exogenous matrix", "lags + optional holdout"],
    central_claims=[
        "Native MQL5 arch-style library: mean (const/zero/AR/HAR/X) x vol (const/ARCH/GARCH) x residual distribution.",
        "Joint log-likelihood fit via ALGLIB; forecast returns mean/variance/residual_variance matrices.",
        "ARCH-LM diagnostics check residual heteroskedasticity after fit.",
    ],
    formulas=["GARCH(1,1): sigma2_t = omega + alpha*eps2_{t-1} + beta*sigma2_{t-1}"],
    algorithms=["ArchParameters composition", "HARX.fit", "analytic/bootstrap forecast", "ARCH-LM"],
    implementation_details=["mean.mqh HARX facade", "volatility process subclasses", "ArchModelResult/ArchForecast"],
    execution_assumptions=["scaled returns improve optimizer", "empty params => failed convergence"],
    cost_assumptions=["CPU cost of MLE per refit; no trading costs"],
    risk_assumptions=["symmetric GARCH misses leverage", "optimizer failure"],
    evidence_level="B",
    reproducibility="Code + demos attached; Python numeric parity deferred to Part III",
    lookahead_or_leakage_risks=["Fitting including the forecast bar leaks; holdout must be honored"],
    transferable_mechanism="Conditional variance as first-class state separate from direction — MIS vol coordinate (label/filter), never Book sizing.",
    qmx_overlap="regime_classifier_v1 needs vol features; conditional variance is a candidate coordinate.",
    qmx_possible_gap="No fitted conditional-variance producer in V1; recovered MS-GARCH unauthoritative.",
    testable_hypotheses=["Rolling GARCH(1,1) ranks next |r| better than ATR on FX D1"],
    confidence=0.78,
    supporting_excerpts=[
        "we present an MQL5 library for modeling and forecasting volatility",
        "Joint estimation of the model's parameters is performed by calling one of the fit() methods",
    ],
))

recs.append(R(
    article_id=22258,
    title="Building Volatility Models in MQL5 (Part II): Implementing GJR-GARCH and TARCH in MQL5",
    publication_date="2026-04-30T11:05Z",
    authors=["Francis Dube"],
    topics=["GJR-GARCH", "TARCH", "leverage effect", "asymmetric volatility", "vol z-score"],
    market_mechanisms=["leverage effect (Black 1976)", "volatility feedback / loss aversion", "asymmetric news impact curve"],
    asset_or_venue_dependencies=["Demo AUDUSD D1; theory equity-centric; FX leverage effect mixed"],
    time_horizons=["D1 demo; indicator sliding HistoryLen then 1-step forecast"],
    data_requirements=["scaled log returns", "O>=1 for GJR", "TARCH power=1"],
    central_claims=[
        "Symmetric GARCH erases shock sign; GJR adds gamma*I(neg)*eps2; TARCH models conditional stdev.",
        "gamma>0 measures fragility/leverage useful for risk intuition.",
        "ConditionalVolatility_forecaster emits forecast + vol z-score for abnormal spikes.",
    ],
    formulas=[
        "GJR: sigma2_t = w + a*e2_{t-1} + g*I_{t-1}*e2_{t-1} + b*sigma2_{t-1}",
        "TARCH power=1 on absolute shocks",
        "vol_z = (forecast - mean_hist)/std_hist",
    ],
    algorithms=["CGjrGarchProcess/CTarchProcess", "sliding refit excluding current bar", "news impact curve script"],
    implementation_details=["VOL_GJR_GARCH/VOL_TARCH", "GJR_Demo/TARCH_Demo", "Num_Stds threshold"],
    execution_assumptions=["refit excludes most recent bar", "ScaleFactor~100"],
    cost_assumptions=["per-bar MLE costly on low TF"],
    risk_assumptions=["equity leverage may not transfer to FX", "check gamma p-values"],
    evidence_level="B",
    reproducibility="Attached demos; no large walk-forward study",
    lookahead_or_leakage_risks=["Including current bar in fit leaks 1-step forecast; article claims exclusion"],
    transferable_mechanism="Signed-shock asymmetric conditional variance and vol z-score as filter/regime features.",
    qmx_overlap="MIS stress vs elevated can use asymmetry; filter only.",
    qmx_possible_gap="No GJR gamma / vol-z producer in V1; must not size.",
    testable_hypotheses=["GJR AIC < GARCH on equity CFDs; gamma often insignificant on majors FX"],
    confidence=0.82,
    supporting_excerpts=[
        "volatility tends to rise much more sharply following a price drop",
        "gamma acts as a quantitative measure of market fragility",
        "indicator computes a volatility z-score",
    ],
))

recs.append(R(
    article_id=22714,
    title="Building Volatility Models in MQL5 (Part III): Implementing the SLSQP Algorithm for Model Estimation",
    publication_date="2026-05-30T11:37Z",
    authors=["Francis Dube"],
    topics=["SLSQP", "MLE optimizer", "Python arch parity"],
    market_mechanisms=["optimizer bias in estimated conditional variance"],
    asset_or_venue_dependencies=["AUDUSD/EURUSD-style samples; method-general"],
    time_horizons=["fit-sample length"],
    data_requirements=["identical starts/scaling/constraints vs Python"],
    central_claims=[
        "Param divergence vs Python arch was optimizer (minNLC), not LLH bugs.",
        "SLSQP port matches Python params/LLH within practical tolerances.",
    ],
    formulas=["constrained NLP max LLH(theta) s.t. bounds/stationarity"],
    algorithms=["SLSQP with bounds + linear constraints in HARX.fit"],
    implementation_details=["native SLSQP; gradients; stopping criteria"],
    execution_assumptions=["matched starting values and backcast"],
    cost_assumptions=["iteration cost vs minNLC"],
    risk_assumptions=["wrong optimizer => wrong vol state"],
    evidence_level="A",
    reproducibility="Explicit Python vs MQL5 LLH/param comparison",
    lookahead_or_leakage_risks=["standard in-sample fit only"],
    transferable_mechanism="Estimation fidelity is part of the vol-state contract.",
    qmx_overlap="Any fitted vol producer needs optimizer validation before shadow.",
    qmx_possible_gap="No numeric validation harness for conditional-vol fits in QMX.",
    testable_hypotheses=["SLSQP vs minNLC param L2 distance material on FX returns"],
    confidence=0.85,
    supporting_excerpts=[
        "main source of cross-platform divergence was the optimizer, not the log-likelihood computation",
        "reproduces Python ARCH results reproducibly",
    ],
))

recs.append(R(
    article_id=23171,
    title="Building Volatility Models in MQL5 (Part IV): Implementing Long Memory Volatility Processes, FIGARCH, and HARCH",
    publication_date="2026-07-03T08:34Z",
    authors=["Francis Dube"],
    topics=["FIGARCH", "HARCH", "long memory", "Hurst R/S", "GPH d"],
    market_mechanisms=["hyperbolic vol decay", "multi-horizon aggregation"],
    asset_or_venue_dependencies=["AUDUSD demos; claims on |r| or r^2 proxies"],
    time_horizons=["N>=200 for R/S; multi-day/week persistence; HARCH explicit horizons"],
    data_requirements=["abs/squared returns", "periodogram", "spectral diagnostic"],
    central_claims=[
        "GARCH(1,1) forgets too fast or becomes IGARCH; real vol often long-memory.",
        "Workflow: Hurst R/S + GPH d + log-periodogram => FIGARCH vs HARCH.",
        "H in (0.5,1) and d in (0,0.5) support stationary long memory.",
    ],
    formulas=[
        "log(R/S) ~ H log(n)",
        "GPH regression for fractional d",
        "FIGARCH fractional lag on ARCH; HARCH multi-horizon squares",
    ],
    algorithms=["hurst_exponent_rs", "gph_test", "FIGARCH/HARCH classes", "spectral plot"],
    implementation_details=["tests.mqh safeguards", "library VOL_FIGARCH/VOL_HARCH"],
    execution_assumptions=["GPH alpha~0.5", "min sample checks"],
    cost_assumptions=["FFT + heavier MLE than GARCH(1,1)"],
    risk_assumptions=["spurious long memory from breaks"],
    evidence_level="B",
    reproducibility="Code + diagnostic workflow; empiricals are reader-run",
    lookahead_or_leakage_risks=["Full-sample Hurst/GPH before decisions overfits; use rolling+embargo"],
    transferable_mechanism="Long-memory gate: when d>0, short-memory ATR/GARCH understates persistence of elevated/stressed.",
    qmx_overlap="Regime persistence / stressed duration.",
    qmx_possible_gap="No Hurst/GPH or long-memory vol feature in V1.",
    testable_hypotheses=["FX D1 r^2 GPH d>0 more often than M1", "FIGARCH MAE < GARCH when H>0.6"],
    confidence=0.8,
    supporting_excerpts=[
        "volatility often decays much more slowly—clusters can persist for weeks or months",
        "choose FIGARCH when the spectrum shows a continuous fractional slope or HARCH when the spectrum",
    ],
))

recs.append(R(
    article_id=23677,
    title="Building Volatility Models in MQL5 (Part V): Implementing EGARCH as an Alternate Asymmetric Volatility Process",
    publication_date="2026-08-17T09:41Z",
    authors=["Francis Dube"],
    topics=["EGARCH", "positivity constraints", "leverage tests", "log variance"],
    market_mechanisms=["log-variance positivity without nonneg bounds", "asset-class-dependent leverage sign"],
    asset_or_venue_dependencies=["XAUUSD/commodity vs equity gamma sign may flip; FX mixed"],
    time_horizons=["bar returns; multi-step analytic/simulation forecast"],
    data_requirements=["returns for MLE", "leverage diagnostic tests"],
    central_claims=[
        "GARCH nonnegativity can pin alpha~0 with p~1, misrepresenting data.",
        "EGARCH models log(sigma2); gamma<0 typical equities, gamma>0 common commodities.",
        "Adds CEgarchProcess, leverage tests, EGARCH indicators.",
    ],
    formulas=[
        "log(sigma2_t)=w + sum a(|z|-E|z|) + sum g*z + sum b*log(sigma2)",
        "stationarity: sum beta < 1",
    ],
    algorithms=["egarch_recursion", "grid startingValues", "leverage/sign-bias tests", "SLSQP"],
    implementation_details=["VOL_EGARCH", "log backCast", "unbounded short-run coeffs"],
    execution_assumptions=["power=2 default", "Normal residuals default"],
    cost_assumptions=["similar MLE cost to GJR"],
    risk_assumptions=["negative beta unstable", "wrong gamma-sign prior by asset class"],
    evidence_level="B",
    reproducibility="Boundary-pathology script + EGARCH code",
    lookahead_or_leakage_risks=["same rolling-fit leakage as Part II"],
    transferable_mechanism="Constraint-free asymmetric vol; store gamma sign as MIS metadata by venue/asset.",
    qmx_overlap="Asymmetry coordinate for stressed vs elevated; gold vs FX differ.",
    qmx_possible_gap="No EGARCH/gamma producer; no asset-class leverage-sign prior.",
    testable_hypotheses=["XAUUSD EGARCH gamma>0 more often than equity CFDs"],
    confidence=0.81,
    supporting_excerpts=[
        "one parameter's p-value is very close to 1",
        "By modeling the natural logarithm of conditional variance",
        "positive gamma is frequently observed in commodity markets",
    ],
))

# --- Beyond GARCH / MMAR series ---
recs.append(R(
    article_id=22438,
    title="Beyond GARCH (Part I): Mandelbrot's MMAR versus Engle's GARCH",
    publication_date="2026-05-18T10:51Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["MMAR", "GARCH limits", "multifractal scaling", "partition function"],
    market_mechanisms=["multifractal trading time", "fat tails + long memory beyond GARCH"],
    asset_or_venue_dependencies=["EURUSD M5 via MT5 Python API — FX spot CFD/broker feed"],
    time_horizons=["5-minute returns; multi-scale partition intervals"],
    data_requirements=["EURUSD M5 history", "partition function params"],
    central_claims=[
        "GARCH assumes thin tails, short memory, single timescale — structural blind spots.",
        "EURUSD M5 shows multifractal scaling via partition function — MMAR candidate.",
        "Vol forecast quality drives risk/position logic in authors' framing (Book-layer, not MIS).",
    ],
    formulas=["partition function moment scaling", "GARCH(1,1) baseline"],
    algorithms=["MT5 Python data load", "partition analysis step1"],
    implementation_details=["config.py DATA PARAMETERS", "Python pipeline"],
    execution_assumptions=["broker EURUSD M5 continuous enough for scaling tests"],
    cost_assumptions=["offline Python compute"],
    risk_assumptions=["multifractality can be spurious; needs later decision tests"],
    evidence_level="B",
    reproducibility="Python scripts; EURUSD M5 reproducible if same window",
    lookahead_or_leakage_risks=["full-sample multifractal test before trading"],
    transferable_mechanism="Test whether vol process is mono-scale GARCH-like or multifractal before choosing MIS features.",
    qmx_overlap="Family choice for vol coordinate; lightgbm regime vs GARCH/MMAR.",
    qmx_possible_gap="No multifractal/partition diagnostic in MIS producers.",
    testable_hypotheses=["EURUSD M5 tau(q) nonlinear => reject monofractal"],
    confidence=0.74,
    supporting_excerpts=[
        "GARCH assumes thin tails, has only short (exponentially decaying) memory, and operates on a single time scale",
        "our data exhibits multifractal scaling",
    ],
))

recs.append(R(
    article_id=22484,
    title="Beyond GARCH (Part II): Measuring the Fractal Dimension of Markets",
    publication_date="2026-05-19T15:16Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["Hurst exponent", "scaling function tau(q)", "multifractal spectrum"],
    market_mechanisms=["path roughness via H", "memory structure vs EMH H=0.5"],
    asset_or_venue_dependencies=["EURUSD M5"],
    time_horizons=["multi-scale from M5 base"],
    data_requirements=["partition outputs from Part I"],
    central_claims=[
        "H encodes memory; H!=0.5 miscalibrates classical risk as horizon grows.",
        "Extract tau(q), H, and decide multifractality before spectrum fit.",
    ],
    formulas=["tau(q) scaling", "Hurst from tau", "spectrum precursors"],
    algorithms=["step2_extract_scaling", "step3_fit_spectrum start"],
    implementation_details=["Python steps 2-3"],
    execution_assumptions=["stable partition scales"],
    cost_assumptions=["offline"],
    risk_assumptions=["H estimation sensitive to scale choice"],
    evidence_level="B",
    reproducibility="Python scripts chained from Part I",
    lookahead_or_leakage_risks=["in-sample H used as if known ex ante"],
    transferable_mechanism="H as MIS side-feature for persistence of vol regimes.",
    qmx_overlap="Persistence of quiet|elevated|stressed labels.",
    qmx_possible_gap="No Hurst feature in V1 sensors.",
    testable_hypotheses=["|H-0.5| predicts longer elevated-label runs"],
    confidence=0.72,
    supporting_excerpts=[
        "The H = 0.5 assumption embedded in classical finance systematically miscalibrates risk when the true H differs",
    ],
))

recs.append(R(
    article_id=22476,
    title="Beyond GARCH (Part III): Building the MMAR and the Verdict",
    publication_date="2026-05-21T15:20Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["MMAR construction", "FBM", "multiplicative cascade", "Monte Carlo vs GARCH"],
    market_mechanisms=["returns = FBM o multifractal trading time"],
    asset_or_venue_dependencies=["EURUSD M5"],
    time_horizons=["MC forecast horizons vs GARCH"],
    data_requirements=["fitted H and cascade distribution"],
    central_claims=[
        "Built full MMAR path: cascade + FBM + combine + MC forecast.",
        "Head-to-head: MMAR captures more structure than GARCH on this EURUSD sample (author verdict).",
    ],
    formulas=["MMAR composition equation", "MC vol aggregation"],
    algorithms=["steps 4-7 Python", "Monte Carlo forecasting"],
    implementation_details=["cascade/fbm/combine/monte_carlo scripts"],
    execution_assumptions=["Zhang 2017 pipeline fidelity"],
    cost_assumptions=["MC path count dominates runtime"],
    risk_assumptions=["single-pair verdict; overfit risk"],
    evidence_level="C",
    reproducibility="Scripts present; exact metrics window-dependent",
    lookahead_or_leakage_risks=["parameters fit on same series used to claim superiority"],
    transferable_mechanism="MC distributional vol forecast vs point GARCH — uncertainty as MIS confidence.",
    qmx_overlap="Uncertainty bands around vol coordinate.",
    qmx_possible_gap="No distributional vol forecast in MIS.",
    testable_hypotheses=["MMAR CI coverage of realized |r| better calibrated than GARCH on FX M5 OOS"],
    confidence=0.68,
    supporting_excerpts=[
        "The MMAR captures more. By decomposing returns into Fractional Brownian Motion (long memory) and multifractal trading time",
    ],
))

recs.append(R(
    article_id=21299,
    title="Beyond GARCH (Part IV): Partition Analysis in MQL5",
    publication_date="2026-05-30T11:42Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["MQL5 MMAR library", "partition analysis", "OLS", "Hurst"],
    market_mechanisms=["in-terminal multifractal diagnostics"],
    asset_or_venue_dependencies=["EURUSD live MT5; gold mentioned"],
    time_horizons=["return series length for partition scales"],
    data_requirements=["returns vector in MQL5"],
    central_claims=[
        "Ports partition engine to MQL5: OLS, generalized Hurst, multifractal decision.",
        "Native path removes Python dependency for detection stage.",
    ],
    formulas=["OLS log-log scaling", "generalized Hurst"],
    algorithms=["CPartitionAnalysis", "MMARConstants"],
    implementation_details=["shared types", "live-data runner"],
    execution_assumptions=["enough bars for scales"],
    cost_assumptions=["in-terminal OLS across q and scales"],
    risk_assumptions=["broker feed gaps distort scaling"],
    evidence_level="B",
    reproducibility="MQL5 modules + live runner",
    lookahead_or_leakage_risks=["using full chart history without embargo"],
    transferable_mechanism="On-chart multifractal gate before trusting mono-scale vol features.",
    qmx_overlap="Feature-family selection for regime model.",
    qmx_possible_gap="No partition/Hurst module in MIS codebase.",
    testable_hypotheses=["Partition reject-monofractal rate differs FX vs gold"],
    confidence=0.73,
    supporting_excerpts=[
        "self-contained MQL5 class that can take any return series, compute its multifractal scaling properties",
    ],
))

recs.append(R(
    article_id=22519,
    title="Beyond GARCH (Part V): Fitting the Multifractal Spectrum in MQL5",
    publication_date="2026-06-09T12:23Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["Legendre transform", "singularity spectrum f(alpha)", "BLEIC fit"],
    market_mechanisms=["local smoothness alpha vs fractal dimension f(alpha)"],
    asset_or_venue_dependencies=["EURUSD; equity mentioned"],
    time_horizons=["from partition tau(q)"],
    data_requirements=["tau(q) curve"],
    central_claims=[
        "Legendre transform tau(q)->f(alpha); fit four theoretical spectra via BLEIC.",
        "Winning distribution parametrizes cascade for simulation.",
    ],
    formulas=["alpha = d tau/dq", "f(alpha)=q*alpha - tau(q)", "four candidate spectra"],
    algorithms=["CSpectrumFitter", "ALGLIB BLEIC"],
    implementation_details=["bounded nonlinear opt"],
    execution_assumptions=["stable tau(q)"],
    cost_assumptions=["BLEIC iterations"],
    risk_assumptions=["wrong spectrum family => bad cascade"],
    evidence_level="B",
    reproducibility="MQL5 fitter module",
    lookahead_or_leakage_risks=["in-sample spectrum selection"],
    transferable_mechanism="Spectrum width as mixing diagnostic independent of vol level.",
    qmx_overlap="Separating structural mixing from vol magnitude (cf. 22638).",
    qmx_possible_gap="No spectrum-width feature.",
    testable_hypotheses=["Delta-alpha uncorrelated with realized vol on FX"],
    confidence=0.7,
    supporting_excerpts=[
        "alpha gives the local smoothness and f(alpha) gives the fractal dimension of points sharing that smoothness",
    ],
))

# fix reproducibility list typo if any later validation
recs[-1]["reproducibility"] = "MQL5 fitter module"

recs.append(R(
    article_id=22521,
    title="Beyond GARCH (Part VI): Fractional Brownian Motion And The Multiplicative Cascade in MQL5",
    publication_date="2026-06-23T08:25Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["FBM", "multiplicative cascade", "MMAR simulation"],
    market_mechanisms=["multifractal trading time + long-memory FBM"],
    asset_or_venue_dependencies=["params from prior EURUSD fits; gold mentioned"],
    time_horizons=["synthetic path length = forecast horizon"],
    data_requirements=["fitted spectrum distribution", "H"],
    central_claims=[
        "CSimulationEngine builds cascade then FBM then MMAR paths.",
        "Validation checks synthetic vs empirical moments/scaling.",
    ],
    formulas=["cascade mass weights", "FBM covariance via FFT/Cholesky", "MMAR combine"],
    algorithms=["CSimulationEngine"],
    implementation_details=["Normal/Binomial/Poisson/Gamma weights", "mass conservation"],
    execution_assumptions=["cascade depth covers horizon"],
    cost_assumptions=["Cholesky heavy for long paths"],
    risk_assumptions=["simulation != forecast without MC aggregation"],
    evidence_level="B",
    reproducibility="MQL5 simulation engine + validation hooks",
    lookahead_or_leakage_risks=["fitted on same sample being validated"],
    transferable_mechanism="Generative vol paths for stress scenarios (research), not live MIS labels.",
    qmx_overlap="Offline stress corpora for regime training.",
    qmx_possible_gap="No generative vol scenario tool in MIS pipeline.",
    testable_hypotheses=["Synthetic MMAR kurtosis matches EURUSD M5 within 10%"],
    confidence=0.7,
    supporting_excerpts=[
        "engine constructs complete synthetic price paths through three stages: The Multiplicative Cascade",
    ],
))

recs.append(R(
    article_id=22537,
    title="Beyond GARCH (Part VII): Monte Carlo Volatility Forecasting in MQL5",
    publication_date="2026-07-01T13:08Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["Monte Carlo vol forecast", "confidence intervals", "adaptive cascade depth"],
    market_mechanisms=["distributional forecast from many MMAR paths"],
    asset_or_venue_dependencies=["EURUSD"],
    time_horizons=["forecast horizon with adaptive cascade depth b^k"],
    data_requirements=["fitted MMAR params", "N simulations"],
    central_claims=[
        "Single path useless for forecast; MC aggregates to point vol + uncertainty.",
        "Adaptive cascade depth balances resolution vs cost; robust to individual sim failures.",
    ],
    formulas=["vol stats across paths", "CI from quantiles"],
    algorithms=["CMonteCarlo"],
    implementation_details=["failure-tolerant loop", "forecast statistics"],
    execution_assumptions=["N sims large enough for stable quantiles"],
    cost_assumptions=["N * path cost"],
    risk_assumptions=["CI miscalibration if model misspecified"],
    evidence_level="B",
    reproducibility="MQL5 MC module + pipeline runner",
    lookahead_or_leakage_risks=["params fit in-sample then MC on same regime"],
    transferable_mechanism="Vol forecast as distribution — MIS can carry level + uncertainty, still not size.",
    qmx_overlap="Confidence on elevated/stressed labels.",
    qmx_possible_gap="MIS scores are class probs, not vol forecast CIs.",
    testable_hypotheses=["MC 80% CI coverage of next-horizon RV near 80% OOS"],
    confidence=0.72,
    supporting_excerpts=[
        "To produce a volatility forecast — a point estimate with uncertainty bounds — we need to run the simulation engine many times",
    ],
))

recs.append(R(
    article_id=22539,
    title="Beyond GARCH (Part VIII): The MMAR Library And Putting it to Work in an Expert Advisor",
    publication_date="2026-07-13T11:41Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["CMMAR facade", "EA integration", "fit/forecast API"],
    market_mechanisms=["packaged multifractal vol forecast for EA decisions"],
    asset_or_venue_dependencies=["EURUSD demo EA"],
    time_horizons=["rolling refit e.g. daily suggested"],
    data_requirements=["returns window for Fit()"],
    central_claims=[
        "Facade: configure/fit/forecast over partition+spectrum+sim+MC.",
        "Author suggests using CI width for position sizing — Book layer, not MIS.",
    ],
    formulas=["facade Forecast() wraps MC stats"],
    algorithms=["CMMAR", "demo EA"],
    implementation_details=["ALGLIB-only deps", "three-call API"],
    execution_assumptions=["periodic refit"],
    cost_assumptions=["fit+MC per refresh"],
    risk_assumptions=["authors explicitly propose sizing from CI — conflicts with QMX MIS rule"],
    evidence_level="C",
    reproducibility="Library + demo EA; live PnL not a controlled study",
    lookahead_or_leakage_risks=["refit cadence vs trade timing"],
    transferable_mechanism="Clean Fit/Forecast API pattern for a future MIS vol producer (labels only).",
    qmx_overlap="API shape for vol coordinate producer.",
    qmx_possible_gap="Must strip sizing advice; MIS may carry vol, must not size.",
    testable_hypotheses=["Rolling MMAR forecast rank-IC with next RV on EURUSD"],
    confidence=0.7,
    supporting_excerpts=[
        "Use the forecast confidence interval to dynamically adjust lot sizes",
        "three-call API: configure, fit, forecast",
    ],
))

# --- Microstructure / realized / regimes ---
recs.append(R(
    article_id=22638,
    title="Market Microstructure in MQL5 (Part 4): Volatility That Remembers",
    publication_date="2026-06-05T10:59Z",
    authors=["Max Brown"],
    topics=["realized vol", "FIGARCH proxy", "GJR leverage", "bipower jumps", "MFDFA Delta-alpha", "vol clustering"],
    market_mechanisms=["clustering", "persistence", "asymmetry", "regime mixing", "jumps"],
    asset_or_venue_dependencies=["NQ E-mini Nasdaq 100 futures CME Globex M1; NY session [14:30,21:00) UTC; not US100 CFD"],
    time_horizons=["M1 intraday; 514 NY sessions May 2024–May 2026"],
    data_requirements=["M1 closes", "session filter", "GPH d from prior part", "optional Dube GJR lib"],
    central_claims=[
        "ATR/stdev ignore clustering, persistence, asymmetry, multifractal mixing.",
        "Suite: RealizedVolatility, DurationVolatility, FractionalVolatility, FIGARCH-inspired power-law weighted RV, clustering index, GJR leverage ratio gamma/(a+g+b), bipower jump intensity, MFDFA Delta-alpha with R2.",
        "FIGARCHVolatility is NOT fitted FIGARCH — engineering proxy using GPH d.",
        "On 514 NQ sessions: vol estimators corr>0.97; mean jump intensity 1.4%; median Delta-alpha 0.875; clustering FALLS in acute stress; leverage can invert in tariff shock.",
        "Practical thresholds table for filter/sizing — sizing is Book, not MIS.",
    ],
    formulas=[
        "GJR: sigma2=w+a*e2+g*I*e2+b*sigma2; leverage=g/(a+g+b)",
        "BPV=(pi/2)*mean(|r_t||r_{t-1}|); jump if r2 > k^2 * BPV",
        "Delta-alpha = max alpha - min alpha from Legendre of MFDFA",
        "FIGARCH proxy: power-law weighted realized var using d",
    ],
    algorithms=["PopulateVolatilityAnalysis", "MultifractalSpectrum", "LeverageEffect USE_GJR_LEVERAGE"],
    implementation_details=["MicroStructure_Foundation.mqh", "outlier |r|>=0.1 filter", "SSRN companion papers"],
    execution_assumptions=["NY session bars>=300", "R2>=0.65 for Delta-alpha trust"],
    cost_assumptions=["GJR fit per window heavier than RV"],
    risk_assumptions=["thresholds NQ-specific heuristics", "proxy leverage != fitted GJR in Python tables"],
    evidence_level="A",
    reproducibility="514-session tables + code; clear venue (NQ futures)",
    lookahead_or_leakage_risks=["session labels of stress episodes are ex-post macro narrative", "winsorization after seeing extremes"],
    transferable_mechanism="Rich vol-state vector (level, memory, clustering, leverage, jumps, mixing) ideal as MIS coordinates — explicitly separate from position sizing.",
    qmx_overlap="Closest corpus match to MIS vol coordinate design; quiet|normal|elevated|stressed can consume these.",
    qmx_possible_gap="V1 lacks realized/clustering/leverage/jump/Delta-alpha producers; SQS is spread-only.",
    testable_hypotheses=[
        "Clustering index <0.08 predicts weaker next-bar |r| forecastability on NQ",
        "Jump intensity >2.1% coincides with feed/gap degraded-sensor flags",
        "Delta-alpha uncorrelated with RV (replication)",
    ],
    confidence=0.9,
    supporting_excerpts=[
        "FIGARCHVolatility() is not a fitted FIGARCH model",
        "clustering index is lower during acute stress regimes",
        "pairwise correlations above 0.97",
        "mean jump intensity of 1.4%",
    ],
))

recs.append(R(
    article_id=16960,
    title="Creating volatility forecast indicator using Python",
    publication_date="2025-10-13T12:37Z",
    authors=["Yevgeniy Koshtenko"],
    topics=["ML vol forecast", "extreme-vol classifier", "Python-MT5"],
    market_mechanisms=["vol surge warning as practical target vs point forecast"],
    asset_or_venue_dependencies=["EURUSD/GBPUSD/USDJPY/crypto mentioned; MT5+Python"],
    time_horizons=["indicator horizon for future extreme vol"],
    data_requirements=["MT5 rates", "feature pipeline", "train/test split"],
    central_claims=[
        "Point regression less useful than high-vol classifier.",
        "Author claims ~70% accuracy and ~2/3 of significant moves captured.",
        "Purpose: warn to adjust strategy/stops — filter/trigger adjacent, not MIS sizing.",
    ],
    formulas=["binary/high-vol label from future realized vol threshold"],
    algorithms=["VolatilityProcessor", "ML classifier", "extreme vol indicator"],
    implementation_details=["Python model + MT5 indicator bridge"],
    execution_assumptions=["stable feature defs", "enough history"],
    cost_assumptions=["offline train; light infer"],
    risk_assumptions=["accuracy claims may be in-sample optimistic"],
    evidence_level="C",
    reproducibility="Attached files; metrics not fully audited OOS protocol",
    lookahead_or_leakage_risks=["label uses future vol — must shift carefully; risk of leakage if features aligned wrong"],
    transferable_mechanism="Reformulate vol forecast as P(elevated/stressed) — aligns with MIS multiclass.",
    qmx_overlap="Direct analogy to regime_classifier_v1 elevated|stressed.",
    qmx_possible_gap="Need leak-free label protocol like 23488; author metrics insufficient alone.",
    testable_hypotheses=["High-vol classifier AUC >0.65 OOS on EURUSD M15 with purged CV"],
    confidence=0.62,
    supporting_excerpts=[
        "achieves forecast accuracy of approximately 70%",
        "what is more important is not the exact value of future volatility, but a timely warning about its potential surge",
    ],
))
recs[-1]["reproducibility"] = "Attached files; metrics not a fully audited OOS protocol"

recs.append(R(
    article_id=23488,
    title="Porting the Canonical Catch22 Time-Series Feature Set and Testing It on Volatility Regimes",
    publication_date="2026-08-05T12:47Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["catch22", "volatility regimes", "leak-free ablation", "feature validation"],
    market_mechanisms=["canonical TS features add orthogonal info for vol-regime classification"],
    asset_or_venue_dependencies=["EURUSD FX"],
    time_horizons=["windowed features; tercile regime labels"],
    data_requirements=["price series", "pycatch22 reference", "chronological splits"],
    central_claims=[
        "CCatch22 MQL5 port validated vs pycatch22 feature-by-feature.",
        "Leak-free ablation (purge/embargo/stride/train-only terciles): catch22 adds real info for vol-regime classification.",
        "Informative features != automatic strategy improvement — regime-filter EA lesson.",
    ],
    formulas=["22 catch22 features", "tercile labels from train-only vol"],
    algorithms=["CCatch22", "three-arm ablation", "regime-filter EA"],
    implementation_details=["ALGLIB FFT", "validate_catch22.py"],
    execution_assumptions=["non-overlapping stride", "embargo"],
    cost_assumptions=["feature compute modest"],
    risk_assumptions=["strategy coupling failure modes"],
    evidence_level="A",
    reproducibility="Validated port + explicit leak-free protocol",
    lookahead_or_leakage_risks=["explicitly mitigated; still risk if labels redefine OOS"],
    transferable_mechanism="Gold-standard evaluation template for any MIS vol/regime feature.",
    qmx_overlap="Directly relevant to regime_classifier_v1 feature ablation.",
    qmx_possible_gap="catch22 not in MIS feature set; evaluation rigor higher than many QMX notes.",
    testable_hypotheses=["Add top catch22 features to lightgbm regime model lifts macro-F1 OOS"],
    confidence=0.88,
    supporting_excerpts=[
        "catch22 adds real, orthogonal information on top of classic indicators for volatility-regime classification",
        "an informative feature does not automatically improve an unrelated strategy",
    ],
))

recs.append(R(
    article_id=23734,
    title="Building a Gold Volatility Regime Monitor from Options Data in MQL5",
    publication_date="2026-08-31T09:29Z",
    authors=["Eugenio Gustavo Guilarte Homayden"],
    topics=["implied vol", "realized vol", "variance risk premium proxy", "gold options", "regime monitor"],
    market_mechanisms=["IV vs RV gap (VRP proxy)", "options-implied forward risk"],
    asset_or_venue_dependencies=["GLD ETF options as proxy for gold; compare to XAUUSD RV; not spot-gold options"],
    time_horizons=["30-day IV interpolated on total variance; matching RV window"],
    data_requirements=["option chain", "Black-Scholes inversion", "JSON feed", "WebRequest"],
    central_claims=[
        "IV is money-backed expectation; RV is past; ratio IV/RV is scale-free regime context.",
        "Heuristic states around ratios 1.20/1.05/0.95 for gold — configurable, not estimated.",
        "Do NOT trust vendor IV column; solve IV yourself.",
        "Use for sizing/sanity — Book layer; article is not a direction trigger.",
    ],
    formulas=[
        "BS inversion for IV",
        "total variance interpolation to 30d",
        "ratio = IV30 / RV30",
    ],
    algorithms=["gold_vrp_feed.py", "MQL5 service panel + push on regime change"],
    implementation_details=["ATM call/put average", "GitHub Actions optional refresh"],
    execution_assumptions=["GLD~XAUUSD RV spot-check ~22.6%", "WebRequest allowed"],
    cost_assumptions=["external feed latency/ops"],
    risk_assumptions=["GLD != spot gold options; BS approx; heuristics"],
    evidence_level="B",
    reproducibility="Full Python+MQL5 source; thresholds heuristic",
    lookahead_or_leakage_risks=["regime notifications are contemporaneous IV/RV — OK if no future IV"],
    transferable_mechanism="External IV-RV regime as MIS coordinate for metals — filter/context, not size.",
    qmx_overlap="Vol regime for XAU; complements price-only sensors.",
    qmx_possible_gap="No options/IV feed in V1; MIS metals blind to forward vol.",
    testable_hypotheses=["IV/RV>1.2 predicts next-week RV expansion on XAUUSD more than ATR alone"],
    confidence=0.8,
    supporting_excerpts=[
        "Realized volatility is what gold did. Implied volatility is what the market is charging for what gold might do",
        "The field is unreliable",
        "What you get is not a buy or sell signal but a reliable, money-backed second opinion",
    ],
))
recs[-1]["reproducibility"] = "Full Python+MQL5 source; thresholds heuristic"

recs.append(R(
    article_id=23385,
    title="From Option Chain to 3D Volatility Surface in MetaTrader 5",
    publication_date="2026-07-16T12:04Z",
    authors=["Muhammad Minhas Qamar"],
    topics=["implied vol surface", "Black-Scholes", "DirectX 3D", "skew/term structure"],
    market_mechanisms=["vol smile/skew", "term structure of IV"],
    asset_or_venue_dependencies=["MT5 option symbols with strikes/expiries; equity/FX options where broker provides"],
    time_horizons=["across expiries on surface grid"],
    data_requirements=["option chain OHLC/greeks fields", "rates/dividends assumptions"],
    central_claims=[
        "Build live 3D IV surface from MT5 option chain via BS inversion + DirectX.",
        "Surface encodes fear/skew beyond single ATM IV.",
    ],
    formulas=["BS price", "Newton-Raphson + bisection IV", "Abramowitz-Stegun CDF"],
    algorithms=["surface grid", "CSV or native options feed", "DirectX render"],
    implementation_details=["stateless BS core", "deep ITM/OTM vega collapse handling"],
    execution_assumptions=["broker option chain completeness"],
    cost_assumptions=["per-tick surface rebuild"],
    risk_assumptions=["model IV != local-vol/stochastic-vol; sparse strikes"],
    evidence_level="B",
    reproducibility="Tooling code; depends on broker option availability",
    lookahead_or_leakage_risks=["none for live surface; historical backfill may use settlement quirks"],
    transferable_mechanism="Skew/term features as richer vol state than scalar ATR.",
    qmx_overlap="Optional IV surface features for assets with options.",
    qmx_possible_gap="No option-chain ingestion in QMX.",
    testable_hypotheses=["25d RR skew predicts next-day RV asymmetry better than GJR gamma alone"],
    confidence=0.75,
    supporting_excerpts=[
        "the shape of the smile is where the market hides its fear",
        "robust implied-volatility inversion that combines fast Newton-Raphson with a bisection fallback",
    ],
))
recs[-1]["reproducibility"] = "Tooling code; depends on broker option availability"

recs.append(R(
    article_id=15841,
    title="Gain An Edge Over Any Market (Part IV): CBOE Euro And Gold Volatility Indexes",
    publication_date="2024-09-23T13:54Z",
    authors=["Gamuchirai Zororo Ndawana"],
    topics=["EVZ", "GVZ", "CBOE vol indexes", "alt data", "ONNX"],
    market_mechanisms=["index-level implied vol as exogenous predictor"],
    asset_or_venue_dependencies=["FRED CBOE Euro & Gold vol indexes; XAUEUR / related MT5 symbols"],
    time_horizons=["daily FRED series"],
    data_requirements=["FRED API", "MT5 OHLC", "ML pipeline"],
    central_claims=[
        "Adding CBOE EVZ/GVZ may improve ML accuracy vs price-only.",
        "Correlation of alt vol indexes to MT5 prices near 0 individually; 0.4 between indexes.",
    ],
    formulas=["feature importance / model comparison across OHLC vs OHLC+CBOE"],
    algorithms=["fetch FRED", "EDA", "model+ONNX export"],
    implementation_details=["attached FetchData scripts"],
    execution_assumptions=["daily alignment; missing FRED values handled"],
    cost_assumptions=["external data dependency"],
    risk_assumptions=["weak pairwise corr; overfitting risk"],
    evidence_level="C",
    reproducibility="Scripts attached; success not guaranteed by author",
    lookahead_or_leakage_risks=["FRED revision/vintage; alignment timezone"],
    transferable_mechanism="Macro IV indexes as exogenous MIS features for FX/gold.",
    qmx_overlap="Alt-data vol for metals/FX regimes.",
    qmx_possible_gap="No FRED/CBOE ingestion.",
    testable_hypotheses=["GVZ changes Granger-cause XAUUSD RV"],
    confidence=0.6,
    supporting_excerpts=[
        "virtue in including the FRED CBOE Volatility Indexes",
        "correlation levels not significantly far from 0",
    ],
))
recs[-1]["reproducibility"] = "Scripts attached; author does not guarantee consistent success"

# --- Entropy / adaptive / pullback regimes ---
recs.append(R(
    article_id=22220,
    title="Integrating MQL5 with Data Processing Packages (Part 9): Entropy-Based Adaptive Volatility Filtering and Position Sizing",
    publication_date="2026-05-19T11:21Z",
    authors=["Hlomohang John Borotho"],
    topics=["Shannon entropy", "adaptive vol regimes", "NN direction", "risk multipliers"],
    market_mechanisms=["tick-level disorder => regime", "adaptive stops/size"],
    asset_or_venue_dependencies=["XAUUSD"],
    time_horizons=["tick windows; four vol states"],
    data_requirements=["ticks", "Flask server", "trained NN"],
    central_claims=[
        "Entropy features + NN + four-state vol regime detector drive adaptive risk multipliers.",
        "Vol used as filter AND sizing — sizing is Book, not MIS.",
    ],
    formulas=["Shannon entropy on tick returns/signs", "regime->risk multiplier map"],
    algorithms=["feature pipeline", "Flask inference", "EA lifecycle"],
    implementation_details=["Python+MT5 bridge"],
    execution_assumptions=["server availability", "tick quality"],
    cost_assumptions=["infra for Flask"],
    risk_assumptions=["coupled signal+size hard to attribute"],
    evidence_level="C",
    reproducibility="Project code path described; production claims strong",
    lookahead_or_leakage_risks=["NN train leakage if random split on ticks"],
    transferable_mechanism="Four-state vol regime from entropy — MIS-like labels; strip sizing.",
    qmx_overlap="Four-state mapping parallels quiet|normal|elevated|stressed.",
    qmx_possible_gap="No entropy tick feature; no external inference sensor.",
    testable_hypotheses=["Entropy regime changes lead ATR regime changes on XAUUSD"],
    confidence=0.64,
    supporting_excerpts=[
        "volatility regime detector continuously classifies market conditions into four distinct states",
        "adaptive risk management that scales position size and stop distances",
    ],
))
recs[-1]["reproducibility"] = "Project described end-to-end; strong production claims need independent verify"

recs.append(R(
    article_id=22807,
    title="Swing Extremes and Pullbacks (Part 4): Dynamic Pullback Depth Using Volatility Models",
    publication_date="2026-06-16T10:38Z",
    authors=["Hlomohang John Borotho"],
    topics=["ATR regimes", "pullback depth", "dual ATR", "structure trading"],
    market_mechanisms=["acceptable pullback depth depends on vol state"],
    asset_or_venue_dependencies=["equity-style examples; MT5 symbols general"],
    time_horizons=["swing legs; fast ATR vs rolling ATR"],
    data_requirements=["OHLC", "dual ATR handles"],
    central_claims=[
        "Fixed pullback % fails across vol regimes.",
        "Dual ATR => four vol states widen/tighten depth thresholds; SL ATR-anchored.",
        "Vol as filter/trigger gate for structure entries; also stop geometry (Book).",
    ],
    formulas=["retracement ratio", "depth score 0-10", "ATR multiples for stops"],
    algorithms=["Layer 2.5 pullback intelligence", "bias engine"],
    implementation_details=["state machine rebuild"],
    execution_assumptions=["confirmed swings"],
    cost_assumptions=["light"],
    risk_assumptions=["overfit depth thresholds"],
    evidence_level="C",
    reproducibility="EA implementation + backtest section",
    lookahead_or_leakage_risks=["swing confirmation delay vs entry"],
    transferable_mechanism="Vol-state-conditioned geometry thresholds as filters.",
    qmx_overlap="Elevated/stressed should widen structure tolerances — filter policy, not MIS size.",
    qmx_possible_gap="No pullback-depth policy tied to MIS labels.",
    testable_hypotheses=["Vol-conditioned depth cutoffs reduce false pullback entries vs fixed 40%"],
    confidence=0.7,
    supporting_excerpts=[
        "four distinct volatility states that dynamically widen or tighten acceptable depth thresholds",
        "Entries are no longer triggered by price returning to a zone—they require the correction to be statistically appropriate for the current volatility environment",
    ],
))
recs[-1]["reproducibility"] = "EA implementation + backtest section"

# --- ATR / breakout / Chaikin / multi-symbol ---
recs.append(R(
    article_id=10748,
    title="Learn how to design a trading system by ATR",
    publication_date="2022-05-05T15:10Z",
    authors=["Mohamed Abdelmaaboud"],
    topics=["ATR", "True Range", "SL/TP", "vol strength"],
    market_mechanisms=["True Range captures gaps/intra-bar; ATR smooths"],
    asset_or_venue_dependencies=["EURUSD examples; FX general"],
    time_horizons=["ATR period N bars"],
    data_requirements=["OHLC"],
    central_claims=[
        "ATR measures volatility not direction.",
        "Strategies: ATR strength, movement, SL/TP placement.",
    ],
    formulas=["TR = max(H-L, |H-Cprev|, |L-Cprev|)", "ATR = MA(TR,n)"],
    algorithms=["simple ATR EAs / blueprints"],
    implementation_details=["MQL5 educational systems"],
    execution_assumptions=["enough bars for ATR"],
    cost_assumptions=["none"],
    risk_assumptions=["ATR lag in shocks"],
    evidence_level="D",
    reproducibility="Educational code; no rigorous edge test",
    lookahead_or_leakage_risks=["low"],
    transferable_mechanism="ATR as baseline realized-range vol coordinate.",
    qmx_overlap="Simple vol level feature.",
    qmx_possible_gap="ATR alone insufficient for regime; need clustering/asymmetry.",
    testable_hypotheses=["ATR percentile ranks map to quiet|normal|elevated"],
    confidence=0.7,
    supporting_excerpts=[
        "one of the most popular tools is the Average True Range (ATR)",
        "Simple ATR - SL & TP levels strategies",
    ],
))

recs.append(R(
    article_id=16213,
    title="MQL5 Wizard Techniques you should know (Part 44): Average True Range (ATR) technical indicator",
    publication_date="2024-10-25T09:50Z",
    authors=["Stephen Njuki"],
    topics=["ATR", "vol breakout", "ATR bands", "wizard signals", "sizing mention"],
    market_mechanisms=["ATR as FX proxy for volume", "contraction/expansion cycles"],
    asset_or_venue_dependencies=["forex-oriented"],
    time_horizons=["ATR period; breakout confirmation bars"],
    data_requirements=["OHLC", "wizard signal classes"],
    central_claims=[
        "ATR used for filter, breakout trigger, exit, contraction signal, bands.",
        "Also historically used to guide position sizing — Book not MIS.",
    ],
    formulas=["ATR", "ATR channel bands", "threshold breakout rules"],
    algorithms=["wizard signal ideas (many not coded)"],
    implementation_details=["conceptual patterns; reader to implement"],
    execution_assumptions=["wizard EA pipeline"],
    cost_assumptions=["n/a"],
    risk_assumptions=["untested ideas in article"],
    evidence_level="D",
    reproducibility="Ideas not fully coded/tested in-article",
    lookahead_or_leakage_risks=["depends on implementation"],
    transferable_mechanism="Menu of ATR roles: filter vs trigger vs (Book) sizing.",
    qmx_overlap="Clarifies ATR role separation needed in QMX.",
    qmx_possible_gap="MIS must pick filter-only ATR features.",
    testable_hypotheses=["ATR contraction then expansion predicts breakout continuation OOS"],
    confidence=0.55,
    supporting_excerpts=[
        "not just for filtering entry signals but also in guiding on position sizing",
        "Volatility Breakout Signal",
    ],
))
recs[-1]["reproducibility"] = "Ideas not fully coded/tested in-article"

recs.append(R(
    article_id=752,
    title="MQL5 Cookbook: Developing a Multi-Symbol Volatility Indicator in MQL5",
    publication_date="2014-01-06T10:34Z",
    authors=["Anatoli Kazharski"],
    topics=["multi-symbol ATR", "sync issues", "cross-asset vol panel"],
    market_mechanisms=["compare vol across symbols for relative risk"],
    asset_or_venue_dependencies=["multi FX symbols e.g. AUDUSD/GBPUSD"],
    time_horizons=["per-symbol ATR period"],
    data_requirements=["synchronized multi-symbol history"],
    central_claims=[
        "Multi-symbol ATR indicator teaching sync/true-bar start issues.",
        "Foundation for later vol-analyzing trading systems.",
    ],
    formulas=["per-symbol ATR"],
    algorithms=["multi-symbol buffer sync"],
    implementation_details=["multisymbolatr.mq5"],
    execution_assumptions=["broker history aligned"],
    cost_assumptions=["CopyRates per symbol"],
    risk_assumptions=["desync false vol"],
    evidence_level="D",
    reproducibility="Source attached",
    lookahead_or_leakage_risks=["sync bugs can look like future bars"],
    transferable_mechanism="Cross-sectional vol ranking as MIS relative coordinate.",
    qmx_overlap="Multi-pair relative vol state.",
    qmx_possible_gap="No cross-symbol vol panel in MIS.",
    testable_hypotheses=["Relative ATR rank predicts which pair hits elevated first"],
    confidence=0.65,
    supporting_excerpts=[
        "development of a multi-symbol volatility indicator",
        "synchronization of other symbols' data with respect to the current symbol",
    ],
))
recs[-1]["reproducibility"] = "Source attached"

recs.append(R(
    article_id=14775,
    title="How to build and optimize a volatility-based trading system (Chaikin Volatility - CHV)",
    publication_date="2024-04-25T13:32Z",
    authors=["Mohamed Abdelmaaboud"],
    topics=["Chaikin Volatility", "EMA of HL range", "vol expansion signals"],
    market_mechanisms=["ROC of smoothed high-low range"],
    asset_or_venue_dependencies=["EURUSD examples"],
    time_horizons=["CHV periods + optional MA filter"],
    data_requirements=["OHLC"],
    central_claims=[
        "CHV measures volatility via change in smoothed range.",
        "Simple strategies + MA optimization for entries.",
    ],
    formulas=["CHV = ROC(EMA(High-Low, n), m)"],
    algorithms=["custom CHV indicator", "strategy EAs"],
    implementation_details=["MQL5 CHV + optimizable EA"],
    execution_assumptions=["enough history"],
    cost_assumptions=["none"],
    risk_assumptions=["vol expansion != direction"],
    evidence_level="D",
    reproducibility="Code + simple tests",
    lookahead_or_leakage_risks=["optimizer overfitting"],
    transferable_mechanism="Range-expansion oscillator as elevated trigger/filter feature.",
    qmx_overlap="Alternate vol estimator vs ATR.",
    qmx_possible_gap="No CHV-like range-ROC feature.",
    testable_hypotheses=["CHV spikes lead ATR spikes on FX M15"],
    confidence=0.6,
    supporting_excerpts=[
        "volatility factor is very important",
        "Chaikin Volatility (CHV)",
    ],
))
recs[-1]["reproducibility"] = "Code + simple tests"

recs.append(R(
    article_id=19459,
    title="Developing a Volatility Based Breakout System",
    publication_date="2025-09-22T11:00Z",
    authors=["Hlomohang John Borotho"],
    topics=["ATR breakout", "session range", "false breakout filter"],
    market_mechanisms=["vol stops distinguish genuine vs false breakouts"],
    asset_or_venue_dependencies=["session-based FX/CFD charts"],
    time_horizons=["daily sessions", "ATR vol stop"],
    data_requirements=["session H/L", "ATR"],
    central_claims=[
        "Static breakouts fail in low vol/noise; ATR vol analysis filters.",
        "Includes position sizing/trailing — Book layer.",
    ],
    formulas=["session range", "ATR vol stop", "breakout beyond range+vol buffer"],
    algorithms=["session detect", "breakout EA"],
    implementation_details=["visual session markers"],
    execution_assumptions=["session definitions correct for symbol"],
    cost_assumptions=["spreads matter at breakout"],
    risk_assumptions=["session TZ errors"],
    evidence_level="C",
    reproducibility="Backtest results in article",
    lookahead_or_leakage_risks=["session high/low must use completed session only"],
    transferable_mechanism="Vol-buffered breakout as trigger; vol state as filter.",
    qmx_overlap="Elevated vol may increase false breakouts — MIS filter for breakout bots.",
    qmx_possible_gap="No session-vol breakout quality feature.",
    testable_hypotheses=["ATR-buffered breakouts higher precision than raw range breakouts"],
    confidence=0.66,
    supporting_excerpts=[
        "false breakouts often occur in low-volatility environments",
        "volatility analysis using ATR",
    ],
))
recs[-1]["reproducibility"] = "Backtest results in article"

recs.append(R(
    article_id=20745,
    title="Larry Williams Market Secrets (Part 5): Automating the Volatility Breakout Strategy in MQL5",
    publication_date="2026-01-16T07:48Z",
    authors=["Chacha Ian Maroa"],
    topics=["Larry Williams", "range expansion breakout", "ATR/risk"],
    market_mechanisms=["abnormal range expansion births trends"],
    asset_or_venue_dependencies=["XAUUSD/gold demos; commodities/equity mentioned"],
    time_horizons=["prior period range => next period breakout levels"],
    data_requirements=["OHLC period ranges"],
    central_claims=[
        "Volatility breakouts (range expansion) as entry triggers with disciplined risk.",
        "Fully coded EA + backtests.",
    ],
    formulas=["entry = prior close/open +/- k * prior range", "risk geometry"],
    algorithms=["period detect", "breakout EA"],
    implementation_details=["MQL5 EA step-by-step"],
    execution_assumptions=["period boundaries clear (D1/session)"],
    cost_assumptions=["slippage on breakout"],
    risk_assumptions=["whipsaw if expansion mean-reverts"],
    evidence_level="C",
    reproducibility="EA + backtests",
    lookahead_or_leakage_risks=["must use prior completed period range only"],
    transferable_mechanism="Range-expansion trigger; MIS elevated may enable/disable.",
    qmx_overlap="Trigger family gated by MIS vol state.",
    qmx_possible_gap="No range-expansion event sensor in V1 (gap-event exists but different).",
    testable_hypotheses=["Williams vol breakout expectancy >0 on XAUUSD D1 after costs"],
    confidence=0.68,
    supporting_excerpts=[
        "sustained price moves are usually born from moments of extreme volatility",
        "abnormal range expansion often marks the birth of meaningful market moves",
    ],
))

recs.append(R(
    article_id=20862,
    title="Larry Williams Market Secrets (Part 6): Measuring Volatility Breakouts Using Market Swings",
    publication_date="2026-01-22T10:17Z",
    authors=["Chacha Ian Maroa"],
    topics=["swing-based vol", "alternate range measure", "breakout"],
    market_mechanisms=["dominant swing range as vol proxy vs prior bar range"],
    asset_or_venue_dependencies=["XAUUSD/gold; forex/equity/options mentioned"],
    time_horizons=["swing legs across periods"],
    data_requirements=["swing detection", "OHLC"],
    central_claims=[
        "Swing-measured volatility is an alternate expansion gauge to last-period range.",
        "EA projects breakout entries from swing range.",
    ],
    formulas=["swing range = dominant up/down swing amplitude", "breakout = f(swing range)"],
    algorithms=["swing detect", "EA"],
    implementation_details=["step-by-step EA"],
    execution_assumptions=["swing definition unambiguous"],
    cost_assumptions=["breakout slippage"],
    risk_assumptions=["swing repaint if not confirmed"],
    evidence_level="C",
    reproducibility="EA + tests",
    lookahead_or_leakage_risks=["unconfirmed swings leak"],
    transferable_mechanism="Swing-range vol estimator as alternate to ATR/Parkinson for triggers.",
    qmx_overlap="Alternate realized-range feature.",
    qmx_possible_gap="No swing-range vol sensor.",
    testable_hypotheses=["Swing-range breakout vs ATR-range breakout Sharpe comparison on XAU"],
    confidence=0.66,
    supporting_excerpts=[
        "shift our attention to a different perspective on measuring volatility using market swings",
    ],
))

recs.append(R(
    article_id=16560,
    title="Price Action Analysis Toolkit Development (Part 5): Volatility Navigator EA",
    publication_date="2024-12-16T13:40Z",
    authors=["Christian Benjamin"],
    topics=["ATR navigator", "entry/SL/TP geometry", "analysis-only EA"],
    market_mechanisms=["vol-aware trade geometry suggestions"],
    asset_or_venue_dependencies=["any chart/TF"],
    time_horizons=["scalp short TF vs swing higher TF"],
    data_requirements=["OHLC + ATR-like measures"],
    central_claims=[
        "Tool suggests entry/SL/TP from volatility; does NOT open trades.",
        "Vol used for geometry (Book), analysis overlay.",
    ],
    formulas=["ATR-based distances for SL/TP"],
    algorithms=["Volatility Navigator EA alerts"],
    implementation_details=["notifications"],
    execution_assumptions=["user combines with own strategy"],
    cost_assumptions=["n/a"],
    risk_assumptions=["suggestions not validated edge"],
    evidence_level="D",
    reproducibility="EA code; analysis-only",
    lookahead_or_leakage_risks=["low if uses closed bars"],
    transferable_mechanism="Separates analysis vol overlay from execution — good QMX boundary example.",
    qmx_overlap="MIS as labeler not executor mirrors this stance.",
    qmx_possible_gap="n/a — reinforces MIS non-sizing rule.",
    testable_hypotheses=["Navigator SL distance correlates with next-bar TR"],
    confidence=0.58,
    supporting_excerpts=[
        "this tool does not open trades",
        "optimize these critical aspects of trading",
    ],
))

recs.append(R(
    article_id=18165,
    title="Formulating Dynamic Multi-Pair EA (Part 4): Volatility and Risk Adjustment",
    publication_date="2025-08-11T10:06Z",
    authors=["Hlomohang John Borotho"],
    topics=["multi-pair ATR", "V-Stop", "dynamic lots", "risk tiers"],
    market_mechanisms=["cross-pair vol heterogeneity requires adaptive risk"],
    asset_or_venue_dependencies=["EURUSD GBPUSD USDJPY XAUUSD multi-pair"],
    time_horizons=["ATR period; multi-symbol concurrent"],
    data_requirements=["per-symbol ATR/RSI"],
    central_claims=[
        "Fixed lots/SL fail across vol profiles.",
        "ATR+V-Stop filter entries; dynamic lots/SL; risk high/mod/low — sizing is Book.",
    ],
    formulas=["ATR-based lot = risk_budget / (ATR*mult*tick_value)", "V-Stop"],
    algorithms=["multi-symbol loop", "trailing"],
    implementation_details=["modular EA"],
    execution_assumptions=["margin for multi-pair"],
    cost_assumptions=["correlated risk underestimated"],
    risk_assumptions=["vol-scaled size still needs portfolio risk"],
    evidence_level="C",
    reproducibility="Backtests shown",
    lookahead_or_leakage_risks=["standard"],
    transferable_mechanism="Per-symbol vol risk tier as MIS label; actual lots stay in Book.",
    qmx_overlap="Multi-pair elevated/stressed relative labels.",
    qmx_possible_gap="MIS lacks per-symbol risk-tier vol output for Book consumption rules.",
    testable_hypotheses=["Vol-tiered lots reduce DD vs fixed lots multi-pair"],
    confidence=0.7,
    supporting_excerpts=[
        "strategy that performs well on EURUSD may underperform or become overly risky on GBPJPY due to their different volatility profiles",
        "dynamically adjusting lot sizes and stop losses based on real-time volatility",
    ],
))

recs.append(R(
    article_id=22338,
    title="MQL5 Wizard Techniques you should know (Part 87): Volatility-Scaled Money Management with Monotonic Queues and Radial Basis Functions",
    publication_date="2026-04-30T13:13Z",
    authors=["Stephen Njuki"],
    topics=["vol-scaled MM", "monotonic queue", "RBF gate", "inverse vol sizing"],
    market_mechanisms=["static size + lagged vol estimate fails when range expands"],
    asset_or_venue_dependencies=["Forex/equity wizard EAs"],
    time_horizons=["sliding window max/min range as vol proxy; tick/low-TF sensitive"],
    data_requirements=["high/low window", "optional RSI for RBF"],
    central_claims=[
        "scale_factor = base_vol / current_vol inverse sizing.",
        "Monotonic queue O(1) vol updates; optional RBF moderates size.",
        "Pure Book money-management — must NOT live in MIS.",
    ],
    formulas=["scale_factor = base_volatility / current_volatility", "lot clamp to step/min/max"],
    algorithms=["CMoneyMonotonicQueueRBF", "Optimize()"],
    implementation_details=["wizard custom MM class"],
    execution_assumptions=["low-latency VPS"],
    cost_assumptions=["CopyHigh/Low still latency source"],
    risk_assumptions=["inverse vol increases size in calm — crowded complacency risk"],
    evidence_level="B",
    reproducibility="Class + empirical backtests section",
    lookahead_or_leakage_risks=["window vol using incomplete bar"],
    transferable_mechanism="Demonstrates why vol sizing belongs in Book; MIS should only publish vol state.",
    qmx_overlap="Negative example for MIS scope; positive for Book MM design.",
    qmx_possible_gap="Clarify interface: MIS vol coordinate -> Book may size; MIS itself must not.",
    testable_hypotheses=["Inverse-vol MM cuts max loss vs fixed fractional in range-expansion regimes"],
    confidence=0.76,
    supporting_excerpts=[
        "position sizing is inversely adjusted by scale_factor = base_volatility / current_volatility",
        "strategies that work in backtests collapse in live when market range expands",
    ],
))
recs[-1]["reproducibility"] = "Class + empirical backtests section"

recs.append(R(
    article_id=23759,
    title="Building a Dynamic ATR-Based Trend Channel Indicator in MQL5",
    publication_date="2026-08-19T05:05Z",
    authors=["Israel Pelumi Abioye"],
    topics=["ATR channel", "trend envelope"],
    market_mechanisms=["ATR-width channel around trend"],
    asset_or_venue_dependencies=["generic MT5"],
    time_horizons=["ATR period + trend MA period"],
    data_requirements=["OHLC"],
    central_claims=["Dynamic ATR channel visualizes vol-aware trend bounds; filter/trigger aid."],
    formulas=["upper/lower = trend +/- k*ATR"],
    algorithms=["custom indicator"],
    implementation_details=["MQL5 buffers/plots"],
    execution_assumptions=["trend definition stable"],
    cost_assumptions=["light"],
    risk_assumptions=["channel whipsaw in chop"],
    evidence_level="D",
    reproducibility="Indicator code",
    lookahead_or_leakage_risks=["low"],
    transferable_mechanism="ATR envelope as visual vol state.",
    qmx_overlap="Simple elevated when price presses band.",
    qmx_possible_gap="optional band-pressure feature",
    testable_hypotheses=["Band walk duration predicts trend continuation"],
    confidence=0.55,
    supporting_excerpts=["Dynamic ATR-Based Trend Channel"],
))
# fix gap type
recs[-1]["qmx_possible_gap"] = "Optional band-pressure feature not in MIS."

recs.append(R(
    article_id=20309,
    title="Developing a Trading Strategy: The Flower Volatility Index Trend-Following Approach",
    publication_date="2025-11-24T15:09Z",
    authors=["Daniel Opoku"],
    topics=["Flower Volatility Index", "rose curves", "vol displacement"],
    market_mechanisms=["map vol/price displacement via rose-curve components"],
    asset_or_venue_dependencies=["commodity mentioned; general charts"],
    time_horizons=["indicator lookback"],
    data_requirements=["price series"],
    central_claims=[
        "FVI transforms rose-curve math into vol/trend tool.",
        "EA uses FVI for directional bias — trigger family.",
    ],
    formulas=["rose curve X/Y components mapped to price/vol"],
    algorithms=["FVI indicator", "trend-following EA"],
    implementation_details=["graphical curve rendering"],
    execution_assumptions=["params stable"],
    cost_assumptions=["n/a"],
    risk_assumptions=["novel indicator — weak prior literature"],
    evidence_level="D",
    reproducibility="Indicator+EA code",
    lookahead_or_leakage_risks=["parameter fitting risk"],
    transferable_mechanism="Exotic vol oscillator — low priority vs GARCH/RV/ATR.",
    qmx_overlap="Low; novelty vol feature.",
    qmx_possible_gap="Not needed for V1.",
    testable_hypotheses=["FVI vs ATR rank-IC on next |r|"],
    confidence=0.45,
    supporting_excerpts=[
        "Flower Volatility Index (FVI), a novel approach that transforms the mathematical elegance of Rose Curves",
    ],
))

recs.append(R(
    article_id=23226,
    title="Low-Frequency Quantitative Strategies in MetaTrader 5 (Part 4): A Volatility-Adjusted Momentum Framework",
    publication_date="2026-07-06T11:52Z",
    authors=["Jocimar Lopes"],
    topics=["ORB", "relative volume", "stocks in play", "intraday equities"],
    market_mechanisms=["news => unusual volume => imbalance => trend; ORB"],
    asset_or_venue_dependencies=["US equities; relative volume vs 14d avg; not FX"],
    time_horizons=["first 5 minutes ORB; intraday"],
    data_requirements=["US stock universe", "volume history"],
    central_claims=[
        "ORB on stocks-in-play via relative volume; Swiss Finance Institute ORB study cited.",
        "Low win rate high R:R; volatility/volume selection filter.",
    ],
    formulas=["relative volume = open5m vol / 14d avg", "ORB high/low break"],
    algorithms=["stocks-in-play filter", "ORB EA"],
    implementation_details=["main EA file", "backtests"],
    execution_assumptions=["US equity session", "borrow/liquidity"],
    cost_assumptions=["need robust capital; institutional DD profile"],
    risk_assumptions=["FX transfer poor; volume definition broker-dependent"],
    evidence_level="B",
    reproducibility="Cites SFI study; EA backtests",
    lookahead_or_leakage_risks=["universe selection bias"],
    transferable_mechanism="Volume-vol proxy as filter for breakout triggers — equity venue specific.",
    qmx_overlap="Only if QMX trades US equities; else out of scope.",
    qmx_possible_gap="Equity relative-volume sensor absent (OK if FX-only).",
    testable_hypotheses=["Relative volume>threshold improves ORB expectancy on US stocks"],
    confidence=0.72,
    supporting_excerpts=[
        "Opening Range Breakout (ORB) presented in this article is a very simple intraday system based on relative volume",
        "win rate below 30%, due to a highly favourable risk-reward ratio",
    ],
))

recs.append(R(
    article_id=23676,
    title="Beyond the Mean and Standard Deviation: A Robust Statistics Library for MQL5 Indicators",
    publication_date="2026-08-21T14:33Z",
    authors=["Adeolu Kayode Gbadebo"],
    topics=["MAD", "median", "Theil-Sen", "robust vol proxy", "breakdown point"],
    market_mechanisms=["outliers break mean/stdev-based bands; robust scale resists"],
    asset_or_venue_dependencies=["EURUSD FX examples"],
    time_horizons=["rolling windows"],
    data_requirements=["price series"],
    central_claims=[
        "Mean/stdev breakdown point 0; median/MAD/Theil-Sen high breakdown.",
        "Drop-in robust replacements for Bollinger-like vol bands.",
    ],
    formulas=["MAD = median(|x-median|)", "robust z = (x-med)/(c*MAD)", "Theil-Sen slope"],
    algorithms=["RobustStats.mqh", "comparison overlay", "breakdown demos"],
    implementation_details=["three drop-in indicators"],
    execution_assumptions=["oddities at tiny windows"],
    cost_assumptions=["median denser than mean"],
    risk_assumptions=["MAD understates jump risk if jumps are the signal"],
    evidence_level="B",
    reproducibility="Library + evidence section on breakdown",
    lookahead_or_leakage_risks=["low"],
    transferable_mechanism="Robust scale as vol coordinate resistant to bad ticks — complements jump filters.",
    qmx_overlap="Feed-state/degraded-sensors + robust vol.",
    qmx_possible_gap="MIS vol features likely mean/stdev/ATR; no MAD path.",
    testable_hypotheses=["MAD bands false-break rate < Bollinger on tick-spike days"],
    confidence=0.78,
    supporting_excerpts=[
        "Almost every statistical indicator on a MetaTrader chart is built from two numbers: the arithmetic mean and the standard deviation",
        "median and the quantities derived from it (MAD, Theil-Sen slope) have a high breakdown point",
    ],
))

recs.append(R(
    article_id=20168,
    title="Price Action Analysis Toolkit Development (Part 49): Integrating Trend, Momentum, and Volatility Indicators",
    publication_date="2025-11-07T09:33Z",
    authors=["Christian Benjamin"],
    topics=["multi-indicator dashboard", "ATR with trend/momentum"],
    market_mechanisms=["combined confirmation across families"],
    asset_or_venue_dependencies=["generic MT5"],
    time_horizons=["per selected indicators"],
    data_requirements=["multiple indicator handles"],
    central_claims=[
        "Dashboard consolidates trend/momentum/vol indicators to reduce manual attach friction.",
        "Vol as one panel among filters.",
    ],
    formulas=["depends on selected indicators (ATR etc.)"],
    algorithms=["Multi Indicator Handler EA"],
    implementation_details=["interactive dashboard"],
    execution_assumptions=["user selects set"],
    cost_assumptions=["many handles"],
    risk_assumptions=["confirmation bias / correlated indicators"],
    evidence_level="D",
    reproducibility="EA code + testing section",
    lookahead_or_leakage_risks=["low"],
    transferable_mechanism="UI pattern for vol+other MIS coordinates display.",
    qmx_overlap="Operator visibility of MIS vol with other sensors.",
    qmx_possible_gap="No unified MIS sensor dashboard requirement covered here.",
    testable_hypotheses=["Dashboard reduces operator attach time — process metric"],
    confidence=0.5,
    supporting_excerpts=[
        "managing multiple indicators efficiently within MetaTrader 5",
        "consolidates all chosen indicators into a single, interactive dashboard",
    ],
))

recs.append(R(
    article_id=18111,
    title="Implementing a Breakeven Mechanism in MQL5 (Part 2): ATR- and RRR-Based Breakeven",
    publication_date="2026-06-08T11:57Z",
    authors=[],  # filled below if needed
    topics=["ATR breakeven", "RRR", "trade management"],
    market_mechanisms=["vol-scaled breakeven distance"],
    asset_or_venue_dependencies=["generic MT5 positions"],
    time_horizons=["ATR period for BE trigger distance"],
    data_requirements=["open position", "ATR"],
    central_claims=[
        "ATR-based and RRR-based breakeven mechanisms adapt exit geometry to vol.",
        "Pure Book/execution management — not MIS.",
    ],
    formulas=["BE when profit >= k*ATR or RRR threshold"],
    algorithms=["breakeven manager module"],
    implementation_details=["Part 2 of BE series"],
    execution_assumptions=["stops allowed to modify"],
    cost_assumptions=["spread may kill tight BE"],
    risk_assumptions=["premature BE cuts runners"],
    evidence_level="D",
    reproducibility="Example code",
    lookahead_or_leakage_risks=["none"],
    transferable_mechanism="ATR as execution geometry input in Book.",
    qmx_overlap="None for MIS; Book may read ATR independently.",
    qmx_possible_gap="Keep BE out of MIS.",
    testable_hypotheses=["ATR-BE vs fixed-points BE expectancy"],
    confidence=0.55,
    supporting_excerpts=["ATR- and RRR-Based Breakeven"],
))

# author for 18111 from digest
recs[-1]["authors"] = ["Unverified in frontmatter; body credit via MQL5 page"]

# quick author fix using known from digest — actually from inventory author empty; skip

# Validate and write
assert len(recs) >= 30, len(recs)
ids = [r["article_id"] for r in recs]
assert len(ids) == len(set(ids)), [i for i in ids if ids.count(i) > 1]
prior = {17737, 23286, 22940, 16830, 15223, 23482, 23016, 10715, 23454, 21003, 14203, 19944, 9804, 23355, 22938, 22939, 15748, 19290, 18867, 1575, 21235, 16752, 9231, 22772}
assert not (set(ids) & prior), set(ids) & prior

# normalize types
for r in recs:
    for k in SCHEMA:
        if k not in r:
            raise SystemExit(f"missing {k} in {r['article_id']}")
    assert r["evidence_level"] in list("ABCDX")
    assert isinstance(r["confidence"], float)
    # authors list
    if not isinstance(r["authors"], list):
        r["authors"] = [r["authors"]]

OUT.parent.mkdir(parents=True, exist_ok=True)
with OUT.open("w", encoding="utf-8") as f:
    for r in recs:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"wrote {OUT} n={len(recs)}")
print("ids:", ",".join(str(i) for i in ids))
