"""Monte Carlo candle-perturbation — the alternate-history B-14 rung (Story 22.3).

The second ladder procedure (22.3) re-runs the backtest across resampled market
paths generated by a **real-seeded moving-block bootstrap of OHLC deltas**, so the
operator can see how the strategy holds up under alternate but short-horizon-
consistent market histories (not merely a re-order of realised trades, as
22.2 does).

What the procedure is:

* a **pure library function** (:func:`run_candle_perturbation`) under the B-14
  contract — it consumes a ``world = replay`` run's real historical candles,
  RETURNS its result, and writes no log and no ledger line (the Epic 15
  orchestrator owns every append). Unlike the trade-shuffle rung it **does** mint a
  synthetic market series, but that series is **procedure-ephemeral**: it is never
  persisted into a data room, so the run stays ``world = replay`` and its provenance
  is ``procedure-ephemeral`` (B-7; AC1, AC2);
* a **moving-block bootstrap of exact-integer OHLC delta tuples** (AC1): each candle
  is reduced to the exact-integer offsets ``(open, high, low, close) - anchor`` from
  its anchor price (the previous close; the seed price for the first candle). A
  scenario resamples overlapping length-``L`` blocks of those delta tuples, then
  **cumulative-sums** them back onto the seed price with exact-integer money math
  (AD-7). Because a whole delta tuple is a rigid translation, each rebuilt candle
  keeps its internal shape; the rebuild additionally **enforces high/low bounds** and
  shifts any candle whose low would fall to or below zero so the series is always
  valid and **strictly positive**. **Scenario 0 is the true history** — it bypasses
  resampling and returns the real candles verbatim;
* the **block length is a UI-editable configurable with no ratified value** (SC-07,
  AC1): it resolves from the run-config's ``qmb_mc_candle_perturbation_block_length``
  key or an explicit argument; unset, it is a typed ``invalid input`` refusal, never
  a silently-applied default. The scenario count is likewise configurable;
* **per-scenario reproducibility** (AR-59; NFR-03; AC4): scenario ``s`` resamples
  with a fresh :class:`random.Random` seeded ``base_seed + s`` — no module-global
  RNG — and the result records the RNG family, seed-derivation rule, block length,
  scenario count, resampling scheme, and data-window UTC-ns bounds. Re-running the
  same inputs reproduces the result fingerprint bit-for-bit, or refuses;
* the **persistence law** (B-7, GAP-0048; AC2, AC3): the ephemeral perturbation
  stays ``world = replay`` and its claim class is robustness-only. A config that
  instead requests **persisting** the synthetic series compiles to ``world =
  simulated`` and is a typed ``policy rejection`` for governed evidence — it cannot
  ledger into the bar's store until GAP-0048 closes (SC-06). A config binding a
  ``replay`` clock to synthetic-tainted persisted data is a typed ``invalid input``
  (B-2/B-7 wins, FM-3, DEC-0164);
* the **governed fan-out** (B-5, AR-50, AR-51; AC5): scenarios fan out under the
  orchestrator's process-per-run governor bounded by ``min(cpu, memory)`` with
  enqueue-when-full and a cancel token — no Ray, no daemon, no required Docker. The
  orchestrator appends exactly one ``role = replicate`` ledger line per scenario with
  the objective measure, never a bar verdict (B-4);
* the **distribution summary** (AC6): the per-scenario objective measure is
  summarised with the Story 22.1 primitive — percentiles, confidence bands, and the
  direction-aware empirical percentile rank of the true result within the
  alternate-history distribution — as chart series data, never a verdict. The claim
  class is robustness (alternate-history), never edge (L20), and the result cannot
  gate live money.
"""

from __future__ import annotations

import random
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from fractions import Fraction
from typing import Final, cast

from qmf.core.chrono import Instant
from qmf.core.exact import ExactRational, Money, UnitKind
from qmf.core.fingerprint import Fingerprint, World, fingerprint
from qmf.core.refusal import Ok, Result, TypedRefusal, is_refusal

from qmb._refuse import clean_token, invalid, policy
from qmb.config.compiler import (
    CLOCK_REPLAY,
    CLOCK_SIMULATED,
    PROVENANCE_PROCEDURE_EPHEMERAL,
    PROVENANCE_SYNTHETIC_TAINTED,
)
from qmb.ledger.line import ROLE_REPLICATE
from qmb.orchestrator.governor import GovernedRequest
from qmb.results.charts import HistogramReadyArray
from qmb.robustness.contract import (
    CLAIM_CLASS_ROBUSTNESS,
    CLAIM_GATED_BEHIND,
    PROCEDURE_MC_CANDLE_PERTURBATION,
    THRESHOLDS_DEFERRED_TO,
    require_positive_int,
)
from qmb.robustness.shuffle import RNG_FAMILY, SEED_DERIVATION_RULE
from qmb.robustness.summary import (
    DIRECTION_HIGHER_IS_BETTER,
    DIRECTION_LOWER_IS_BETTER,
    DistributionSummary,
    summarize_distribution,
)

__all__ = [
    "BLOCK_LENGTH_HAS_RATIFIED_VALUE",
    "BLOCK_LENGTH_KEY",
    "CANDLE_PERTURBATION_PROCEDURE",
    "MINIMUM_POSITIVE_PRICE",
    "PERTURBATION_CANONICAL_PAYLOAD",
    "PERTURBATION_CLAIM_CLASS",
    "PERTURBATION_EMITS_IMAGE_PAYLOAD",
    "PERTURBATION_EMITS_VERDICT",
    "PERTURBATION_MAKES_EDGE_CLAIM",
    "PERTURBATION_MINTS_SYNTHETIC_SERIES",
    "PERTURBATION_MODE",
    "PERTURBATION_PERSISTS_SYNTHETIC_SERIES",
    "PERTURBATION_PROVENANCE_KIND",
    "PERTURBATION_RESULT_CLASS",
    "PERTURBATION_RESULT_FORMAT_VERSION",
    "PERTURBATION_SCENARIO_COUNT_KEY",
    "PERTURBATION_VERDICT_DEFERRED_TO",
    "RESAMPLING_SCHEME",
    "SCENARIO_ZERO_IS_TRUE_HISTORY",
    "WORLD_WHEN_EPHEMERAL",
    "WORLD_WHEN_PERSISTED",
    "AlternateHistoryDistribution",
    "Candle",
    "CandlePerturbationResult",
    "OHLCDelta",
    "PerturbationPersistence",
    "PerturbationProvenance",
    "PerturbationScenario",
    "SyntheticCandleSeries",
    "governed_perturbation_requests",
    "ohlc_deltas",
    "perturbation_identity",
    "perturbation_persistence",
    "perturbation_scenarios",
    "refuse_persisted_synthetic_series",
    "refuse_perturbation_bar_verdict",
    "refuse_replay_clock_on_synthetic_persisted",
    "run_candle_perturbation",
    "summarize_perturbation_objective",
]

# The B-14 rung this module realizes and the alternate-history mode it runs in.
CANDLE_PERTURBATION_PROCEDURE: Final[str] = PROCEDURE_MC_CANDLE_PERTURBATION
PERTURBATION_MODE: Final[str] = "alternate-history"

# The resampling scheme the label records (AC4): a moving (overlapping) block
# bootstrap of exact-integer OHLC delta tuples.
RESAMPLING_SCHEME: Final[str] = "moving-block-bootstrap"
SCENARIO_ZERO_IS_TRUE_HISTORY: Final[bool] = True

PERTURBATION_RESULT_CLASS: Final[str] = "qmb-candle-perturbation-result"
PERTURBATION_RESULT_FORMAT_VERSION: Final[int] = 1
_PERTURBATION_PROVENANCE_CLASS: Final[str] = "qmb-candle-perturbation-provenance"
_OBJECTIVE_DISTRIBUTION_CLASS: Final[str] = "qmb-candle-perturbation-objective-distribution"
_PERTURBATION_SCENARIO_CLASS: Final[str] = "qmb-candle-perturbation-scenario"
_SYNTHETIC_SERIES_CLASS: Final[str] = "qmb-candle-perturbation-synthetic-series"
_CANDLE_CLASS: Final[str] = "qmb-candle"
_PERSISTENCE_CLASS: Final[str] = "qmb-candle-perturbation-persistence"

# The block length is a UI-editable configurable with NO ratified value (SC-07, AC1).
# The scenario count is likewise configurable. Neither ships an invented default.
BLOCK_LENGTH_KEY: Final[str] = "qmb_mc_candle_perturbation_block_length"
PERTURBATION_SCENARIO_COUNT_KEY: Final[str] = "qmb_mc_candle_perturbation_scenarios"
BLOCK_LENGTH_HAS_RATIFIED_VALUE: Final[bool] = False

# The smallest strictly-positive scaled-integer price. A rebuilt candle whose low
# would fall to or below zero is translated up so this becomes its low — the series
# is always valid and strictly positive (AC1).
MINIMUM_POSITIVE_PRICE: Final[int] = 1

# The B-7 persistence discipline (AC1, AC2). The perturbation DOES mint a synthetic
# market series — unlike trade-shuffle — but the series is procedure-ephemeral and
# never persisted, so the run stays world=replay with a robustness-only claim.
PERTURBATION_MINTS_SYNTHETIC_SERIES: Final[bool] = True
PERTURBATION_PERSISTS_SYNTHETIC_SERIES: Final[bool] = False
PERTURBATION_PROVENANCE_KIND: Final[str] = PROVENANCE_PROCEDURE_EPHEMERAL
PERTURBATION_CLAIM_CLASS: Final[str] = CLAIM_CLASS_ROBUSTNESS
PERTURBATION_MAKES_EDGE_CLAIM: Final[bool] = False
WORLD_WHEN_EPHEMERAL: Final[str] = World.REPLAY.value
WORLD_WHEN_PERSISTED: Final[str] = World.SIMULATED.value

# The summary is chart series as data, never images, and emits no verdict (AC6).
PERTURBATION_CANONICAL_PAYLOAD: Final[str] = "series-data"
PERTURBATION_EMITS_IMAGE_PAYLOAD: Final[bool] = False
PERTURBATION_EMITS_VERDICT: Final[bool] = False
PERTURBATION_VERDICT_DEFERRED_TO: Final[str] = THRESHOLDS_DEFERRED_TO

_PointValue = ExactRational | Money


# --- the candle and its exact-integer OHLC delta (AC1) -----------------------


@dataclass(frozen=True, slots=True)
class Candle:
    """One OHLC candle with exact strictly-positive scaled-integer prices (AC1).

    ``open``, ``high``, ``low``, and ``close`` are exact scaled integers (AD-7),
    never binary floats. A valid candle brackets its body: ``high`` is the maximum
    and ``low`` the minimum of the four prices, and every price is strictly positive.
    """

    instant: Instant
    open: int
    high: int
    low: int
    close: int

    def fp1_identity(self) -> dict[str, object]:
        """Canonical identity content. Package SemVer never enters."""
        return {
            "class": _CANDLE_CLASS,
            "close": self.close,
            "high": self.high,
            "instant_ns": self.instant.value_ns,
            "low": self.low,
            "open": self.open,
        }

    @classmethod
    def try_create(
        cls,
        instant: object,
        open_price: object,
        high: object,
        low: object,
        close: object,
    ) -> Result[Candle]:
        """Validate one strictly-positive, high/low-bounded OHLC candle."""
        if not isinstance(instant, Instant):
            return invalid(
                "instant",
                "a candle is timestamped with an Instant (int64 UTC-ns)",
                given=repr(type(instant).__name__),
            )
        prices = {"open": open_price, "high": high, "low": low, "close": close}
        parsed: dict[str, int] = {}
        for field, value in prices.items():
            checked = _positive_int(value, field)
            if is_refusal(checked):
                return checked
            parsed[field] = checked.value
        o, h, low_v, c = parsed["open"], parsed["high"], parsed["low"], parsed["close"]
        if h < max(o, c) or h < low_v:
            return invalid(
                "high",
                "a candle high is at least its open, close, and low (high/low bounds)",
                open=o,
                high=h,
                low=low_v,
                close=c,
            )
        if low_v > min(o, c):
            return invalid(
                "low",
                "a candle low is at most its open and close (high/low bounds)",
                open=o,
                high=h,
                low=low_v,
                close=c,
            )
        return Ok(cls(instant=instant, open=o, high=h, low=low_v, close=c))


@dataclass(frozen=True, slots=True)
class OHLCDelta:
    """One exact-integer OHLC delta tuple: ``(O, H, L, C) - anchor`` (AC1).

    The anchor is the previous candle's close (the seed price for the first
    candle). The four offsets are a rigid unit: adding one anchor to all four
    reconstructs a candle whose internal high/low bounds are preserved.
    """

    open_delta: int
    high_delta: int
    low_delta: int
    close_delta: int

    def fp1_identity(self) -> dict[str, object]:
        """Canonical identity content."""
        return {
            "close_delta": self.close_delta,
            "high_delta": self.high_delta,
            "low_delta": self.low_delta,
            "open_delta": self.open_delta,
        }


def ohlc_deltas(candles: object, *, seed_price: object = None) -> Result[tuple[OHLCDelta, ...]]:
    """Reduce a candle series to exact-integer OHLC delta tuples (AC1).

    Delta ``i`` is ``(O_i, H_i, L_i, C_i)`` minus its anchor — the previous
    candle's close, or the ``seed_price`` for ``i = 0`` (defaulting to the first
    candle's open). Cumulative-summing the deltas in their true order back onto the
    seed price reproduces the exact input series.
    """
    parsed = _coerce_candles(candles)
    if is_refusal(parsed):
        return parsed
    series = parsed.value
    seed = _resolve_seed_price(seed_price, series)
    if is_refusal(seed):
        return seed
    deltas: list[OHLCDelta] = []
    anchor = seed.value
    for candle in series:
        deltas.append(
            OHLCDelta(
                open_delta=candle.open - anchor,
                high_delta=candle.high - anchor,
                low_delta=candle.low - anchor,
                close_delta=candle.close - anchor,
            )
        )
        anchor = candle.close
    return Ok(tuple(deltas))


# --- scenario descriptors and the governed fan-out (AC5) ---------------------


@dataclass(frozen=True, slots=True)
class PerturbationScenario:
    """One alternate-history scenario: index, derived seed, replicate run id (AC4, AC5).

    ``role`` is always ``replicate`` — a scenario is a governed replicate run, never a
    bar-verdict run. ``run_id`` is the deterministic fingerprint the governor admits
    and the orchestrator ledgers exactly once. Scenario 0 is the true history.
    """

    scenario_index: int
    seed: int
    run_id: Fingerprint
    is_true_history: bool
    role: str = ROLE_REPLICATE

    def fp1_identity(self) -> dict[str, object]:
        """Canonical scenario identity content. Package SemVer is omitted."""
        return {
            "class": _PERTURBATION_SCENARIO_CLASS,
            "is_true_history": self.is_true_history,
            "role": self.role,
            "run_id": self.run_id.value,
            "scenario_index": self.scenario_index,
            "seed": self.seed,
        }


def perturbation_scenarios(
    base_seed: object,
    scenario_count: object,
    *,
    run_root: object = None,
) -> Result[tuple[PerturbationScenario, ...]]:
    """Build the deterministic scenario descriptors of one perturbation run (AC4, AC5).

    ``scenario_count`` scenarios are numbered ``0..count-1``; scenario ``s`` carries
    seed ``base_seed + s`` and a run id fingerprinted from the procedure, base seed,
    scenario index, and the optional ``run_root`` (the parent run's id) so replicate
    ids never collide across parent runs. Scenario 0 is flagged as the true history.
    """
    base = _non_negative_int(base_seed, "base_seed")
    if is_refusal(base):
        return base
    count = _positive_int(scenario_count, "scenario_count")
    if is_refusal(count):
        return count
    root = _optional_run_root(run_root)
    if is_refusal(root):
        return root
    scenarios: list[PerturbationScenario] = []
    for index in range(count.value):
        seed = base.value + index
        stamped = fingerprint(
            {
                "base_seed": base.value,
                "class": _PERTURBATION_SCENARIO_CLASS,
                "procedure": CANDLE_PERTURBATION_PROCEDURE,
                "role": ROLE_REPLICATE,
                "run_root": root.value,
                "scenario_index": index,
                "seed": seed,
            }
        )
        if is_refusal(stamped):
            return stamped
        scenarios.append(
            PerturbationScenario(
                scenario_index=index,
                seed=seed,
                run_id=stamped.value,
                is_true_history=index == 0,
            )
        )
    return Ok(tuple(scenarios))


def governed_perturbation_requests(
    scenarios: object,
    *,
    projected_peak_memory: object,
    cpu_cost: object = 1,
) -> Result[tuple[GovernedRequest, ...]]:
    """Build the governor requests for a scenario fan-out (B-5, AR-50, AC5).

    Each :class:`PerturbationScenario` becomes one
    :class:`~qmb.orchestrator.governor.GovernedRequest` the orchestrator submits to
    its ``min(cpu, memory)`` resource governor: admitted when it fits, enqueued when
    full (enqueue-on-full), never silently oversubscribed. Process fan-out belongs to
    the orchestrator — no Ray, no daemon, no required Docker — and each governed
    scenario ledgers exactly one ``role = replicate`` line.
    """
    parsed = _coerce_scenarios(scenarios)
    if is_refusal(parsed):
        return parsed
    requests: list[GovernedRequest] = []
    for scenario in parsed.value:
        built = GovernedRequest.try_create(scenario.run_id, projected_peak_memory, cpu_cost)
        if is_refusal(built):
            return built
        requests.append(built.value)
    return Ok(tuple(requests))


def refuse_perturbation_bar_verdict(name: object) -> Result[None]:
    """Refuse reading a bar verdict out of a replicate scenario line (AR-51, AC5).

    A governed scenario appends exactly one ``role = replicate`` ledger line carrying
    the objective measure — never a Book-bar pass/fail. Any attempt to read a bar
    verdict out of it is a ``policy rejection`` (B-4, AR-51).
    """
    token = clean_token(name)
    if token is None:
        return invalid(
            "verdict",
            "a verdict name is required to refuse it",
            given=repr(name),
        )
    return policy(
        "verdict",
        "a candle-perturbation scenario is a role=replicate run appending one ledger line "
        "with the objective measure; it never writes a Book-bar pass/fail verdict (B-4, AR-51)",
        verdict=token,
        role=ROLE_REPLICATE,
        writes_bar_verdict=False,
    )


# --- the B-7 persistence law (AC2, AC3) --------------------------------------


@dataclass(frozen=True, slots=True)
class PerturbationPersistence:
    """The compiled persistence classification of a perturbation run (AC2, AC3).

    The only OK state is the procedure-ephemeral one: the synthetic series is never
    persisted, the run stays ``world = replay``, provenance is
    ``procedure-ephemeral``, and the claim class is robustness-only. Every persisting
    configuration is a typed refusal, never an Ok value.
    """

    world: str
    data_provenance: str
    claim_class: str
    persisted: bool

    def fp1_identity(self) -> dict[str, object]:
        """Canonical persistence identity content."""
        return {
            "claim_class": self.claim_class,
            "class": _PERSISTENCE_CLASS,
            "data_provenance": self.data_provenance,
            "persisted": self.persisted,
            "world": self.world,
        }


def perturbation_persistence(
    *,
    persist: object = False,
    clock: object = CLOCK_REPLAY,
) -> Result[PerturbationPersistence]:
    """Classify a perturbation run by whether it persists its synthetic series (AC2, AC3).

    * ``persist = False`` (the only OK state): the perturbation is procedure-ephemeral
      — ``world = replay``, provenance ``procedure-ephemeral``, claim class robustness
      (AC2). A ``simulated`` clock with no persistence is a mismatch and refuses.
    * ``persist = True`` with a ``simulated`` clock: ``world = simulated`` governed
      evidence — a typed ``policy rejection`` that cannot ledger into the bar's store
      until GAP-0048 closes (SC-06, AC3).
    * ``persist = True`` with a ``replay`` clock: a replay clock bound to
      synthetic-tainted persisted data is a typed ``invalid input`` (B-2/B-7 wins,
      FM-3, DEC-0164, AC3).
    """
    if not isinstance(persist, bool):
        return invalid(
            "persist",
            "persist is an explicit bool: whether the synthetic series is written to a data room",
            given=repr(type(persist).__name__),
        )
    clock_token = clean_token(clock)
    if clock_token not in (CLOCK_REPLAY, CLOCK_SIMULATED):
        return invalid(
            "clock",
            "a perturbation run binds clock replay or simulated",
            given=repr(clock),
            legal=(CLOCK_REPLAY, CLOCK_SIMULATED),
        )
    if not persist:
        if clock_token != CLOCK_REPLAY:
            return invalid(
                "clock",
                "a procedure-ephemeral perturbation stays world=replay; a simulated clock "
                "without persistence is a clock/provenance mismatch (B-7, FM-3)",
                clock=clock_token,
                data_provenance=PROVENANCE_PROCEDURE_EPHEMERAL,
            )
        return Ok(
            PerturbationPersistence(
                world=World.REPLAY.value,
                data_provenance=PROVENANCE_PROCEDURE_EPHEMERAL,
                claim_class=PERTURBATION_CLAIM_CLASS,
                persisted=False,
            )
        )
    if clock_token == CLOCK_REPLAY:
        return refuse_replay_clock_on_synthetic_persisted(clock_token)
    return refuse_persisted_synthetic_series(PERTURBATION_SCENARIO_COUNT_KEY)


def refuse_persisted_synthetic_series(name: object) -> TypedRefusal:
    """Refuse ledgering a persisted synthetic series as governed evidence (SC-06, AC3).

    A config that persists the synthetic series compiles to ``world = simulated`` and
    is a typed ``policy rejection`` for governed evidence: it cannot ledger into the
    bar's store while the GAP-0048 fidelity seam is open. Returned, never raised.
    """
    token = clean_token(name)
    if token is None:
        return invalid(
            "config",
            "a config identity is required to refuse persisting the synthetic series",
            given=repr(name),
        )
    return policy(
        "data_provenance",
        "persisting the synthetic candle series makes the run world=simulated governed "
        "evidence; it is a typed policy rejection that cannot ledger into the bar's store "
        "until GAP-0048 closes (SC-06, B-7)",
        config=token,
        world=World.SIMULATED.value,
        data_provenance=PROVENANCE_SYNTHETIC_TAINTED,
        gated_behind=CLAIM_GATED_BEHIND,
    )


def refuse_replay_clock_on_synthetic_persisted(clock: object) -> TypedRefusal:
    """Refuse a replay clock bound to synthetic-tainted persisted data (B-2/B-7, AC3).

    World is provenance-derived: a ``replay`` clock bound to synthetic-tainted
    persisted data is a typed ``invalid input`` — B-7 (a caller may not declare world)
    and B-2 (the replay clock reads recorded data) win (FM-3, DEC-0164).
    """
    token = clean_token(clock)
    return invalid(
        "clock",
        "a replay clock bound to synthetic-tainted persisted data is invalid input; "
        "world is provenance-derived and B-2/B-7 win (FM-3, DEC-0164)",
        clock=token if token is not None else repr(clock),
        data_provenance=PROVENANCE_SYNTHETIC_TAINTED,
    )


# --- the RNG / data-window provenance record (AC4) ---------------------------


@dataclass(frozen=True, slots=True)
class PerturbationProvenance:
    """The RNG, block, and data-window provenance every result records (AR-59, AC4).

    Carries the RNG family, base seed, seed-derivation rule, block length, scenario
    count, resampling scheme, and the data-window UTC-ns bounds. This is the
    ``rng_provenance`` the CT-32 label folds in for a stochastic run (B-13).
    """

    rng_family: str
    base_seed: int
    seed_derivation_rule: str
    block_length: int
    scenario_count: int
    resampling_scheme: str
    data_window_start_ns: int
    data_window_end_ns: int

    def fp1_identity(self) -> dict[str, object]:
        """Canonical provenance identity content."""
        return {
            "base_seed": self.base_seed,
            "block_length": self.block_length,
            "class": _PERTURBATION_PROVENANCE_CLASS,
            "data_window_end_ns": self.data_window_end_ns,
            "data_window_start_ns": self.data_window_start_ns,
            "resampling_scheme": self.resampling_scheme,
            "rng_family": self.rng_family,
            "scenario_count": self.scenario_count,
            "seed_derivation_rule": self.seed_derivation_rule,
        }


# --- the per-scenario synthetic series (procedure-ephemeral, AC1) -------------


@dataclass(frozen=True, slots=True)
class SyntheticCandleSeries:
    """One scenario's synthetic candle series — procedure-ephemeral, never persisted.

    Scenario 0 (``is_true_history``) is the real candles verbatim; every other
    scenario is a moving-block-bootstrapped alternate history. ``fingerprint`` is the
    ``fp1`` over the candle series; the run result folds only this fingerprint into
    its identity, never the full candles.
    """

    scenario_index: int
    is_true_history: bool
    candles: tuple[Candle, ...]
    fingerprint: Fingerprint

    def fp1_identity(self) -> dict[str, object]:
        """Canonical series identity content — the full candle sequence."""
        return {
            "candles": [candle.fp1_identity() for candle in self.candles],
            "class": _SYNTHETIC_SERIES_CLASS,
            "is_true_history": self.is_true_history,
            "scenario_index": self.scenario_index,
        }


# --- the objective distribution summary (AC6) --------------------------------


@dataclass(frozen=True, slots=True)
class AlternateHistoryDistribution:
    """The objective measure summarised across the alternate histories, as data (AC6).

    ``summary`` is the Story 22.1 distribution primitive — percentiles, confidence
    bands, and a direction-aware one-tailed p-value — over the perturbed scenarios'
    objective values against the true (scenario 0) result.
    ``observed_favorable_rank`` is the direction-aware empirical percentile rank of the
    true result within the alternate-history distribution. ``distribution`` is a
    histogram-ready array of the scenario objective values — chart series as data,
    never an image, AD-10-excluded from identity. No pass/fail verdict is emitted.
    """

    objective_identity: str
    direction: str
    unit_kind: str
    scenario_count: int
    summary: DistributionSummary
    observed_favorable_rank_num: int
    observed_favorable_rank_den: int
    distribution: HistogramReadyArray

    @property
    def observed_favorable_rank(self) -> Fraction:
        """The direction-aware empirical percentile rank of the true result (0..1)."""
        return Fraction(self.observed_favorable_rank_num, self.observed_favorable_rank_den)

    @property
    def emits_verdict(self) -> bool:
        """Always ``False`` — the objective distribution is pure data (AC6)."""
        return PERTURBATION_EMITS_VERDICT

    def chart_series(self) -> dict[str, object]:
        """The scenario distribution as machine-readable chart series (never an image)."""
        return self.distribution.as_data()

    def fp1_identity(self) -> dict[str, object]:
        """Canonical identity content. The histogram array is display-only, excluded."""
        return {
            "canonical_payload": PERTURBATION_CANONICAL_PAYLOAD,
            "class": _OBJECTIVE_DISTRIBUTION_CLASS,
            "direction": self.direction,
            "emits_image_payload": PERTURBATION_EMITS_IMAGE_PAYLOAD,
            "emits_verdict": PERTURBATION_EMITS_VERDICT,
            "objective_identity": self.objective_identity,
            "observed_favorable_rank_den": self.observed_favorable_rank_den,
            "observed_favorable_rank_num": self.observed_favorable_rank_num,
            "scenario_count": self.scenario_count,
            "summary": self.summary.fp1_identity(),
            "unit_kind": self.unit_kind,
        }


def summarize_perturbation_objective(
    *,
    objective_identity: object,
    observed: object,
    scenario_objectives: object,
    direction: object,
    band_probabilities: object = (),
) -> Result[AlternateHistoryDistribution]:
    """Summarise the objective measure across the alternate histories, as data (AC6).

    ``observed`` is the true-history (scenario 0) objective; ``scenario_objectives``
    is the objective measure of each perturbed scenario. Every value is an exact
    quantity — ``Money``, an ``ExactRational``, an ``int``, or a ``Fraction`` — sharing
    the observed value's unit-kind. Returns percentiles, confidence bands, and the
    direction-aware empirical percentile rank of the true result within the
    distribution. No pass/fail verdict is emitted and no alpha level is invented.
    """
    label = clean_token(objective_identity)
    if label is None:
        return invalid(
            "objective_identity",
            "the summarised objective names a non-blank measure identity",
            given=repr(objective_identity),
        )
    dir_token = _direction_token(direction)
    if is_refusal(dir_token):
        return dir_token
    observed_pv = _as_point_value(observed, field="observed")
    if is_refusal(observed_pv):
        return observed_pv
    unit_kind = observed_pv.value.unit_kind
    scenarios = _coerce_objectives(scenario_objectives, unit_kind)
    if is_refusal(scenarios):
        return scenarios
    values = scenarios.value
    if not values:
        return invalid(
            "scenario_objectives",
            "summarising the objective needs at least one perturbed-scenario value; an "
            "empty required input is invalid, never a silently-applied default (AR-13)",
        )
    summary = summarize_distribution(
        values,
        observed_pv.value,
        dir_token.value,
        band_probabilities=band_probabilities,
    )
    if is_refusal(summary):
        return summary
    favorable = _favorable_rank(summary.value.percentile_rank, dir_token.value)
    distribution = HistogramReadyArray(
        name=f"{label}_alternate_history_distribution",
        unit_kind=unit_kind,
        values=values,
    )
    return Ok(
        AlternateHistoryDistribution(
            objective_identity=label,
            direction=dir_token.value,
            unit_kind=unit_kind.value,
            scenario_count=len(values),
            summary=summary.value,
            observed_favorable_rank_num=favorable.numerator,
            observed_favorable_rank_den=favorable.denominator,
            distribution=distribution,
        )
    )


# --- the result (AC1, AC2, AC4, AC6) -----------------------------------------


@dataclass(frozen=True, slots=True)
class CandlePerturbationResult:
    """The Monte Carlo candle-perturbation result of one replay run (AC1, AC2, AC4, AC6).

    ``provenance`` records the RNG family, base seed, seed rule, block length,
    scenario count, resampling scheme, and data-window bounds; ``scenarios`` are the
    governed replicate descriptors; ``series`` carries each scenario's
    procedure-ephemeral synthetic candles (scenario 0 is the true history);
    ``objective`` is the alternate-history distribution summary when the objective was
    supplied. The whole object mints a synthetic series but never persists it, stays
    ``world = replay``, and is a pure deterministic function of its inputs —
    :meth:`fingerprint` reproduces bit-for-bit (AC4). It makes no edge claim and emits
    no verdict.
    """

    procedure: str
    mode: str
    world: str
    base_seed: int
    seed_price: int
    block_length: int
    scenario_count: int
    provenance: PerturbationProvenance
    scenarios: tuple[PerturbationScenario, ...]
    series: tuple[SyntheticCandleSeries, ...]
    objective: AlternateHistoryDistribution | None = None

    @property
    def emits_verdict(self) -> bool:
        """Always ``False`` — the result is pure data, never a verdict (AC6)."""
        return PERTURBATION_EMITS_VERDICT

    @property
    def mints_synthetic_series(self) -> bool:
        """Always ``True`` — the perturbation mints a synthetic market series (AC1)."""
        return PERTURBATION_MINTS_SYNTHETIC_SERIES

    @property
    def persists_synthetic_series(self) -> bool:
        """Always ``False`` — the synthetic series is procedure-ephemeral (AC2)."""
        return PERTURBATION_PERSISTS_SYNTHETIC_SERIES

    @property
    def claim_class(self) -> str:
        """Always robustness (alternate-history), never edge (L20, AC6)."""
        return PERTURBATION_CLAIM_CLASS

    def true_history(self) -> SyntheticCandleSeries:
        """Scenario 0 — the real candles verbatim (AC1)."""
        return self.series[0]

    def series_at(self, scenario_index: int) -> SyntheticCandleSeries | None:
        """The synthetic series for ``scenario_index``, or ``None`` if out of range."""
        for item in self.series:
            if item.scenario_index == scenario_index:
                return item
        return None

    def rng_provenance(self) -> dict[str, object]:
        """The ``rng_provenance`` stamp the CT-32 label folds in (B-13, AR-59)."""
        return self.provenance.fp1_identity()

    def result_label(self) -> dict[str, object]:
        """The procedure identity plus seed that enter the result label (B-7, AC2)."""
        return {
            "base_seed": self.base_seed,
            "claim_class": PERTURBATION_CLAIM_CLASS,
            "class": PERTURBATION_RESULT_CLASS,
            "mints_synthetic_series": PERTURBATION_MINTS_SYNTHETIC_SERIES,
            "mode": self.mode,
            "persists_synthetic_series": PERTURBATION_PERSISTS_SYNTHETIC_SERIES,
            "procedure": self.procedure,
            "provenance_kind": PERTURBATION_PROVENANCE_KIND,
            "resampling_scheme": RESAMPLING_SCHEME,
            "rng_family": self.provenance.rng_family,
            "world": self.world,
        }

    def fp1_identity(self) -> dict[str, object]:
        """Canonical identity content. Deterministic and reproducible (AC4, NFR-03).

        The per-scenario synthetic candles are folded in only by their series
        fingerprint (not the full candle sequences), keeping identity bounded while
        staying a pure function of the inputs.
        """
        content: dict[str, object] = {
            "base_seed": self.base_seed,
            "block_length": self.block_length,
            "canonical_payload": PERTURBATION_CANONICAL_PAYLOAD,
            "claim_class": PERTURBATION_CLAIM_CLASS,
            "class": PERTURBATION_RESULT_CLASS,
            "emits_image_payload": PERTURBATION_EMITS_IMAGE_PAYLOAD,
            "emits_verdict": PERTURBATION_EMITS_VERDICT,
            "format_version": PERTURBATION_RESULT_FORMAT_VERSION,
            "makes_edge_claim": PERTURBATION_MAKES_EDGE_CLAIM,
            "mints_synthetic_series": PERTURBATION_MINTS_SYNTHETIC_SERIES,
            "mode": self.mode,
            "persists_synthetic_series": PERTURBATION_PERSISTS_SYNTHETIC_SERIES,
            "procedure": self.procedure,
            "provenance": self.provenance.fp1_identity(),
            "resampling_scheme": RESAMPLING_SCHEME,
            "scenario_count": self.scenario_count,
            "scenarios": [scenario.fp1_identity() for scenario in self.scenarios],
            "seed_price": self.seed_price,
            "series_fingerprints": [item.fingerprint.value for item in self.series],
            "world": self.world,
        }
        if self.objective is not None:
            content["objective"] = self.objective.fp1_identity()
        return content

    def fingerprint(self) -> Result[Fingerprint]:
        """Content fingerprint. The same inputs reproduce it bit-for-bit (AC4)."""
        return fingerprint(self.fp1_identity())


def run_candle_perturbation(
    *,
    candles: object,
    base_seed: object,
    block_length: object = None,
    scenario_count: object = None,
    config: object = None,
    seed_price: object = None,
    run_root: object = None,
    objective_identity: object = None,
    scenario_objectives: object = None,
    objective_direction: object = None,
    band_probabilities: object = (),
) -> Result[CandlePerturbationResult]:
    """Run the Monte Carlo candle-perturbation over a replay run's candles (AC1-AC6).

    ``candles`` is the ``world = replay`` run's real historical OHLC series. The block
    length and scenario count are UI-editable configurables resolved from ``config``
    (the ``qmb_mc_candle_perturbation_block_length`` and
    ``qmb_mc_candle_perturbation_scenarios`` keys) or passed explicitly — neither has
    a ratified value (SC-07). Each scenario moving-block-bootstraps exact-integer OHLC
    deltas with a ``base_seed + scenario_index`` seeded generator and cumulative-sums
    them onto the seed price, always rebuilding a valid strictly-positive series;
    scenario 0 is the true history. No synthetic series is persisted, so the run stays
    ``world = replay`` (B-7). When ``scenario_objectives`` (one exact objective value
    per scenario, index-aligned) and ``objective_direction`` are supplied, the
    objective is summarised across the alternate histories against the true result. No
    verdict is emitted.
    """
    resolved_block = _resolve_configurable(config, block_length, BLOCK_LENGTH_KEY, "block_length")
    if is_refusal(resolved_block):
        return resolved_block
    resolved_count = _resolve_configurable(
        config, scenario_count, PERTURBATION_SCENARIO_COUNT_KEY, "scenario_count"
    )
    if is_refusal(resolved_count):
        return resolved_count
    base = _non_negative_int(base_seed, "base_seed")
    if is_refusal(base):
        return base
    parsed_candles = _coerce_candles(candles)
    if is_refusal(parsed_candles):
        return parsed_candles
    true_candles = parsed_candles.value
    seed = _resolve_seed_price(seed_price, true_candles)
    if is_refusal(seed):
        return seed
    block = resolved_block.value
    if block > len(true_candles):
        return invalid(
            "block_length",
            "the moving-block bootstrap block length cannot exceed the candle count; a "
            "block must fit inside the data window (AC1)",
            block_length=block,
            candle_count=len(true_candles),
        )
    deltas = ohlc_deltas(true_candles, seed_price=seed.value)
    if is_refusal(deltas):
        return deltas
    timeline = tuple(candle.instant for candle in true_candles)
    descriptors = perturbation_scenarios(base.value, resolved_count.value, run_root=run_root)
    if is_refusal(descriptors):
        return descriptors
    built_series = _build_scenarios(
        true_candles=true_candles,
        deltas=deltas.value,
        timeline=timeline,
        seed_price=seed.value,
        base_seed=base.value,
        scenario_count=resolved_count.value,
        block_length=block,
    )
    if is_refusal(built_series):
        return built_series
    objective: AlternateHistoryDistribution | None = None
    if scenario_objectives is not None or objective_identity is not None:
        summarised = _summarise_supplied_objective(
            objective_identity=objective_identity,
            scenario_objectives=scenario_objectives,
            objective_direction=objective_direction,
            scenario_count=resolved_count.value,
            band_probabilities=band_probabilities,
        )
        if is_refusal(summarised):
            return summarised
        objective = summarised.value
    provenance = PerturbationProvenance(
        rng_family=RNG_FAMILY,
        base_seed=base.value,
        seed_derivation_rule=SEED_DERIVATION_RULE,
        block_length=block,
        scenario_count=resolved_count.value,
        resampling_scheme=RESAMPLING_SCHEME,
        data_window_start_ns=timeline[0].value_ns,
        data_window_end_ns=timeline[-1].value_ns,
    )
    return Ok(
        CandlePerturbationResult(
            procedure=CANDLE_PERTURBATION_PROCEDURE,
            mode=PERTURBATION_MODE,
            world=World.REPLAY.value,
            base_seed=base.value,
            seed_price=seed.value,
            block_length=block,
            scenario_count=resolved_count.value,
            provenance=provenance,
            scenarios=descriptors.value,
            series=built_series.value,
            objective=objective,
        )
    )


def perturbation_identity() -> dict[str, object]:
    """Identity-bearing candle-perturbation-procedure fields. Package SemVer is omitted."""
    return {
        "block_length_has_ratified_value": BLOCK_LENGTH_HAS_RATIFIED_VALUE,
        "block_length_key": BLOCK_LENGTH_KEY,
        "canonical_payload": PERTURBATION_CANONICAL_PAYLOAD,
        "claim_class": PERTURBATION_CLAIM_CLASS,
        "class": PERTURBATION_RESULT_CLASS,
        "emits_image_payload": PERTURBATION_EMITS_IMAGE_PAYLOAD,
        "emits_verdict": PERTURBATION_EMITS_VERDICT,
        "format_version": PERTURBATION_RESULT_FORMAT_VERSION,
        "gated_behind": CLAIM_GATED_BEHIND,
        "makes_edge_claim": PERTURBATION_MAKES_EDGE_CLAIM,
        "mints_synthetic_series": PERTURBATION_MINTS_SYNTHETIC_SERIES,
        "mode": PERTURBATION_MODE,
        "persists_synthetic_series": PERTURBATION_PERSISTS_SYNTHETIC_SERIES,
        "procedure": CANDLE_PERTURBATION_PROCEDURE,
        "provenance_kind": PERTURBATION_PROVENANCE_KIND,
        "resampling_scheme": RESAMPLING_SCHEME,
        "rng_family": RNG_FAMILY,
        "scenario_count_key": PERTURBATION_SCENARIO_COUNT_KEY,
        "scenario_run_role": ROLE_REPLICATE,
        "scenario_zero_is_true_history": SCENARIO_ZERO_IS_TRUE_HISTORY,
        "seed_derivation_rule": SEED_DERIVATION_RULE,
        "verdict_deferred_to": PERTURBATION_VERDICT_DEFERRED_TO,
        "world_when_ephemeral": WORLD_WHEN_EPHEMERAL,
        "world_when_persisted": WORLD_WHEN_PERSISTED,
    }


# --- scenario reconstruction (exact integer money) ---------------------------


def _build_scenarios(
    *,
    true_candles: tuple[Candle, ...],
    deltas: tuple[OHLCDelta, ...],
    timeline: tuple[Instant, ...],
    seed_price: int,
    base_seed: int,
    scenario_count: int,
    block_length: int,
) -> Result[tuple[SyntheticCandleSeries, ...]]:
    """Build every scenario's synthetic series. Scenario 0 is the true history.

    Scenario ``s >= 1`` resamples overlapping length-``block_length`` blocks of the
    OHLC deltas with a fresh ``random.Random(base_seed + s)``, cumulative-sums them
    onto the seed price in exact integer money, and rebuilds a valid strictly-positive
    OHLC series (high/low bounds enforced, a non-positive candle translated up).
    """
    series: list[SyntheticCandleSeries] = []
    for index in range(scenario_count):
        if index == 0:
            candles = true_candles
        else:
            resampled = _resample_deltas(deltas, block_length, base_seed + index)
            rebuilt = _rebuild_candles(resampled, timeline, seed_price)
            if is_refusal(rebuilt):
                return rebuilt
            candles = rebuilt.value
        stamped = fingerprint(
            {
                "candles": [candle.fp1_identity() for candle in candles],
                "class": _SYNTHETIC_SERIES_CLASS,
                "is_true_history": index == 0,
                "scenario_index": index,
            }
        )
        if is_refusal(stamped):
            return stamped
        series.append(
            SyntheticCandleSeries(
                scenario_index=index,
                is_true_history=index == 0,
                candles=candles,
                fingerprint=stamped.value,
            )
        )
    return Ok(tuple(series))


def _resample_deltas(
    deltas: tuple[OHLCDelta, ...],
    block_length: int,
    seed: int,
) -> tuple[OHLCDelta, ...]:
    """Moving-block bootstrap: draw overlapping length-``block_length`` blocks.

    Block starts are uniform over ``[0, n - block_length]`` (overlapping blocks). A
    fresh seeded MT19937 generator draws ``ceil(n / block_length)`` blocks, which are
    concatenated and truncated to ``n`` deltas — never a cryptographic use (AR-59).
    """
    n = len(deltas)
    num_starts = n - block_length + 1
    blocks_needed = -(-n // block_length)  # ceil division
    # A seeded MT19937 generator, one fresh instance per scenario, for a reproducible
    # alternate-history resample — never a cryptographic use (AR-59, AC4).
    rng = random.Random(seed)  # noqa: S311
    resampled: list[OHLCDelta] = []
    for _ in range(blocks_needed):
        start = rng.randrange(num_starts)
        resampled.extend(deltas[start : start + block_length])
    return tuple(resampled[:n])


def _rebuild_candles(
    deltas: tuple[OHLCDelta, ...],
    timeline: tuple[Instant, ...],
    seed_price: int,
) -> Result[tuple[Candle, ...]]:
    """Cumulative-sum resampled deltas onto the seed price into valid candles (AC1).

    The running anchor starts at ``seed_price`` and advances to each rebuilt close.
    High/low bounds are enforced from the four rebuilt prices, and any candle whose
    low would fall to or below zero is translated up so the series stays strictly
    positive.
    """
    anchor = seed_price
    candles: list[Candle] = []
    for index, delta in enumerate(deltas):
        o = anchor + delta.open_delta
        h = anchor + delta.high_delta
        low_v = anchor + delta.low_delta
        c = anchor + delta.close_delta
        high = max(o, h, low_v, c)
        low = min(o, h, low_v, c)
        if low < MINIMUM_POSITIVE_PRICE:
            shift = MINIMUM_POSITIVE_PRICE - low
            o += shift
            c += shift
            high += shift
            low += shift
        built = Candle.try_create(timeline[index], o, high, low, c)
        if is_refusal(built):
            return built
        candles.append(built.value)
        anchor = c
    return Ok(tuple(candles))


# --- objective summarisation helpers (AC6) -----------------------------------


def _summarise_supplied_objective(
    *,
    objective_identity: object,
    scenario_objectives: object,
    objective_direction: object,
    scenario_count: int,
    band_probabilities: object,
) -> Result[AlternateHistoryDistribution | None]:
    """Summarise a caller-supplied per-scenario objective, or refuse a partial request.

    ``scenario_objectives`` is index-aligned to the scenarios (element 0 is the true
    history). The observed value is element 0 and the distribution is elements
    ``1..``. A single-scenario run has no alternate-history distribution and returns
    no objective summary.
    """
    if objective_identity is None:
        return invalid(
            "objective_identity",
            "summarising the objective needs the measure identity alongside the "
            "per-scenario objective values",
        )
    if scenario_objectives is None:
        return invalid(
            "scenario_objectives",
            "summarising the objective needs one objective value per scenario, "
            "index-aligned to the scenarios (element 0 is the true history)",
        )
    if isinstance(scenario_objectives, (str, bytes, bytearray)) or not isinstance(
        scenario_objectives, Sequence
    ):
        return invalid(
            "scenario_objectives",
            "the per-scenario objectives are an ordered sequence of exact values",
            given=repr(type(scenario_objectives).__name__),
        )
    supplied = cast("Sequence[object]", scenario_objectives)
    if len(supplied) != scenario_count:
        return invalid(
            "scenario_objectives",
            "one objective value per scenario is required, index-aligned to the scenarios",
            given=len(supplied),
            scenario_count=scenario_count,
        )
    if scenario_count < 2:
        return Ok(None)
    return _as_optional(
        summarize_perturbation_objective(
            objective_identity=objective_identity,
            observed=supplied[0],
            scenario_objectives=list(supplied[1:]),
            direction=objective_direction,
            band_probabilities=band_probabilities,
        )
    )


def _as_optional(
    result: Result[AlternateHistoryDistribution],
) -> Result[AlternateHistoryDistribution | None]:
    if is_refusal(result):
        return result
    value: AlternateHistoryDistribution | None = result.value
    return Ok(value)


def _favorable_rank(percentile_rank: Fraction, direction: str) -> Fraction:
    """The direction-aware empirical percentile rank of the true result (AC6).

    ``percentile_rank`` is the fraction of the distribution below the observed value.
    Higher-is-better favours a high rank as-is; lower-is-better favours the low side,
    so the favourable fraction is its complement.
    """
    if direction == DIRECTION_LOWER_IS_BETTER:
        return Fraction(1) - percentile_rank
    return percentile_rank


def _direction_token(direction: object) -> Result[str]:
    token = clean_token(direction)
    if token not in (DIRECTION_HIGHER_IS_BETTER, DIRECTION_LOWER_IS_BETTER):
        return invalid(
            "direction",
            "an objective distribution declares direction higher-is-better or lower-is-better",
            given=repr(direction),
            allowed=(DIRECTION_HIGHER_IS_BETTER, DIRECTION_LOWER_IS_BETTER),
        )
    return Ok(token)


def _as_point_value(value: object, *, field: str, index: int | None = None) -> Result[_PointValue]:
    """Coerce an exact objective value to a ``Money`` or ``ExactRational`` point value."""
    context: dict[str, object] = {} if index is None else {"index": index}
    if isinstance(value, bool):
        return invalid(
            field,
            "an objective value is a number, not a boolean",
            given=repr(value),
            **context,
        )
    if isinstance(value, Money):
        return Ok(value)
    if isinstance(value, ExactRational):
        return Ok(value)
    if isinstance(value, int):
        minted = ExactRational.try_create(value, 1, UnitKind.DIMENSIONLESS_RATIO)
        if is_refusal(minted):
            return minted
        return Ok(minted.value)
    if isinstance(value, Fraction):
        minted = ExactRational.try_create(
            value.numerator, value.denominator, UnitKind.DIMENSIONLESS_RATIO
        )
        if is_refusal(minted):
            return minted
        return Ok(minted.value)
    if isinstance(value, float):
        return invalid(
            field,
            "a binary float never enters the objective distribution; carry it through the "
            "return-space carve-out (a label-derived measure) or supply exact Money / rational "
            "(AD-7, NFR-03)",
            given=repr(value),
            **context,
        )
    return invalid(
        field,
        "an objective value is exact Money, an ExactRational, an int, or a Fraction",
        given=repr(type(value).__name__),
        **context,
    )


def _coerce_objectives(value: object, unit_kind: UnitKind) -> Result[tuple[_PointValue, ...]]:
    if isinstance(value, (str, bytes, bytearray)) or not isinstance(value, Sequence):
        return invalid(
            "scenario_objectives",
            "the per-scenario objectives are an ordered sequence of exact values",
            given=repr(type(value).__name__),
        )
    out: list[_PointValue] = []
    for index, item in enumerate(cast("Sequence[object]", value)):
        parsed = _as_point_value(item, field="scenario_objectives", index=index)
        if is_refusal(parsed):
            return parsed
        if parsed.value.unit_kind is not unit_kind:
            return invalid(
                "scenario_objectives",
                "every scenario objective shares the observed value's unit-kind; there is "
                "no silent unit coercion (AD-40)",
                index=index,
                given=parsed.value.unit_kind.value,
                expected=unit_kind.value,
            )
        out.append(parsed.value)
    return Ok(tuple(out))


# --- coercion helpers --------------------------------------------------------


def _coerce_candles(value: object) -> Result[tuple[Candle, ...]]:
    if isinstance(value, Candle):
        items: Sequence[object] = (value,)
    elif isinstance(value, (str, bytes, bytearray)) or not isinstance(value, Sequence):
        return invalid(
            "candles",
            "candle-perturbation reads the replay run's ordered OHLC candle series",
            given=repr(type(value).__name__),
        )
    else:
        items = cast("Sequence[object]", value)
    out: list[Candle] = []
    previous_ns: int | None = None
    for index, item in enumerate(items):
        parsed = _candle_from(item, index)
        if is_refusal(parsed):
            return parsed
        candle = parsed.value
        if previous_ns is not None and candle.instant.value_ns <= previous_ns:
            return invalid(
                "candles",
                "candles are strictly increasing in Instant order (a real historical series)",
                index=index,
                instant_ns=candle.instant.value_ns,
                previous_ns=previous_ns,
            )
        previous_ns = candle.instant.value_ns
        out.append(candle)
    if not out:
        return invalid(
            "candles",
            "candle-perturbation re-runs over a non-empty real candle series; an empty "
            "series has no history to perturb (AC1)",
        )
    return Ok(tuple(out))


def _candle_from(item: object, index: int) -> Result[Candle]:
    if isinstance(item, Candle):
        return Ok(item)
    if not isinstance(item, Mapping):
        return invalid(
            "candles",
            "every candle is a Candle or a mapping of instant, open, high, low, close",
            index=index,
            given=repr(type(item).__name__),
        )
    body = cast("Mapping[str, object]", item)
    minted = Candle.try_create(
        body.get("instant"),
        body.get("open"),
        body.get("high"),
        body.get("low"),
        body.get("close"),
    )
    if is_refusal(minted):
        return invalid(
            "candles",
            "each candle is a valid strictly-positive OHLC print",
            index=index,
            cause=dict(minted.context),
        )
    return minted


def _coerce_scenarios(value: object) -> Result[tuple[PerturbationScenario, ...]]:
    if isinstance(value, PerturbationScenario):
        return Ok((value,))
    if isinstance(value, (str, bytes, bytearray)) or not isinstance(value, Sequence):
        return invalid(
            "scenarios",
            "the fan-out reads a sequence of PerturbationScenario descriptors",
            given=repr(type(value).__name__),
        )
    out: list[PerturbationScenario] = []
    for index, item in enumerate(cast("Sequence[object]", value)):
        if not isinstance(item, PerturbationScenario):
            return invalid(
                "scenarios",
                "each scenario is a PerturbationScenario built by perturbation_scenarios",
                index=index,
                given=repr(type(item).__name__),
            )
        out.append(item)
    if not out:
        return invalid("scenarios", "a scenario fan-out has at least one scenario")
    return Ok(tuple(out))


def _resolve_configurable(config: object, explicit: object, key: str, field: str) -> Result[int]:
    """Resolve a required positive-int configurable from the config key or an explicit arg.

    Neither the block length nor the scenario count has a ratified value (SC-07); an
    unset input is a typed ``invalid input`` refusal, never a silently-applied default.
    """
    if config is not None:
        return require_positive_int(config, key)
    if explicit is not None:
        return _positive_int(explicit, field)
    return invalid(
        field,
        "this input is a UI-editable configurable with no ratified value; supply it via the "
        "resolved run-config key or explicitly (SC-07)",
        configurable_key=key,
    )


def _resolve_seed_price(value: object, candles: tuple[Candle, ...]) -> Result[int]:
    """The cumulative-sum seed price, defaulting to the first candle's open (AC1)."""
    if value is None:
        return Ok(candles[0].open)
    return _positive_int(value, "seed_price")


def _optional_run_root(value: object) -> Result[str]:
    if value is None:
        return Ok("")
    if isinstance(value, Fingerprint):
        return Ok(value.value)
    token = clean_token(value)
    if token is None:
        return invalid(
            "run_root",
            "the parent run root is a Fingerprint or its fp1 token",
            given=repr(value),
        )
    return Ok(token)


def _non_negative_int(value: object, field: str) -> Result[int]:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        return invalid(field, "a non-negative exact integer is required", given=repr(value))
    return Ok(value)


def _positive_int(value: object, field: str) -> Result[int]:
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        return invalid(field, "a positive exact integer is required", given=repr(value))
    return Ok(value)
