"""MIS surface: governed signal snapshot, V1 producers, and the shadow seam.

Story 26.3 lands the compute-once environment-keyed signal snapshot dispatched
to the Book door and the KSA only. Story 26.17 ships the six rule-based
labelers plus fitted ``liquidity_stress_v1``. ``regime_classifier_v1`` stays
unbound. Story 26.18 publishes candidates through the zero-authority shadow
seam — distinct WriterId/manifest prefix and ``shadow_composition_fp``,
comparison publish-only, no money-path authority.
"""

from __future__ import annotations

from typing import Final

from qmn.mis.catalog import (
    DEGRADED_SENSORS_PRODUCER_ID,
    FEED_STATE_PRODUCER_ID,
    FITTED_PRODUCER_IDS,
    GAP_EVENT_PRODUCER_ID,
    IDENTITY_PRODUCER_ID,
    LIQUIDITY_STRESS_PRODUCER_ID,
    MIS_PRODUCER_SURFACE,
    REGIME_CLASSIFIER_PRODUCER_ID,
    RULE_BASED_PRODUCER_IDS,
    SPREAD_STATE_PRODUCER_ID,
    UNAUTHORITATIVE_CANDIDATES,
    V1_GOVERNED_PRODUCER_IDS,
    AlignmentPolicy,
    ConfiguredMisProducer,
    FormulaNature,
    FrontierFrame,
    MisFormula,
    MisProducerCatalog,
    MisProducerRole,
    ProducerEmission,
    SpreadState,
    SqsBaselineArtifact,
    configure_mis_producer,
    empty_mis_catalog,
    mis_formula,
    refuse_trained_regime_classifier,
    refuse_unauthoritative_candidate,
    register_mis_producer,
    v1_formula_catalog,
    v1_mis_inventory,
)
from qmn.mis.labelers import (
    assemble_governed_snapshot,
    evaluate_degraded_sensors,
    evaluate_feed_state,
    evaluate_gap_event,
    evaluate_identity,
    evaluate_mis_producer,
    evaluate_spread_state,
    evaluate_sqs,
)
from qmn.mis.liquidity import (
    LiquidityFitArtifact,
    evaluate_liquidity_stress,
    exact_nearest_rank_quantile,
    fit_liquidity_quantiles,
)
from qmn.mis.shadow import (
    MONEY_PATH_CONSUMERS,
    SHADOW_COMPARISON_PROJECTION_KEY,
    SHADOW_COUNTED_TOWARD_MAX_SLICE_LATENCY,
    SHADOW_HAS_MONEY_PATH_AUTHORITY,
    SHADOW_ISOLATION_FAILURE_ID,
    SHADOW_LANE_PUBLISH_BOUND_VARIABLE,
    SHADOW_MANIFEST_PREFIX,
    SHADOW_SURFACE,
    SHADOW_WRITER_ROLE,
    SHADOW_WRITER_STREAM,
    ShadowCandidateCatalog,
    ShadowComparisonRecord,
    ShadowCondition,
    ShadowEvaluation,
    ShadowLaneConfig,
    ShadowPublication,
    allocate_shadow_writer,
    assemble_shadow_snapshot,
    compare_shadow_to_governed,
    empty_shadow_catalog,
    evaluate_shadow_lane,
    publish_shadow_snapshot,
    refuse_shadow_governed_wiring,
    refuse_shadow_light_claim,
    refuse_shadow_money_path,
    register_shadow_candidate,
    shadow_candidate_identities,
    shadow_comparison_projection,
    shadow_writer_stream_pair,
)
from qmn.mis.signal_snapshot import (
    DECISION_FRESHNESS_BOUND_VARIABLE,
    GOVERNED_CONSUMERS,
    SIGNAL_SNAPSHOT_FORMAT_VERSION,
    SIGNAL_SNAPSHOT_SURFACE,
    SQS_PRODUCER_ID,
    CanonicalFeedState,
    GovernedConsumer,
    ProducerReadiness,
    ProducerSlot,
    SignalSnapshot,
    SnapshotLane,
    SqsBaselineKey,
    SqsReading,
    check_snapshot_freshness,
    consume_signal_snapshot,
    mint_signal_snapshot,
    refuse_bot_consumer,
    sqs_baseline_key,
)

__all__ = [
    "DECISION_FRESHNESS_BOUND_VARIABLE",
    "DEGRADED_SENSORS_PRODUCER_ID",
    "FEED_STATE_PRODUCER_ID",
    "FITTED_PRODUCER_IDS",
    "GAP_EVENT_PRODUCER_ID",
    "GOVERNED_CONSUMERS",
    "IDENTITY_PRODUCER_ID",
    "LIQUIDITY_STRESS_PRODUCER_ID",
    "MIS_PRODUCER_SURFACE",
    "MIS_SURFACE",
    "MONEY_PATH_CONSUMERS",
    "REGIME_CLASSIFIER_PRODUCER_ID",
    "RULE_BASED_PRODUCER_IDS",
    "SHADOW_COMPARISON_PROJECTION_KEY",
    "SHADOW_COUNTED_TOWARD_MAX_SLICE_LATENCY",
    "SHADOW_HAS_MONEY_PATH_AUTHORITY",
    "SHADOW_ISOLATION_FAILURE_ID",
    "SHADOW_LANE_PUBLISH_BOUND_VARIABLE",
    "SHADOW_MANIFEST_PREFIX",
    "SHADOW_SURFACE",
    "SHADOW_WRITER_ROLE",
    "SHADOW_WRITER_STREAM",
    "SIGNAL_SNAPSHOT_FORMAT_VERSION",
    "SIGNAL_SNAPSHOT_SURFACE",
    "SPREAD_STATE_PRODUCER_ID",
    "SQS_PRODUCER_ID",
    "UNAUTHORITATIVE_CANDIDATES",
    "V1_GOVERNED_PRODUCER_IDS",
    "AlignmentPolicy",
    "CanonicalFeedState",
    "ConfiguredMisProducer",
    "FormulaNature",
    "FrontierFrame",
    "GovernedConsumer",
    "LiquidityFitArtifact",
    "MisFormula",
    "MisProducerCatalog",
    "MisProducerRole",
    "ProducerEmission",
    "ProducerReadiness",
    "ProducerSlot",
    "ShadowCandidateCatalog",
    "ShadowComparisonRecord",
    "ShadowCondition",
    "ShadowEvaluation",
    "ShadowLaneConfig",
    "ShadowPublication",
    "SignalSnapshot",
    "SnapshotLane",
    "SpreadState",
    "SqsBaselineArtifact",
    "SqsBaselineKey",
    "SqsReading",
    "allocate_shadow_writer",
    "assemble_governed_snapshot",
    "assemble_shadow_snapshot",
    "check_snapshot_freshness",
    "compare_shadow_to_governed",
    "configure_mis_producer",
    "consume_signal_snapshot",
    "empty_mis_catalog",
    "empty_shadow_catalog",
    "evaluate_degraded_sensors",
    "evaluate_feed_state",
    "evaluate_gap_event",
    "evaluate_identity",
    "evaluate_liquidity_stress",
    "evaluate_mis_producer",
    "evaluate_shadow_lane",
    "evaluate_spread_state",
    "evaluate_sqs",
    "exact_nearest_rank_quantile",
    "fit_liquidity_quantiles",
    "mint_signal_snapshot",
    "mis_formula",
    "publish_shadow_snapshot",
    "refuse_bot_consumer",
    "refuse_shadow_governed_wiring",
    "refuse_shadow_light_claim",
    "refuse_shadow_money_path",
    "refuse_trained_regime_classifier",
    "refuse_unauthoritative_candidate",
    "register_mis_producer",
    "register_shadow_candidate",
    "shadow_candidate_identities",
    "shadow_comparison_projection",
    "shadow_writer_stream_pair",
    "sqs_baseline_key",
    "v1_formula_catalog",
    "v1_mis_inventory",
]

MIS_SURFACE: Final[str] = "qmn.mis"
