"""Ontology nouns: Desk → Role → Quant → Agent → Subagent, plus Session/Mission/Task.

AD-7 / DEC-0306 / FR-Q06 — definitions only.
"""

from __future__ import annotations

from qma.core.ontology.actor_id import (
    ACTOR_ID_PREFIX,
    SLUG_MAX_LEN,
    SLUG_MIN_LEN,
    SLUG_PATTERN,
    ActorId,
    is_valid_slug_form,
    validate_slug_form,
)
from qma.core.ontology.chain import (
    ONTOLOGY_CHAIN,
    ONTOLOGY_OBJECTS,
    RUN_CONTAINER,
    WORK_VOCABULARY,
    is_ontology_object,
)
from qma.core.ontology.creation import (
    CREATION_ACTS,
    CreationAct,
    CreationRequest,
    SlugIndex,
    authorize_creation,
    create_desk,
    create_quant,
    validate_desk_slug,
    validate_quant_slug,
)
from qma.core.ontology.desks import (
    DESK_DISPLAY_NAMES,
    DESK_PREFIX_TOKENS,
    DESK_SLUG_VALUES,
    ROLE_DISPLAY_NAMES,
    ROLE_SLUG_COLLISION_KEYS,
    DeskSlug,
    OntologyError,
    RoleName,
    assert_role_names_are_not_desk_names,
    role_slug_collision_key,
)
from qma.core.ontology.records import (
    PROFILE_FORBIDDEN_USES,
    Agent,
    Desk,
    Goal,
    Mission,
    Profile,
    Quant,
    Role,
    Session,
    SlugTombstone,
    Subagent,
    Task,
    Worker,
    assert_profile_presentation_only,
    retire_desk,
    retire_quant,
)
from qma.core.ontology.wake_policy import (
    MAX_WAKES_PER_WINDOW_REGISTRY_KEY,
    QUANT_WRITE_COMMAND,
    QUIET_HOURS_REGISTRY_KEY,
    WAKE_CONDITION_ANY,
    WAKE_POLICY_EDITABILITY,
    WAKE_POLICY_HOME,
    WAKE_POLICY_SCOPE,
    QuietHours,
    WakePolicy,
    authorize_quant_write,
    is_wake_condition,
    parse_quiet_hours,
    parse_wake_policy,
    refuse_model_wake_policy_write,
    source_may_write_wake_policy,
    wake_conditions_match,
)

__all__ = [
    "ACTOR_ID_PREFIX",
    "CREATION_ACTS",
    "DESK_DISPLAY_NAMES",
    "DESK_PREFIX_TOKENS",
    "DESK_SLUG_VALUES",
    "MAX_WAKES_PER_WINDOW_REGISTRY_KEY",
    "ONTOLOGY_CHAIN",
    "ONTOLOGY_OBJECTS",
    "PROFILE_FORBIDDEN_USES",
    "QUANT_WRITE_COMMAND",
    "QUIET_HOURS_REGISTRY_KEY",
    "ROLE_DISPLAY_NAMES",
    "ROLE_SLUG_COLLISION_KEYS",
    "RUN_CONTAINER",
    "SLUG_MAX_LEN",
    "SLUG_MIN_LEN",
    "SLUG_PATTERN",
    "WAKE_CONDITION_ANY",
    "WAKE_POLICY_EDITABILITY",
    "WAKE_POLICY_HOME",
    "WAKE_POLICY_SCOPE",
    "WORK_VOCABULARY",
    "ActorId",
    "Agent",
    "CreationAct",
    "CreationRequest",
    "Desk",
    "DeskSlug",
    "Goal",
    "Mission",
    "OntologyError",
    "Profile",
    "Quant",
    "QuietHours",
    "Role",
    "RoleName",
    "Session",
    "SlugIndex",
    "SlugTombstone",
    "Subagent",
    "Task",
    "WakePolicy",
    "Worker",
    "assert_profile_presentation_only",
    "assert_role_names_are_not_desk_names",
    "authorize_creation",
    "authorize_quant_write",
    "create_desk",
    "create_quant",
    "is_ontology_object",
    "is_valid_slug_form",
    "is_wake_condition",
    "parse_quiet_hours",
    "parse_wake_policy",
    "refuse_model_wake_policy_write",
    "retire_desk",
    "retire_quant",
    "role_slug_collision_key",
    "source_may_write_wake_policy",
    "validate_desk_slug",
    "validate_quant_slug",
    "validate_slug_form",
    "wake_conditions_match",
]
