"""Composition root surface (TN-2): doors → preflight → compose → fingerprint → seal.

The host is the only impure shell that owns ambient time, broker sessions,
secrets, async at the venue edge and doors, and real money. Story 25.3 mints
identity-bearing Compose records through the qmf-registry Registrar exactly
once per fingerprint. Story 25.4 persists the sealed composition occurrence
and append-only CT-07 lineage through the registry→data edge; a sink refusal
blocks readiness rather than dropping an edge. Story 25.5 binds doors first,
writes the boot-attempt record under the reserved supervisor WriterId, then
runs the ordered ceremony — only a door-bind failure exits nonzero; later
detected refusals enter stand-down-alive. Story 25.6 owns safe points,
stand-down-alive, watchdog/slice-progress, requested-restart exit 75, and the
SIGTERM/UNKNOWN shutdown contract. Story 25.14 evaluates light/heavy four-bound
claims over assembled definitions at Compose and refuses contradictions before
Seal — child modules never self-approve the effective composition class.
Story 25.16 proves host concurrency and backpressure under deterministic load
without inventing capacity numbers. Story 26.19 proves seat-callback
concurrency and end-to-end backpressure on the same seams (E15-F02).
Story 26.11 admits the assembled runtime risk graph at Compose (cardinalities
and referential integrity together) and runs the technical demo shakedown
without a live binding — evidence for the human signature, never performance
proof (FTR-07). Story 26.14 is the D010 runtime risk gate: one executable pass
over the composition root that wires CT-22/23/24/25/27/28/29/30/31/32, fails
unwired import-only contracts, and never treats paper profit as proof.
Story 28.1 assembles the paper-milestone readiness packet (gates, 71-row
settings status, failure register, compiled demo roster) without procuring a
VPS or inventing KSA/latency numbers; soak-local human inputs are blocked ACs.
Story 28.3 injects command, uncertainty, protection, and reconciliation failure
paths through the conformance double without a live demo account (FTR-07).
Story 28.4 proves lifecycle, security, recovery, and no-authority operations
as injected campaigns and DevOps recipes — crash/preflight/quarantine/clock/
disk/shutdown plus powers/secret probes — and skips a real VPS firewall
campaign and a real bucket restore (AR-87).
Story 28.5 wires SCN-0006/0008/0010/0011 through the sealed composition with
TN-23 fixture metadata; synthetic data proves infrastructure/failure only and
FTR-07 invents no KSA numbers.
Story 28.6 publishes a machine-readable closure matrix for every named node
QA-debt ID plus the permanent battery; a missing story/evidence link fails
rather than inheriting, foundation debt stays foundation, and mutmut is not
a factory gate (zero classified mutants fail closed).
Story 28.7 records first-hours VPS and storage baselines through the
test-status harness (variance-derived thresholds, watched ~50 ms never a
gate, storage against vps_disk_budget); it does not require a real VPS and
skips soak-local procurement (FTR-07 / E9-F04).
Child modules and doors never restamp, never hold a registry cache, and never
persist lineage.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

from qmn.host.boot_ceremony import (
    BOOT_BOUND_SURFACES,
    BOOT_CEREMONY_SURFACE,
    BOOT_STAGES,
    CHECK_MODE_EXIT_ON_REFUSAL,
    CHECK_MODE_OPENS_SEQUENCER,
    CHECK_MODE_PREFLIGHT_CHECKS,
    DOOR_BIND_FAILURE_EXIT_CODE,
    FULL_PREFLIGHT_CHECKS,
    HAS_OPERATOR_CLI,
    SUPERVISOR_ROLE,
    SUPERVISOR_STREAM,
    BootAttemptRecord,
    BootCeremonyOutcome,
    BoundSupervisorDoors,
    CompositionFingerprintInputs,
    InMemoryBootAttemptSink,
    PreflightFacts,
    SealedBootEpoch,
    WriterAllocation,
    allocate_writer_ids,
    bind_supervisor_doors,
    compute_composition_fp,
    preflight_checks_for_mode,
    reserved_supervisor_writer,
    run_boot_ceremony,
    run_check_mode,
    supervisor_writer_is_reserved,
)
from qmn.host.concurrency import (
    CONCURRENCY_SURFACE,
    SEAT_CONCURRENCY_OWNED_BY,
    BoundCrossingKind,
    BoundCrossingRecord,
    ConcurrencyLoad,
    ConcurrencyProofReport,
    InjectedBounds,
    prove_host_concurrency,
)
from qmn.host.failure_campaign import (
    DESIGNED_DEGRADED_STATES,
    FAILURE_CAMPAIGN_CLASS,
    FAILURE_CAMPAIGN_FORMAT_VERSION,
    FAILURE_CAMPAIGN_SURFACE,
    INJECTED_COMMAND_FAULTS,
    PROTECTION_COINCIDENCE_FIXTURES,
    REQUIRES_LIVE_DEMO_ACCOUNT,
    FailureCampaignInputs,
    FailureCampaignReport,
    refuse_live_demo_account_required,
    run_paper_milestone_failure_campaign,
)
from qmn.host.golden_scenarios import (
    GOLDEN_PROOF_KEYS,
    GOLDEN_SCENARIO_CLASS,
    GOLDEN_SCENARIO_FORMAT_VERSION,
    GOLDEN_SCENARIO_IDS,
    GOLDEN_SCENARIO_SURFACE,
    SOURCE_CLASS_SYNTHETIC,
    TRADING_EDGE_IS_PROOF,
    GoldenFixtureProof,
    GoldenScenarioInputs,
    GoldenScenarioReport,
    refuse_golden_invented_ksa_or_latency,
    refuse_golden_trading_edge_claim,
    run_paper_milestone_golden_scenarios,
)
from qmn.host.lifecycle_campaign import (
    LIFECYCLE_CAMPAIGN_CLASS,
    LIFECYCLE_CAMPAIGN_FORMAT_VERSION,
    LIFECYCLE_CAMPAIGN_SURFACE,
    LIFECYCLE_INJECTIONS,
    RUNS_LIVE_BUCKET_RESTORE,
    RUNS_LIVE_VPS_FIREWALL,
    DiskHeadroomBand,
    DiskHeadroomDecision,
    LifecycleCampaignInputs,
    LifecycleCampaignReport,
    evaluate_disk_headroom,
    refuse_live_bucket_restore,
    refuse_live_vps_firewall_campaign,
    run_paper_milestone_lifecycle_campaign,
)
from qmn.host.light_heavy import (
    CHILD_MODULES_MAY_SELF_APPROVE,
    LIGHT_HEAVY_SURFACE,
    WORKLOAD_KINDS,
    CompositionClass,
    CompositionClassAssignment,
    FourBoundDeclaration,
    ResolvedCompositionClasses,
    WorkloadClaim,
    WorkloadKind,
    evaluate_workload_claim,
    guard_synchronous_placement,
    resolve_composition_classes,
    workload_claim_identity_content,
)
from qmn.host.lineage_persist import (
    COMPOSITION_LINEAGE_STREAM,
    COMPOSITION_OCCURRENCE_FORMAT_VERSION,
    COMPOSITION_OCCURRENCE_KIND,
    LINEAGE_PERSIST_SURFACE,
    OCCURRENCE_LINEAGE_EDGE_TYPE,
    CarriesLedgerEdgeRequest,
    CompositionCiteSet,
    CompositionLineageReceipt,
    carries_ledger_edge,
    composition_cite_set,
    continues_performance_edge,
    install_composition_occurrence_kind,
    persist_composition_lineage,
    persist_explicit_lineage_edge,
)
from qmn.host.qa_debt_matrix import (
    FACTORY_GATES,
    FOUNDATION_DEBT_IDS,
    MUTATION_MONEY_PATH_MODULES,
    MUTMUT_CONFIG_RELATIVE,
    MUTMUT_IS_FACTORY_GATE,
    NODE_QA_DEBT_IDS,
    PERMANENT_BATTERY_ITEMS,
    QA_DEBT_MATRIX_CLASS,
    QA_DEBT_MATRIX_FORMAT_VERSION,
    QA_DEBT_MATRIX_SURFACE,
    ZERO_CLASSIFIED_MUTANT_FAILS_CLOSED,
    BatteryItem,
    MutationStatus,
    QaDebtClosureMatrix,
    QaDebtGateInputs,
    QaDebtRow,
    evaluate_mutation_verdict,
    refuse_foundation_reclassified,
    refuse_inherited_or_implicit,
    refuse_missing_qa_debt_link,
    refuse_zero_classified_mutants,
    run_paper_milestone_qa_debt_gate,
    workspace_root,
)
from qmn.host.readiness import (
    FTR07_UNSETTABLE_NAMES,
    GO_LIVE_ONLY_HUMAN_INPUTS,
    INVENTS_KSA_OR_LATENCY,
    LIVE_SENSING_HUMAN_INPUTS,
    MACHINE_GATES,
    PROCURES_VPS,
    READINESS_PACKET_CLASS,
    READINESS_PACKET_FORMAT_VERSION,
    READINESS_SURFACE,
    SERIALIZES_UNRELATED_WORK,
    SOAK_LOCAL_HUMAN_INPUTS,
    VPS_PROCUREMENT_STARTING_POINT,
    ArtifactCitation,
    CompiledDemoRoster,
    GateResult,
    HumanInputRecord,
    HumanInputScope,
    ReadinessPacket,
    SettingsStatusReport,
    VpsProcurementEvidence,
    assemble_paper_milestone_readiness,
    compile_demo_roster,
    list_readiness_human_inputs,
    refuse_invented_ksa_or_latency_number,
    refuse_procure_vps,
    refuse_ratified_vps_minimum,
    refuse_unrelated_epic_blocker,
    settings_status_from_config,
)
from qmn.host.registry_mint import (
    COMPOSE_KIND_FORMAT_VERSION,
    COMPOSE_RECORD_KINDS,
    DOOR_LOCAL_REGISTRY_CACHE,
    HAS_ALTERNATE_IDENTITY_FUNCTION,
    IDENTITY_FORBIDDEN_OCCURRENCE_KEYS,
    REGISTRY_MINT_SURFACE,
    ComposeOccurrenceEvidence,
    CompositionRootRegistry,
    compose_kind_contract,
    install_compose_kinds,
    mint_compose_record,
)
from qmn.host.risk_population import (
    LAYER1_CHECKS,
    MISMATCH_REFUSES_BEFORE_SEAL,
    RISK_POPULATION_SURFACE,
    CapabilityRecord,
    Layer1PopulationProof,
    PairedTargetRecord,
    PopulationBindingRecord,
    PopulationBmsRecord,
    PopulationBookRecord,
    PriorityRecord,
    RuntimeRiskGraph,
    ScopeRecord,
    SeatRecord,
    WindowRecord,
    admit_runtime_risk_population,
)
from qmn.host.runtime_risk_gate import (
    MANUAL_OBSERVATION_IS_PROOF,
    PAPER_PROFIT_IS_PROOF,
    REQUIRED_RISK_CONTRACTS,
    RUNTIME_RISK_GATE_SURFACE,
    RUNTIME_RISK_SCENARIOS,
    RiskContractWiring,
    RuntimeRiskCoverageReport,
    RuntimeRiskGateInputs,
    RuntimeRiskGateReport,
    evaluate_runtime_risk_coverage,
    qmn_production_src_root,
    refuse_manual_observation_as_proof,
    refuse_paper_profit_as_proof,
    run_runtime_risk_gate,
)
from qmn.host.seat_concurrency import (
    SEAT_CONCURRENCY_SURFACE,
    SeatConcurrencyLoad,
    SeatConcurrencyProofReport,
    SeatInjectedBounds,
    SeatIsolationRecord,
    prove_seat_concurrency,
)
from qmn.host.security_probes import (
    DEVOPS_FORBIDDEN_ACTIONS,
    SECURITY_PROBE_NAMES,
    SECURITY_PROBES_CLASS,
    SECURITY_PROBES_FORMAT_VERSION,
    SECURITY_PROBES_SURFACE,
    SecurityProbeInputs,
    SecurityProbeReport,
    devops_recipe_may_trade,
    refuse_live_vps_firewall_probe,
    run_paper_milestone_security_probes,
)
from qmn.host.shakedown import (
    SHAKEDOWN_EXERCISES,
    SHAKEDOWN_FOR_HUMAN_SIGNATURE,
    SHAKEDOWN_IS_PERFORMANCE_PROOF,
    SHAKEDOWN_SURFACE,
    ShakedownEvidence,
    ShakedownPlan,
    ShakedownSignaturePage,
    assemble_shakedown_signature_page,
    refuse_invented_soak_or_ksa_number,
    refuse_shakedown_as_performance_proof,
    run_demo_shakedown,
)
from qmn.host.supervise import (
    ASYNC_ALLOWED_SURFACES,
    CLEAN_STOP_EXIT_CODE,
    DOMAIN_BACKGROUND_THREADS_ALLOWED,
    DRAIN_WINDOW_BREACH_EXIT_CODE,
    EVENT_LOOP_COUNT,
    NODE_RESURRECT_SUBTYPE,
    OPERATOR_PRINCIPAL,
    REQUESTED_RESTART_EXIT_CODE,
    REQUESTED_RESTART_REASON,
    SUPERVISION_SURFACE,
    CommandFate,
    CrashLoopFold,
    CrashLoopVerdict,
    DrainOutcome,
    LifecycleState,
    LifecycleSupervisor,
    NotifyTransport,
    RecordingNotifyTransport,
    ResurrectReceipt,
    SafePointSnapshot,
    ShutdownKind,
    SliceProgressTrip,
    StandDownTrigger,
    StdlibSdNotifyTransport,
    SupervisionConfig,
    admit_under_lifecycle,
    evaluate_safe_point,
    notify_ready,
    notify_watchdog,
    notify_watchdog_trigger,
    sd_notify,
    supervision_process_model,
)

__all__ = [
    "ASYNC_ALLOWED_SURFACES",
    "BOOT_BOUND_SURFACES",
    "BOOT_CEREMONY_STEPS",
    "BOOT_CEREMONY_SURFACE",
    "BOOT_STAGES",
    "CHECK_MODE_EXIT_ON_REFUSAL",
    "CHECK_MODE_OPENS_SEQUENCER",
    "CHECK_MODE_PREFLIGHT_CHECKS",
    "CHILD_MODULES_MAY_SELF_APPROVE",
    "CLEAN_STOP_EXIT_CODE",
    "COMPOSE_KIND_FORMAT_VERSION",
    "COMPOSE_RECORD_KINDS",
    "COMPOSITION_LINEAGE_STREAM",
    "COMPOSITION_OCCURRENCE_FORMAT_VERSION",
    "COMPOSITION_OCCURRENCE_KIND",
    "COMPOSITION_ROOT_SURFACE",
    "CONCURRENCY_SURFACE",
    "DESIGNED_DEGRADED_STATES",
    "DEVOPS_FORBIDDEN_ACTIONS",
    "DOMAIN_BACKGROUND_THREADS_ALLOWED",
    "DOOR_BIND_FAILURE_EXIT_CODE",
    "DOOR_LOCAL_REGISTRY_CACHE",
    "DRAIN_WINDOW_BREACH_EXIT_CODE",
    "EVENT_LOOP_COUNT",
    "FACTORY_GATES",
    "FAILURE_CAMPAIGN_CLASS",
    "FAILURE_CAMPAIGN_FORMAT_VERSION",
    "FAILURE_CAMPAIGN_SURFACE",
    "FOUNDATION_DEBT_IDS",
    "FTR07_UNSETTABLE_NAMES",
    "FULL_PREFLIGHT_CHECKS",
    "GOLDEN_PROOF_KEYS",
    "GOLDEN_SCENARIO_CLASS",
    "GOLDEN_SCENARIO_FORMAT_VERSION",
    "GOLDEN_SCENARIO_IDS",
    "GOLDEN_SCENARIO_SURFACE",
    "GO_LIVE_ONLY_HUMAN_INPUTS",
    "HAS_ALTERNATE_IDENTITY_FUNCTION",
    "HAS_OPERATOR_CLI",
    "IDENTITY_FORBIDDEN_OCCURRENCE_KEYS",
    "INJECTED_COMMAND_FAULTS",
    "INVENTS_KSA_OR_LATENCY",
    "LAYER1_CHECKS",
    "LIFECYCLE_CAMPAIGN_CLASS",
    "LIFECYCLE_CAMPAIGN_FORMAT_VERSION",
    "LIFECYCLE_CAMPAIGN_SURFACE",
    "LIFECYCLE_INJECTIONS",
    "LIGHT_HEAVY_SURFACE",
    "LINEAGE_PERSIST_SURFACE",
    "LIVE_SENSING_HUMAN_INPUTS",
    "MACHINE_GATES",
    "MANUAL_OBSERVATION_IS_PROOF",
    "MISMATCH_REFUSES_BEFORE_SEAL",
    "MUTATION_MONEY_PATH_MODULES",
    "MUTMUT_CONFIG_RELATIVE",
    "MUTMUT_IS_FACTORY_GATE",
    "NODE_QA_DEBT_IDS",
    "NODE_RESURRECT_SUBTYPE",
    "OCCURRENCE_LINEAGE_EDGE_TYPE",
    "OPERATOR_PRINCIPAL",
    "PAPER_PROFIT_IS_PROOF",
    "PERMANENT_BATTERY_ITEMS",
    "PROCURES_VPS",
    "PROTECTION_COINCIDENCE_FIXTURES",
    "QA_DEBT_MATRIX_CLASS",
    "QA_DEBT_MATRIX_FORMAT_VERSION",
    "QA_DEBT_MATRIX_SURFACE",
    "READINESS_PACKET_CLASS",
    "READINESS_PACKET_FORMAT_VERSION",
    "READINESS_SURFACE",
    "REGISTRY_MINT_SURFACE",
    "REQUESTED_RESTART_EXIT_CODE",
    "REQUESTED_RESTART_REASON",
    "REQUIRED_RISK_CONTRACTS",
    "REQUIRES_LIVE_DEMO_ACCOUNT",
    "RISK_POPULATION_SURFACE",
    "RUNS_LIVE_BUCKET_RESTORE",
    "RUNS_LIVE_VPS_FIREWALL",
    "RUNTIME_RISK_GATE_SURFACE",
    "RUNTIME_RISK_SCENARIOS",
    "SEAT_CONCURRENCY_OWNED_BY",
    "SEAT_CONCURRENCY_SURFACE",
    "SECURITY_PROBES_CLASS",
    "SECURITY_PROBES_FORMAT_VERSION",
    "SECURITY_PROBES_SURFACE",
    "SECURITY_PROBE_NAMES",
    "SERIALIZES_UNRELATED_WORK",
    "SHAKEDOWN_EXERCISES",
    "SHAKEDOWN_FOR_HUMAN_SIGNATURE",
    "SHAKEDOWN_IS_PERFORMANCE_PROOF",
    "SHAKEDOWN_SURFACE",
    "SOAK_LOCAL_HUMAN_INPUTS",
    "SOURCE_CLASS_SYNTHETIC",
    "SUPERVISION_SURFACE",
    "SUPERVISOR_ROLE",
    "SUPERVISOR_STREAM",
    "TRADING_EDGE_IS_PROOF",
    "VPS_PROCUREMENT_STARTING_POINT",
    "WORKLOAD_KINDS",
    "ZERO_CLASSIFIED_MUTANT_FAILS_CLOSED",
    "ArtifactCitation",
    "BatteryItem",
    "BootAttemptRecord",
    "BootCeremonyOutcome",
    "BoundCrossingKind",
    "BoundCrossingRecord",
    "BoundSupervisorDoors",
    "CapabilityRecord",
    "CarriesLedgerEdgeRequest",
    "CommandFate",
    "CompiledDemoRoster",
    "ComposeOccurrenceEvidence",
    "CompositionCiteSet",
    "CompositionClass",
    "CompositionClassAssignment",
    "CompositionFingerprintInputs",
    "CompositionLineageReceipt",
    "CompositionRootRegistry",
    "ConcurrencyLoad",
    "ConcurrencyProofReport",
    "CrashLoopFold",
    "CrashLoopVerdict",
    "DiskHeadroomBand",
    "DiskHeadroomDecision",
    "DrainOutcome",
    "FailureCampaignInputs",
    "FailureCampaignReport",
    "FourBoundDeclaration",
    "GateResult",
    "GoldenFixtureProof",
    "GoldenScenarioInputs",
    "GoldenScenarioReport",
    "HumanInputRecord",
    "HumanInputScope",
    "InMemoryBootAttemptSink",
    "InjectedBounds",
    "Layer1PopulationProof",
    "LifecycleCampaignInputs",
    "LifecycleCampaignReport",
    "LifecycleState",
    "LifecycleSupervisor",
    "MutationStatus",
    "NotifyTransport",
    "PairedTargetRecord",
    "PopulationBindingRecord",
    "PopulationBmsRecord",
    "PopulationBookRecord",
    "PreflightFacts",
    "PriorityRecord",
    "QaDebtClosureMatrix",
    "QaDebtGateInputs",
    "QaDebtRow",
    "ReadinessPacket",
    "RecordingNotifyTransport",
    "ResolvedCompositionClasses",
    "ResurrectReceipt",
    "RiskContractWiring",
    "RuntimeRiskCoverageReport",
    "RuntimeRiskGateInputs",
    "RuntimeRiskGateReport",
    "RuntimeRiskGraph",
    "SafePointSnapshot",
    "ScopeRecord",
    "SealedBootEpoch",
    "SealedComposition",
    "SeatConcurrencyLoad",
    "SeatConcurrencyProofReport",
    "SeatInjectedBounds",
    "SeatIsolationRecord",
    "SeatRecord",
    "SecurityProbeInputs",
    "SecurityProbeReport",
    "SettingsStatusReport",
    "ShakedownEvidence",
    "ShakedownPlan",
    "ShakedownSignaturePage",
    "ShutdownKind",
    "SliceProgressTrip",
    "StandDownTrigger",
    "StdlibSdNotifyTransport",
    "SupervisionConfig",
    "VpsProcurementEvidence",
    "WindowRecord",
    "WorkloadClaim",
    "WorkloadKind",
    "WriterAllocation",
    "admit_runtime_risk_population",
    "admit_under_lifecycle",
    "allocate_writer_ids",
    "assemble_paper_milestone_readiness",
    "assemble_shakedown_signature_page",
    "bind_supervisor_doors",
    "carries_ledger_edge",
    "ceremony_steps",
    "compile_demo_roster",
    "compose_kind_contract",
    "composition_cite_set",
    "compute_composition_fp",
    "continues_performance_edge",
    "devops_recipe_may_trade",
    "evaluate_disk_headroom",
    "evaluate_mutation_verdict",
    "evaluate_runtime_risk_coverage",
    "evaluate_safe_point",
    "evaluate_workload_claim",
    "guard_synchronous_placement",
    "install_compose_kinds",
    "install_composition_occurrence_kind",
    "list_readiness_human_inputs",
    "mint_compose_record",
    "notify_ready",
    "notify_watchdog",
    "notify_watchdog_trigger",
    "persist_composition_lineage",
    "persist_explicit_lineage_edge",
    "preflight_checks_for_mode",
    "prove_host_concurrency",
    "prove_seat_concurrency",
    "qmn_production_src_root",
    "refuse_foundation_reclassified",
    "refuse_golden_invented_ksa_or_latency",
    "refuse_golden_trading_edge_claim",
    "refuse_inherited_or_implicit",
    "refuse_invented_ksa_or_latency_number",
    "refuse_invented_soak_or_ksa_number",
    "refuse_live_bucket_restore",
    "refuse_live_demo_account_required",
    "refuse_live_vps_firewall_campaign",
    "refuse_live_vps_firewall_probe",
    "refuse_manual_observation_as_proof",
    "refuse_missing_qa_debt_link",
    "refuse_paper_profit_as_proof",
    "refuse_procure_vps",
    "refuse_ratified_vps_minimum",
    "refuse_shakedown_as_performance_proof",
    "refuse_unrelated_epic_blocker",
    "refuse_zero_classified_mutants",
    "reserved_supervisor_writer",
    "resolve_composition_classes",
    "run_boot_ceremony",
    "run_check_mode",
    "run_demo_shakedown",
    "run_paper_milestone_failure_campaign",
    "run_paper_milestone_golden_scenarios",
    "run_paper_milestone_lifecycle_campaign",
    "run_paper_milestone_qa_debt_gate",
    "run_paper_milestone_security_probes",
    "run_runtime_risk_gate",
    "sd_notify",
    "settings_status_from_config",
    "supervision_process_model",
    "supervisor_writer_is_reserved",
    "workload_claim_identity_content",
    "workspace_root",
]

COMPOSITION_ROOT_SURFACE: Final[str] = "qmn.host"
BOOT_CEREMONY_STEPS: Final[tuple[str, ...]] = (
    "preflight",
    "compose",
    "fingerprint",
    "seal",
)


@dataclass(frozen=True, slots=True)
class SealedComposition:
    """Marker for one sealed boot-epoch composition.

    Lineage persistence (Story 25.4) binds ``composition_fp`` and readiness after
    the registry→data sink accepts the occurrence and its edges. The scaffold
    defaults keep ceremony labels available before that write. Story 25.5 seals
    through :func:`run_boot_ceremony` / :class:`SealedBootEpoch`.
    """

    surface: str = COMPOSITION_ROOT_SURFACE
    sealed: bool = True
    ready: bool = False

    def steps(self) -> tuple[str, ...]:
        return BOOT_CEREMONY_STEPS


def ceremony_steps() -> tuple[str, ...]:
    """Ordered compose → fingerprint → seal ceremony (plus preflight gate)."""
    return BOOT_CEREMONY_STEPS
